// 영문 선수명 → 한글 표시명 매핑.
// api-football / ESPN 응답이 영문이라 UI/LLM 입력 시에만 한글로 변환.
// 외래어 표기법 + 한국 스포츠 미디어 굳어진 표기 우선.

import { K_LEAGUE_PLAYER_NAMES_KO } from "./sports/k-league-player-names";
import { J_LEAGUE_PLAYER_NAMES_KO } from "./sports/j-league-player-names";
import { NBA_PLAYER_NAMES_KO } from "./sports/nba-player-names";
import { NBA_PLAYER_NAMES_WIKI_KO } from "./sports/nba-player-names-wiki";
import rawNbaHaikuKo from "../../data/nba-player-names-haiku.json"; // 주간 cron 이 갱신하는 data/*.json (mac-mini)
import { NHL_PLAYER_NAMES_KO } from "./sports/nhl-player-names";
import { NHL_PLAYER_NAMES_WIKI_KO } from "./sports/nhl-player-names-wiki";
import rawNhlInjuryHaikuKo from "../../data/nhl-injury-names-haiku.json"; // NHL 부상자 보강, 주간 cron 갱신(mac-mini)
import { WNBA_PLAYER_NAMES_KO } from "./sports/wnba-player-names";
import { MLB_PLAYER_NAMES_KO } from "./sports/mlb-player-names";
import { MLB_PLAYER_NAMES_NAVER_KO } from "./sports/mlb-player-names-naver";
import { MLB_PLAYER_NAMES_HAIKU_KO } from "./sports/mlb-player-names-haiku";
import rawMlbInjuryHaikuKo from "../../data/mlb-injury-names-haiku.json"; // IL 부상자 보강, 주간 cron 갱신(mac-mini)
import { MLS_PLAYER_NAMES_KO } from "./sports/mls-player-names";
import { ESPN_LEADER_NAMES_KO } from "./sports/espn-leader-names";

const NBA_PLAYER_NAMES_HAIKU_KO = rawNbaHaikuKo as Record<string, string>;
const MLB_INJURY_NAMES_HAIKU_KO = rawMlbInjuryHaikuKo as Record<string, string>;
const NHL_INJURY_NAMES_HAIKU_KO = rawNhlInjuryHaikuKo as Record<string, string>;

const RAW: Record<string, string> = {
  // ─── EPL — Big 6 + 한국 선수 + 슈퍼스타 ───
  // 아스널
  "Bukayo Saka": "부카요 사카",
  "Martin Ødegaard": "마르틴 외데고르",
  "Martin Odegaard": "마르틴 외데고르",
  "Kai Havertz": "카이 하베르츠",
  "Gabriel Martinelli": "가브리에우 마르치넬리",
  "Gabriel Jesus": "가브리에우 제주스",
  "Declan Rice": "데클런 라이스",
  "William Saliba": "윌리암 살리바",
  "Gabriel Magalhães": "가브리에우 마갈량이스",
  "Gabriel Magalhaes": "가브리에우 마갈량이스",
  "David Raya": "다비드 라야",
  "Mikel Merino": "미켈 메리노",
  "Viktor Gyökeres": "빅토르 요케레스",
  "Viktor Gyokeres": "빅토르 요케레스",
  "Riccardo Calafiori": "리카르도 칼라피오리",
  "Jurriën Timber": "유리언 팀버",
  "Jurrien Timber": "유리언 팀버",
  "J. Timber": "유리언 팀버",
  "Piero Hincapié": "피에로 인카피에",
  "Piero Hincapie": "피에로 인카피에",
  "P. Hincapie": "피에로 인카피에",
  "Leandro Trossard": "레안드로 트로사르",
  "L. Trossard": "레안드로 트로사르",
  "Max Dowman": "맥스 다우먼",
  "M. Dowman": "맥스 다우먼",
  "Cristhian Mosquera": "크리스티안 모스케라",
  "C. Mosquera": "크리스티안 모스케라",
  "Gabriel": "가브리에우 마갈량이스",
  "Ben White": "벤 화이트",
  "Oleksandr Zinchenko": "올렉산드르 진첸코",
  "Jakub Kiwior": "야쿠브 키비오르",
  "Jorginho": "조르지뉴",
  "Thomas Partey": "토마스 파티",
  // 리버풀
  "Mohamed Salah": "모하메드 살라",
  "Virgil van Dijk": "버질 반다이크",
  "Trent Alexander-Arnold": "트렌트 알렉산더아놀드",
  "Alisson Becker": "알리송 베커",
  "Alisson": "알리송",
  "Luis Díaz": "루이스 디아스",
  "Luis Diaz": "루이스 디아스",
  "Cody Gakpo": "코디 학포",
  "Dominik Szoboszlai": "도미니크 소보슬러이",
  "Ryan Gravenberch": "라이언 흐라번베르흐",
  "Alexis Mac Allister": "알렉시스 맥 알리스터",
  "Florian Wirtz": "플로리안 비르츠",
  "Hugo Ekitiké": "위고 에키티케",
  "Hugo Ekitike": "위고 에키티케",
  "Federico Chiesa": "페데리코 키에사",
  // 맨시티
  "Erling Haaland": "엘링 홀란드",
  "Erling Braut Haaland": "엘링 홀란드",
  "E. Haaland": "엘링 홀란드",
  "Kevin De Bruyne": "케빈 더 브라위너",
  "Phil Foden": "필 포든",
  "Bernardo Silva": "베르나르두 실바",
  "B. Silva": "베르나르두 실바", // af 축약 표기 (감독 전술 집계)
  "Pep Guardiola": "펩 과르디올라",
  "Josep Guardiola": "펩 과르디올라",
  // ─── EPL 감독 (감독 전술 연구 아티클 — 25/26 실측 누락분) ───
  "Arne Slot": "아르네 슬롯",
  "Keith Andrews": "키스 앤드루스",
  "Marco Silva": "마르쿠 실바",
  "Rob Edwards": "롭 에드워즈",
  "Calum McFarlane": "칼럼 맥팔레인",
  "Enzo Maresca": "엔초 마레스카",
  "Liam Rosenior": "리암 로즈니어",
  "David Moyes": "데이비드 모예스",
  "Scott Parker": "스콧 파커",
  "Mike Jackson": "마이크 잭슨",
  "Rodri": "로드리",
  "Rúben Dias": "후벤 디아스",
  "Ruben Dias": "후벤 디아스",
  "Jérémy Doku": "제레미 도쿠",
  "Jeremy Doku": "제레미 도쿠",
  "Josko Gvardiol": "요슈코 그바르디올",
  "Joško Gvardiol": "요슈코 그바르디올",
  "Savinho": "사비뉴",
  "Ederson": "에데르송",
  "Omar Marmoush": "오마르 마르무시",
  "Tijjani Reijnders": "테이야니 레이너르스",
  // 맨유
  "Bruno Fernandes": "브루누 페르난드스",
  "Marcus Rashford": "마커스 래시퍼드",
  "Casemiro": "카제미루",
  "Casimiro": "카제미루",
  "Carlos Henrique Casimiro": "카제미루",
  "Alejandro Garnacho": "알레한드로 가르나초",
  "Rasmus Højlund": "라스무스 회일룬",
  "Rasmus Hojlund": "라스무스 회일룬",
  "André Onana": "앙드레 오나나",
  "Andre Onana": "앙드레 오나나",
  "Matheus Cunha": "마테우스 쿠냐",
  "Bryan Mbeumo": "브라이언 음베모",
  "Benjamin Šeško": "벤야민 셰슈코",
  "Benjamin Sesko": "벤야민 셰슈코",
  "Patrick Dorgu": "패트릭 도르구",
  // 첼시
  "Cole Palmer": "콜 파머",
  "Enzo Fernández": "엔소 페르난데스",
  "Enzo Fernandez": "엔소 페르난데스",
  "Moisés Caicedo": "모이세스 카이세도",
  "Moises Caicedo": "모이세스 카이세도",
  "Nicolas Jackson": "니콜라스 잭슨",
  "Pedro Neto": "페드루 네투",
  "Reece James": "리스 제임스",
  "Levi Colwill": "레비 콜윌",
  "João Pedro": "주앙 페드루",
  "Joao Pedro": "주앙 페드루",
  "Estêvão": "에스테방",
  "Estevao": "에스테방",
  "Robert Sánchez": "로베르트 산체스",
  "Robert Sanchez": "로베르트 산체스",
  // 토트넘
  "Son Heung-min": "손흥민",
  "Son Heungmin": "손흥민",
  "Heung-min Son": "손흥민",
  "Heungmin Son": "손흥민",
  "James Maddison": "제임스 매디슨",
  "Cristian Romero": "크리스티안 로메로",
  "Micky van de Ven": "미키 판데벤",
  "Brennan Johnson": "브레넌 존슨",
  "Dejan Kulusevski": "데얀 쿨루셉스키",
  "Yves Bissouma": "이브 비수마",
  "Pape Matar Sarr": "파페 마타르 사르",
  "Mohammed Kudus": "모하메드 쿠두스",
  "Xavi Simons": "샤비 시몬스",
  "Guglielmo Vicario": "굴리엘모 비카리오",
  // 기타 EPL 주요
  "Jarrod Bowen": "재럿 보언",
  "Lucas Paquetá": "루카스 파케타",
  "Lucas Paqueta": "루카스 파케타",
  "Eberechi Eze": "에베레치 에제",
  "Marc Guéhi": "마르크 게이",
  "Marc Guehi": "마르크 게이",
  "Dean Henderson": "딘 헨더슨",
  "Adam Wharton": "애덤 워튼",
  "Borna Sosa": "보르나 소사",
  "Cheick Doucouré": "셰크 두쿠레",
  "Cheick Doucoure": "셰크 두쿠레",
  "Eddie Nketiah": "에디 은케티아",
  "Daniel Muñoz": "다니엘 무뇨스",
  "Daniel Munoz": "다니엘 무뇨스",
  "Ismaïla Sarr": "이스마일라 사르",
  "Ismaila Sarr": "이스마일라 사르",
  "Jean-Philippe Mateta": "장필리프 마테타",
  "J. Mateta": "장필리프 마테타",
  "Evann Guessand": "에반 게상",
  "E. Guessand": "에반 게상",

  // 아스톤 빌라
  "Ollie Watkins": "올리 왓킨스",
  "Morgan Rogers": "모건 로저스",
  "Pau Torres": "파우 토레스",
  "Ezri Konsa": "에즈리 콘사",
  "Emiliano Martínez": "에밀리아노 마르티네스",
  "Emiliano Martinez": "에밀리아노 마르티네스",
  "Emi Martínez": "에밀리아노 마르티네스",
  "Emi Martinez": "에밀리아노 마르티네스",
  "John McGinn": "존 매긴",
  "Youri Tielemans": "유리 틸레만스",
  "Leon Bailey": "리언 베일리",
  "Donyell Malen": "도니엘 말런",

  // 뉴캐슬
  "Alexander Isak": "알렉산데르 이사크",
  "Bruno Guimarães": "브루누 기마랑이스",
  "Bruno Guimaraes": "브루누 기마랑이스",
  "Anthony Gordon": "앤서니 고든",
  "Sven Botman": "스벤 보트만",
  "Nick Pope": "닉 포프",
  "Joelinton": "조엘린통",
  "Sandro Tonali": "산드로 토날리",
  "Kieran Trippier": "키런 트리피어",
  "Fabian Schär": "파비안 셰어",
  "Fabian Schar": "파비안 셰어",
  "Sven Mislintat": "스벤 미슬린타트",
  "Yoane Wissa": "요안 위사",

  // 브라이턴
  "Kaoru Mitoma": "미토마 카오루",
  "Lewis Dunk": "루이스 던크",
  "Carlos Baleba": "카를로스 발레바",
  "Yankuba Minteh": "얀쿠바 민테",
  "Bart Verbruggen": "바르트 페르브뤼헌",
  "Pervis Estupiñán": "페르비스 에스투피냔",
  "Pervis Estupinan": "페르비스 에스투피냔",
  "Joao Pedro Junior": "주앙 페드루",

  // 노팅엄
  "Morgan Gibbs-White": "모건 깁스화이트",
  "Chris Wood": "크리스 우드",
  "Anthony Elanga": "앤서니 엘랑가",
  "Murillo": "무릴루",
  "Matz Sels": "마츠 셀스",

  // 풀럼 / 브렌트포드 / 본머스
  "Raúl Jiménez": "라울 히메네스",
  "Raul Jimenez": "라울 히메네스",
  "Antonee Robinson": "안토니 로빈슨",
  "Adama Traoré": "아다마 트라오레",
  "Adama Traore": "아다마 트라오레",
  "Bernd Leno": "베른트 레노",
  "Igor Thiago": "이고르 치아구",
  "Mikkel Damsgaard": "미켈 담스고르",
  "Antoine Semenyo": "앙투안 세메뇨",
  "Marcus Tavernier": "마커스 태버니어",
  "Justin Kluivert": "저스틴 클라위베르트",
  "Dean Huijsen": "딘 후이센",
  "Evanilson": "에바닐송",
  "Dango Ouattara": "당고 우아타라",

  // ─── 라리가 — 빅3 + 슈퍼스타 ───
  // 레알 마드리드
  "Kylian Mbappé": "킬리안 음바페",
  "Kylian Mbappe": "킬리안 음바페",
  "Vinícius Júnior": "비니시우스 주니오르",
  "Vinicius Junior": "비니시우스 주니오르",
  "Vinicius Jr.": "비니시우스 주니오르",
  "Jude Bellingham": "주드 벨링엄",
  "Rodrygo": "호드리구",
  "Federico Valverde": "페데리코 발베르데",
  "Antonio Rüdiger": "안토니오 뤼디거",
  "Antonio Rudiger": "안토니오 뤼디거",
  "Eduardo Camavinga": "에두아르도 카마빙가",
  "Thibaut Courtois": "티보 쿠르투아",
  "Aurélien Tchouaméni": "오렐리앙 추아메니",
  "Aurelien Tchouameni": "오렐리앙 추아메니",
  "Dani Carvajal": "다니 카르바할",
  "Endrick": "엔드릭",
  "Arda Güler": "아르다 귈레르",
  "Arda Guler": "아르다 귈레르",
  "Trent Alexander Arnold": "트렌트 알렉산더아놀드",
  "Álvaro Carreras": "알바로 카레라스",
  "Alvaro Carreras": "알바로 카레라스",
  // 바르셀로나
  "Lamine Yamal": "라민 야말",
  "Robert Lewandowski": "로베르트 레반도프스키",
  "Pedri": "페드리",
  "Gavi": "가비",
  "Frenkie de Jong": "프렌키 더 용",
  "Raphinha": "하피냐",
  "Marc-André ter Stegen": "마르크안드레 테어슈테겐",
  "Marc-Andre ter Stegen": "마르크안드레 테어슈테겐",
  "Marc Casadó": "마르크 카사도",
  "Marc Casado": "마르크 카사도",
  "Fermín López": "페르민 로페스",
  "Fermin Lopez": "페르민 로페스",
  "Pau Cubarsí": "파우 쿠바르시",
  "Pau Cubarsi": "파우 쿠바르시",
  "Dani Olmo": "다니 올모",
  "Joan García": "조안 가르시아",
  "Joan Garcia": "조안 가르시아",
  // AT 마드리드
  "Antoine Griezmann": "앙투안 그리즈만",
  "Julián Álvarez": "훌리안 알바레스",
  "Julian Alvarez": "훌리안 알바레스",
  "Koke": "코케",
  "Marcos Llorente": "마르코스 요렌테",
  "Álex Baena": "알렉스 바에나",
  "Alex Baena": "알렉스 바에나",
  "Giacomo Raspadori": "자코모 라스파도리",

  // ─── 분데스리가 ───
  "Harry Kane": "해리 케인",
  "Jamal Musiala": "자말 무시알라",
  "Joshua Kimmich": "요수아 키미히",
  "Leroy Sané": "르로이 사네",
  "Leroy Sane": "르로이 사네",
  "Manuel Neuer": "마누엘 노이어",
  "Thomas Müller": "토마스 뮐러",
  "Thomas Muller": "토마스 뮐러",
  "Michael Olise": "마이클 올리스",
  "Konrad Laimer": "콘라트 라이머",
  // 도르트문트
  "Karim Adeyemi": "카림 아데예미",
  "Serhou Guirassy": "세르후 기라시",
  "Julian Brandt": "율리안 브란트",
  "Marcel Sabitzer": "마르첼 자비처",
  "Jobe Bellingham": "조비 벨링엄",
  "Niclas Füllkrug": "니클라스 퓔크루크",
  "Niclas Fullkrug": "니클라스 퓔크루크",
  // 레버쿠젠 / RB 라이프치히 / 슈투트가르트
  "Granit Xhaka": "그라니트 자카",
  "Patrik Schick": "파트리크 시크",
  "Lois Openda": "루아 오펜다",
  "Loïs Openda": "루아 오펜다",
  "Deniz Undav": "데니스 운다브",

  // ─── 세리에 A ───
  // 인테르
  "Lautaro Martínez": "라우타로 마르티네스",
  "Lautaro Martinez": "라우타로 마르티네스",
  "Marcus Thuram": "마르쿠스 튀랑",
  "Nicolò Barella": "니콜로 바렐라",
  "Nicolo Barella": "니콜로 바렐라",
  "Hakan Çalhanoğlu": "하칸 찰하놀루",
  "Hakan Calhanoglu": "하칸 찰하놀루",
  // 유벤투스
  "Dušan Vlahović": "두샨 블라호비치",
  "Dusan Vlahovic": "두샨 블라호비치",
  "Adrien Rabiot": "아드리앵 라비오",
  "Kenan Yıldız": "케난 일디즈",
  "Kenan Yildiz": "케난 일디즈",
  "Jonathan David": "조너선 데이비드",
  "Khéphren Thuram": "케프랑 튀랑",
  "Khephren Thuram": "케프랑 튀랑",
  "Randal Kolo Muani": "랑달 콜로 무아니",
  // 나폴리
  "Romelu Lukaku": "로멜루 루카쿠",
  "Khvicha Kvaratskhelia": "흐비차 크바라츠헬리아",
  "Stanislav Lobotka": "스타니슬라프 로보트카",
  "Scott McTominay": "스콧 맥토미니",
  // AC밀란
  "Rafael Leão": "하파엘 레앙",
  "Rafael Leao": "하파엘 레앙",
  "Christian Pulisic": "크리스천 풀리식",
  "Theo Hernández": "테오 에르난데스",
  "Theo Hernandez": "테오 에르난데스",
  "Mike Maignan": "마이크 메냥",
  "Tammy Abraham": "태미 에이브러햄",
  // AS로마
  "Paulo Dybala": "파울로 디발라",
  "Lorenzo Pellegrini": "로렌초 펠레그리니",

  // ─── 리그 1 (PSG 위주) ───
  "Ousmane Dembélé": "우스만 뎀벨레",
  "Ousmane Dembele": "우스만 뎀벨레",
  "Désiré Doué": "데지레 두에",
  "Desire Doue": "데지레 두에",
  "Bradley Barcola": "브래들리 바르콜라",
  "João Neves": "주앙 네베스",
  "Joao Neves": "주앙 네베스",
  "Vitinha": "비치냐",
  "Fabián Ruiz": "파비안 루이스",
  "Fabian Ruiz": "파비안 루이스",
  "Achraf Hakimi": "아슈라프 하키미",
  "Marquinhos": "마르키뉴스",
  "Gianluigi Donnarumma": "잔루이지 돈나룸마",

  // ─── NBA 슈퍼스타 ───
  "LeBron James": "르브론 제임스",
  "Stephen Curry": "스테판 커리",
  "Kevin Durant": "케빈 듀란트",
  "Giannis Antetokounmpo": "야니스 아데토쿤보",
  "Nikola Jokić": "니콜라 요키치",
  "Nikola Jokic": "니콜라 요키치",
  "Luka Dončić": "루카 돈치치",
  "Luka Doncic": "루카 돈치치",
  "Jayson Tatum": "제이슨 테이텀",
  "Joel Embiid": "조엘 엠비드",
  "Shai Gilgeous-Alexander": "셰이 길저스알렉산더",
  "Anthony Edwards": "앤서니 에드워즈",
  "Anthony Davis": "앤서니 데이비스",
  "Devin Booker": "데빈 부커",
  "Damian Lillard": "데미안 릴라드",
  "Jimmy Butler": "지미 버틀러",
  "Donovan Mitchell": "도노반 미첼",
  "Trae Young": "트레이 영",
  "Ja Morant": "자 모란트",
  "Victor Wembanyama": "빅터 웸반야마",
  "Tyrese Haliburton": "타이리스 핼리버튼",
  "Karl-Anthony Towns": "칼앤서니 타운스",
  "Pascal Siakam": "파스칼 시아캄",
  "Jrue Holiday": "주 할리데이",
  "Bam Adebayo": "뱀 아데바요",
  "Jaylen Brown": "제일런 브라운",
  "Paul George": "폴 조지",
  "Klay Thompson": "클레이 톰슨",
  "James Harden": "제임스 하든",
  "Russell Westbrook": "러셀 웨스트브룩",
  "Chris Paul": "크리스 폴",
  "DeMar DeRozan": "디마 디로잔",

  // ─── MLB — 한국 + 슈퍼스타 ───
  "Shohei Ohtani": "오타니 쇼헤이",
  "Aaron Judge": "에런 저지",
  "Mookie Betts": "무키 베츠",
  "Mike Trout": "마이크 트라웃",
  "Juan Soto": "후안 소토",
  "Ronald Acuña Jr.": "로날드 아쿠냐 주니어",
  "Ronald Acuna Jr.": "로날드 아쿠냐 주니어",
  "Vladimir Guerrero Jr.": "블라디미르 게레로 주니어",
  "Bryce Harper": "브라이스 하퍼",
  "Freddie Freeman": "프레디 프리먼",
  "Yordan Alvarez": "요르단 알바레스",
  "José Ramírez": "호세 라미레스",
  "Jose Ramirez": "호세 라미레스",
  "Fernando Tatis Jr.": "페르난도 타티스 주니어",
  "Manny Machado": "매니 마차도",
  "Gerrit Cole": "게릿 콜",
  "Paul Skenes": "폴 스킨스",
  "Spencer Strider": "스펜서 스트라이더",
  "Tarik Skubal": "타릭 스쿠발",
  "Corbin Burnes": "코빈 번스",
  "Yoshinobu Yamamoto": "야마모토 요시노부",
  "Hyun-Jin Ryu": "류현진",
  "Ji-Man Choi": "최지만",
  "Ha-Seong Kim": "김하성",
  "Hyeseong Kim": "김혜성",
  "Kwang-Hyun Kim": "김광현",
  "Jung Hoo Lee": "이정후",
  // MLB 추가 선발 투수 (2026 시즌 주축)
  "Logan Webb": "로건 웹",
  "Zack Wheeler": "잭 휠러",
  "Cole Ragans": "콜 레이건스",
  "Blake Snell": "블레이크 스넬",
  "Max Fried": "맥스 프리드",
  "Chris Sale": "크리스 세일",
  "Justin Verlander": "저스틴 벌랜더",
  "Max Scherzer": "맥스 슈어저",
  "Sonny Gray": "소니 그레이",
  "Pablo López": "파블로 로페스",
  "Pablo Lopez": "파블로 로페스",
  "Framber Valdez": "프램버 발데스",
  "Kevin Gausman": "케빈 가우스먼",
  "George Kirby": "조지 커비",
  "Logan Gilbert": "로건 길버트",
  "Bryan Woo": "브라이언 우",
  "Hunter Brown": "헌터 브라운",
  "Joe Musgrove": "조 머스그로브",
  "Yu Darvish": "다르빗슈 유",
  "Aaron Nola": "에런 놀라",
  "Walker Buehler": "워커 뷸러",
  "Tyler Glasnow": "타일러 글래스나우",
  "Roki Sasaki": "사사키 로키",
  "Senga Kodai": "센가 코다이",
  "Kodai Senga": "센가 코다이",
  "Shota Imanaga": "이마나가 쇼타",
  "Garrett Crochet": "개럿 크로셰",
  "Bryce Miller": "브라이스 밀러",
  "Reynaldo López": "레이날도 로페스",
  "Reynaldo Lopez": "레이날도 로페스",
  // MLB 추가 타자
  "Bobby Witt Jr.": "바비 위트 주니어",
  "Gunnar Henderson": "거너 헨더슨",
  "Adley Rutschman": "애들리 러치먼",
  "Corbin Carroll": "코빈 캐럴",
  "Elly De La Cruz": "엘리 데라크루스",
  "Julio Rodríguez": "훌리오 로드리게스",
  "Julio Rodriguez": "훌리오 로드리게스",
  "Kyle Tucker": "카일 터커",
  "Rafael Devers": "라파엘 데버스",
  "Trea Turner": "트레이 터너",
  "Marcus Semien": "마커스 세미언",
  "Francisco Lindor": "프란시스코 린도어",
  "Pete Alonso": "피트 알론소",
  "Matt Olson": "맷 올슨",
  "Austin Riley": "오스틴 라일리",
  "Will Smith": "윌 스미스",
  "Teoscar Hernández": "테오스카 에르난데스",
  "Teoscar Hernandez": "테오스카 에르난데스",
  // KBO 외국인 투수 (2024~2026 활약)
  "Raul Alcantara": "라울 알칸타라",
  "Raúl Alcántara": "라울 알칸타라",
  "Wes Benjamin": "웨스 벤자민",
  "Dereck Rodriguez": "데렉 로드리게스",
  "Dereck Rodríguez": "데렉 로드리게스",
  "Erick Fedde": "에릭 페디",
  "Mike Soroka": "마이크 소로카",
  "Eric Lauer": "에릭 라우어",
  "Adrian Sampson": "에이드리언 샘슨",
  "Drew Anderson": "드루 앤더슨",
  "Aaron Brooks": "에런 브룩스",
  "Patrick Wisdom": "패트릭 위즈덤",
  "James Naile": "제임스 네일",
  "Casey Kelly": "케이시 켈리",
  "Hayden Wesneski": "헤이든 웨스네스키",
  "Kyle Hart": "카일 하트",
  "Cody Ponce": "코디 폰스",
  // KBO 한국 투수 (영문 표기 케이스)
  "An Woo-Jin": "안우진",
  "Woo-Jin An": "안우진",
  "Won Tae-In": "원태인",
  "Tae-In Won": "원태인",
  "Kwak Bin": "곽빈",
  "Bin Kwak": "곽빈",
  "Yang Hyeon-Jong": "양현종",
  "Hyeon-Jong Yang": "양현종",
  "Ko Young-Pyo": "고영표",
  "Young-Pyo Ko": "고영표",
  "Eom Sang-Baek": "엄상백",
  "Sang-Baek Eom": "엄상백",
  "Moon Dong-Ju": "문동주",
  "Dong-Ju Moon": "문동주",
  "Na Kyun-An": "나균안",
  "Kyun-An Na": "나균안",

  // ─── 유럽 추가 골잡이 / 슈퍼스타 ───
  "Victor Osimhen": "빅터 오시멘",
  "Romelu Lukaku Menama": "로멜루 루카쿠",
  "Darwin Núñez": "다르윈 누녜스",
  "Darwin Nunez": "다르윈 누녜스",
  "Diogo Jota": "디오구 조타",
  "Mason Mount": "메이슨 마운트",
  "Christopher Nkunku": "크리스토퍼 은쿤쿠",
  "Mateo Kovacic": "마테오 코바치치",
  "Mateo Kovačić": "마테오 코바치치",
  "Goncalo Ramos": "곤살루 하무스",
  "Gonçalo Ramos": "곤살루 하무스",
  "Vitor Roque": "비토르 호키",
  "Vítor Roque": "비토르 호키",
  "Niclas Stark": "니클라스 슈타르크",
  "Florian Neuhaus": "플로리안 노이하우스",
  "Mathys Tel": "마티스 텔",
  "Hakim Ziyech": "하킴 지예시",
  "Ferran Torres": "페란 토레스",
  "Yacine Adli": "야신 아들리",
  "Ronald Araújo": "로날드 아라우호",
  "Ronald Araujo": "로날드 아라우호",
  "Iñigo Martínez": "이니고 마르티네스",
  "Inigo Martinez": "이니고 마르티네스",
  "Jules Koundé": "쥘 쿤데",
  "Jules Kounde": "쥘 쿤데",
  "Mikel Oyarzabal": "미켈 오야르사발",
  "Takefusa Kubo": "쿠보 다케후사",
  "Nico Williams": "니코 윌리암스",
  "Ansu Fati": "안수 파티",

  // ─── NHL 슈퍼스타 ───
  "Connor McDavid": "코너 맥데이비드",
  "Leon Draisaitl": "레온 드라이자이틀",
  "Auston Matthews": "오스턴 매슈스",
  "Nathan MacKinnon": "네이선 매키넌",
  "Sidney Crosby": "시드니 크로즈비",
  "Alexander Ovechkin": "알렉산더 오베치킨",
  "Cale Makar": "케일 마카",
  "Nikita Kucherov": "니키타 쿠체로프",
  "David Pastrnak": "다비드 파스트르냐크",
  "Mitch Marner": "미치 마너",
  "Mikko Rantanen": "미코 란타넨",
  "Igor Shesterkin": "이고르 셰스테르킨",

  // ===== NHL Playoff Goalies (2026) =====
  // 2026 NHL 플레이오프/컨퍼런스 파이널 시점 핵심 골리
  "Carter Hart": "카터 하트",
  "Anthony Stolarz": "앤서니 스톨라즈",
  "Frederik Andersen": "프레데리크 안데르센",
  "Logan Thompson": "로건 톰슨",
  "Adin Hill": "애딘 힐",
  "Joey Daccord": "조이 다코르",
  "Jeremy Swayman": "제레미 스웨이먼",
  "Linus Ullmark": "리누스 울마르크",
  "Sergei Bobrovsky": "세르게이 보브롭스키",
  "Stuart Skinner": "스튜어트 스키너",
  "Scott Wedgewood": "스콧 웨지우드",
  "Connor Hellebuyck": "코너 헬레부이크",
  "Ilya Sorokin": "일리야 소로킨",
  "Juuse Saros": "유세 사로스",
  "Thatcher Demko": "새처 뎀코",

  // ===== MLB Veteran / Sub-stars (2026) =====
  // 기존 등록(Verlander, Sale, Darvish, Kodai Senga, Framber Valdez, Walker Buehler,
  //  Max Fried, Garrett Crochet, George Kirby, Pablo Lopez, Bryce Miller,
  //  Hunter Brown, Bryan Woo, Reynaldo Lopez) 제외하고 추가 등록
  "Sandy Alcantara": "샌디 알칸타라",
  "Jesús Luzardo": "헤수스 루사르도",
  "Jesus Luzardo": "헤수스 루사르도",
  "Tanner Bibee": "태너 비비",
  "Freddy Peralta": "프레디 페랄타",
  "Nick Pivetta": "닉 피베타",
  "Seth Lugo": "세스 루고",
  "Bailey Ober": "베일리 오버",
  "Joe Ryan": "조 라이언",
  "Cristopher Sánchez": "크리스토퍼 산체스",
  "Cristopher Sanchez": "크리스토퍼 산체스",
  "Ranger Suárez": "레인저 수아레스",
  "Ranger Suarez": "레인저 수아레스",
  "Michael King": "마이클 킹",
  "Dylan Cease": "딜런 시즈",
  "Robbie Ray": "로비 레이",
  "Clayton Kershaw": "클레이튼 커쇼",
  "Charlie Morton": "찰리 모턴",
  "Lance Lynn": "랜스 린",
  "Emmanuel Clase": "에마누엘 클라세",
  "Edwin Díaz": "에드윈 디아스",
  "Edwin Diaz": "에드윈 디아스",
  "Devin Williams": "데빈 윌리엄스",
  "Mason Miller": "메이슨 밀러",
  "Josh Hader": "조시 헤이더",
  "Ryan Helsley": "라이언 헬슬리",

  // ===== KBO Korean Players =====
  // 기존 등록(안우진/원태인/곽빈/양현종/고영표/엄상백/문동주/나균안) 위쪽 섹션에 존재
  // 대표 타자
  "Park Geon-Woo": "박건우",
  "Geon-Woo Park": "박건우",
  "Lee Jung-Hoo": "이정후",
  "Jung-Hoo Lee": "이정후",
  "Choi Jeong": "최정",
  "Jeong Choi": "최정",
  "Yang Eui-Ji": "양의지",
  "Eui-Ji Yang": "양의지",
  // 타자 추가
  "Kim Do-Young": "김도영",
  "Do-Young Kim": "김도영",
  "Kim Doyoung": "김도영",
  "Roh Si-Hwan": "노시환",
  "Si-Hwan Roh": "노시환",
  "Park Min-Woo": "박민우",
  "Min-Woo Park": "박민우",
  "Kim Hye-Sung": "김혜성",
  "Hye-Sung Kim": "김혜성",
  "Choi Hyung-Woo": "최형우",
  "Hyung-Woo Choi": "최형우",
  "Park Chan-Ho": "박찬호",
  "Chan-Ho Park": "박찬호",
  "Na Sung-Bum": "나성범",
  "Sung-Bum Na": "나성범",
  "Kim Jae-Hwan": "김재환",
  "Jae-Hwan Kim": "김재환",
  "Hong Chang-Ki": "홍창기",
  "Chang-Ki Hong": "홍창기",
  "Park Hae-Min": "박해민",
  "Hae-Min Park": "박해민",
  "Park Sung-Han": "박성한",
  "Sung-Han Park": "박성한",
  "Hwang Jae-Gyun": "황재균",
  "Jae-Gyun Hwang": "황재균",
  "Han Yu-Seom": "한유섬",
  "Yu-Seom Han": "한유섬",
  "Oh Jae-Il": "오재일",
  "Jae-Il Oh": "오재일",
  "Park Byung-Ho": "박병호",
  "Byung-Ho Park": "박병호",
  "Kang Min-Ho": "강민호",
  "Min-Ho Kang": "강민호",
  "Park Dong-Won": "박동원",
  "Dong-Won Park": "박동원",
  "Park Sok-Min": "박석민",
  "Sok-Min Park": "박석민",
  "Yoon Dong-Hee": "윤동희",
  "Dong-Hee Yoon": "윤동희",
  "Ko Seung-Min": "고승민",
  "Seung-Min Ko": "고승민",
  "Park Seung-Wook": "박승욱",
  "Seung-Wook Park": "박승욱",
  "Choi Won-Joon": "최원준",
  "Won-Joon Choi": "최원준",
  "Ku Ja-Wook": "구자욱",
  "Ja-Wook Ku": "구자욱",
  "Koo Ja-Wook": "구자욱",
  "Lee Jae-Hyun": "이재현",
  "Jae-Hyun Lee": "이재현",
  "Kim Sung-Yoon": "김성윤",
  "Sung-Yoon Kim": "김성윤",
  "Kim Min-Seok": "김민석",
  "Min-Seok Kim": "김민석",
  "Jeon Eui-San": "전의산",
  "Eui-San Jeon": "전의산",
  "Jeong Eui-Yun": "정의윤",
  "Eui-Yun Jeong": "정의윤",
  "Kim Ji-Hwan": "김지환",
  "Ji-Hwan Kim": "김지환",
  // 투수 (보강)
  "Koo Chang-Mo": "구창모",
  "Chang-Mo Koo": "구창모",
  "Im Ki-Young": "임기영",
  "Ki-Young Im": "임기영",
  "Lee Yi-Ri": "이의리",
  "Yi-Ri Lee": "이의리",
  "Park Se-Woong": "박세웅",
  "Se-Woong Park": "박세웅",
  "Lee Yong-Chan": "이용찬",
  "Yong-Chan Lee": "이용찬",
  "Sohn Hwa-Yeon": "손화연",
  "Hwa-Yeon Sohn": "손화연",

  // ===== KBO Foreign Pitchers / Hitters (확신 가능 인물만) =====
  // 2026 시즌 실제 명단을 정확히 알 수 없는 인물은 무리하게 등록하지 않음.
  // 최근(2023~2025) KBO 활약 명단 + 일반적 영문 표기.
  // (Patrick Wisdom / Drew Anderson / Aaron Brooks 등은 위 KBO 외인 섹션에 이미 등록)
  "Adam Plutko": "애덤 플루코",
  "Caleb Smith": "케일럽 스미스",
  "Chad Pinder": "채드 핀더",
  "Mickey Storey": "미키 스토리",
  "Charlie Barnes": "찰리 반스",
  "Wes Parsons": "웨스 파슨스",
  "Yoenis Cespedes": "요에니스 세스페데스",
  "Daniel Mengden": "다니엘 멩든",

  // ===== MLB Season Leaderboard (BA / HR / RBI / ERA / WIN / K) =====
  // /predictions/MLB 시즌 리더보드 영문 노출 fix. 한국 미디어 통용 표기.
  // 이미 위쪽에 등록된 인물 (Imanaga·Sasaki·Lindor·Olson·Riley·Suárez·deGrom·Kershaw·Morton 등) 은 중복 방지로 skip.
  // BA TOP 10 (요르단 알바레스 제외 9명)
  "Otto Lopez": "오토 로페스",
  "Otto López": "오토 로페스",
  "Ildemaro Vargas": "일데마로 바르가스",
  "Shea Langeliers": "셰아 랭글리어스",
  "Brandon Marsh": "브랜던 마시",
  "Riley Greene": "라일리 그린",
  "Nick Gonzales": "닉 곤잘레스",
  "Xavier Edwards": "자비에르 에드워즈",
  "Luis Arraez": "루이스 아라에스",
  "Luis Arráez": "루이스 아라에스",
  "Troy Johnston": "트로이 존스턴",
  // 타자 (HR / RBI 후보)
  "Kyle Schwarber": "카일 슈와버",
  "Vladimir Guerrero": "블라디미르 게레로 주니어",
  "Cal Raleigh": "칼 롤리",
  "Eugenio Suárez": "에우헤니오 수아레스",
  "Eugenio Suarez": "에우헤니오 수아레스",
  "Adolis García": "아돌리스 가르시아",
  "Adolis Garcia": "아돌리스 가르시아",
  "Salvador Perez": "살바도르 페레스",
  "Salvador Pérez": "살바도르 페레스",
  "Marcell Ozuna": "마르셀 오수나",
  "Jose Altuve": "호세 알투베",
  "José Altuve": "호세 알투베",
  "Corey Seager": "코리 시거",
  "Anthony Santander": "앤서니 산탄데르",
  "Brent Rooker": "브렌트 루커",
  "Willy Adames": "윌리 아다메스",
  "Ketel Marte": "케텔 마르테",
  "Christian Walker": "크리스천 워커",
  "Christian Yelich": "크리스천 옐리치",
  "Ronald Acuña": "로날드 아쿠냐 주니어",
  "Ronald Acuna": "로날드 아쿠냐 주니어",
  "Bryan Reynolds": "브라이언 레이놀즈",
  "Ozzie Albies": "오지 알비스",
  "Wyatt Langford": "와이엇 랭포드",
  "Jackson Merrill": "잭슨 메릴",
  "Jackson Holliday": "잭슨 할리데이",
  "James Wood": "제임스 우드",
  // 투수 (ERA / WIN / K 추가)
  "Hunter Greene": "헌터 그린",
  "Carlos Rodón": "카를로스 로돈",
  "Carlos Rodon": "카를로스 로돈",
  "MacKenzie Gore": "매켄지 고어",
  "Christopher Sánchez": "크리스토퍼 산체스",
  "Christopher Sanchez": "크리스토퍼 산체스",

  // ===== Soccer Live Match Goal Scorers / Event Players (2025-26) =====
  // /scores 매치 카드 + /live 매치 페이지 이벤트 타임라인 영문 노출 fix.
  // Serie A
  "Riccardo Orsolini": "리카르도 오르솔리니",
  "Andrea Pinamonti": "안드레아 피나몬티",
  "Walid Cheddira": "왈리드 셰디라",
  "Sebastiano Esposito": "세바스티아노 에스포지토",
  "Yerry Mina": "예리 미나",
  "Rafael Obrador": "라파엘 오브라도르",
  "Armand Laurienté": "아르망 로리앙테",
  "Armand Lauriente": "아르망 로리앙테",
  "Nikola Stulic": "니콜라 스툴리치",
  "Nikola Štulić": "니콜라 스툴리치",
  "Jamie Vardy": "제이미 바디",
  // LaLiga
  "Ademola Lookman": "아데몰라 루크만",
  "Vinicius Jr": "비니시우스 주니오르",
  "Iñaki Williams": "이냐키 윌리엄스",
  "Inaki Williams": "이냐키 윌리엄스",
  "Williot Swedberg": "윌리오트 스웨드베리",
  "Toni Martínez": "토니 마르티네스",
  "Toni Martinez": "토니 마르티네스",
  "Javi Guerra": "하비 게라",
  "Hugo Duro": "우고 두로",
  "Sergio Camello": "세르히오 카메요",
  "Alexandre Alemão": "알렉상드르 알레마우",
  "Alexandre Alemao": "알렉상드르 알레마우",
  "Aihen Muñoz": "아이엔 무뇨스",
  "Aihen Munoz": "아이엔 무뇨스",
  "Orri Óskarsson": "오리 외스카르손",
  "Orri Oskarsson": "오리 외스카르손",
  "César Tárrega": "세사르 타레가",
  "Cesar Tarrega": "세사르 타레가",
  "Guido Rodríguez": "기도 로드리게스",
  "Guido Rodriguez": "기도 로드리게스",
  "Víctor Chust": "빅토르 추스트",
  "Victor Chust": "빅토르 추스트",
  "Víctor Muñoz": "빅토르 무뇨스",
  "Victor Munoz": "빅토르 무뇨스",
  "Carlos Romero": "카를로스 로메로",
  "Enrique García": "엔리케 가르시아",
  "Enrique Garcia": "엔리케 가르시아",
  "Carlos Espí": "카를로스 에스피",
  "Carlos Espi": "카를로스 에스피",
  "Kervin Arriaga": "케르빈 아리아가",
  "Isco": "이스코",
  "João Cancelo": "주앙 칸셀루",
  "Joao Cancelo": "주앙 칸셀루",
  // Ligue 1
  "Alimani Gory": "알리마니 고리",
  "Pierre-Emile Højbjerg": "피에르-에밀 호이비에르",
  "Pierre-Emile Hojbjerg": "피에르-에밀 호이비에르",
  "Amine Gouiri": "아민 구이리",
  "Pierre-Emerick Aubameyang": "피에르-에메릭 오바메양",
  "Aubameyang": "피에르-에메릭 오바메양",
  "Esteban Lepaul": "에스테반 르폴",
  "Wesley Saïd": "웨슬리 사이드",
  "Wesley Said": "웨슬리 사이드",
  "Florian Sotoca": "플로리안 소토카",
  "Florian Thauvin": "플로리안 토뱅",
  "Lassine Sinayoko": "라신 시나요코",
  "Romain Del Castillo": "로맹 델 카스티요",
  "Amine Sbaï": "아민 스바이",
  "Amine Sbai": "아민 스바이",
  "Abdoulaye Faye": "압둘라예 파예",
  "Issa Soumaré": "이사 수마레",
  "Issa Soumare": "이사 수마레",
  "Martial Godo": "마르티알 고도",
  "Ismael Doukoure": "이스마엘 두쿠레",
  "Ismaël Doukouré": "이스마엘 두쿠레",
  "Diego Moreira": "디오구 모레이라",
  "Sebastian Nanasi": "세바스티안 나나시",
  "Lamine Camara": "라민 카마라",
  // MLS
  "Hany Mukhtar": "한 무크타르",
  "Denis Bouanga": "드니 부앙가",
  "Germán Berterame": "헤르만 베르테라메",
  "German Berterame": "헤르만 베르테라메",

  // ===== Serie B (이탈리아 2부) — 2025-26 핵심 선수 =====
  // Palermo
  "Matteo Brunori": "마테오 브루노리",
  "Brunori": "마테오 브루노리",
  "Roberto Insigne": "로베르토 인시녜",
  "Joel Pohjanpalo": "요엘 포흐얀팔로",
  "Pohjanpalo": "요엘 포흐얀팔로",
  "Claudio Gomes": "클라우디오 고메스",
  "Salvatore Sirigu": "살바토레 시리구",
  // Sampdoria
  "Massimo Coda": "마시모 코다",
  "Pedro Pereyra": "페드로 페레이라",
  "Gennaro Tutino": "젠나로 투티노",
  "Tutino": "젠나로 투티노",
  "Emil Audero": "에밀 아우데로",
  // Cremonese
  "Pinamonti": "안드레아 피나몬티",
  "Federico Bonazzoli": "페데리코 보나졸리",
  "Bonazzoli": "페데리코 보나졸리",
  "Franco Vázquez": "프란코 바스케스",
  "Franco Vazquez": "프란코 바스케스",
  // Cesena
  "Cristian Shpendi": "크리스티안 슈펜디",
  "Shpendi": "크리스티안 슈펜디",
  // Modena
  "Gabriele Zappa": "가브리엘레 차파",
  "Antonio Palumbo": "안토니오 팔룸보",
  // Bari
  "Mehdi Dorval": "메흐디 도르발",
  "Nicola Bellomo": "니콜라 벨로모",
  // Brescia
  "Andrea Cistana": "안드레아 치스타나",
  "Dimitri Bisoli": "디미트리 비솔리",
  // Spezia
  "Salvatore Esposito": "살바토레 에스포시토",
  "Pio Esposito": "피오 에스포시토",
  "Francesco Pio Esposito": "프란체스코 피오 에스포시토",
  "Antonio Candela": "안토니오 칸델라",
  // Sudtirol
  "Tommaso Berra": "톰마소 베라",
  "Daniele Casiraghi": "다니엘레 카시라기",
  // Frosinone
  "Marco Brescianini": "마르코 브레시아니니",
  "Matija Šverko": "마티야 슈베르코",
  "Caleb Okoli": "칼렙 오콜리",
  // Salernitana
  "Boulaye Dia": "불라예 디아",
  "Loum Tchaouna": "룸 차우나",
  // Pisa
  "Lorenzo Lucca": "로렌초 루카",
  "Marius Marin": "마리우스 마린",
  "Stefano Moreo": "스테파노 모레오",
  // Reggiana
  "Manuel Marras": "마누엘 마라스",
  "Cedric Gondo": "세드릭 곤도",
  // Carrarese
  "Federico Melegoni": "페데리코 멜레고니",
  // Mantova
  "Alessandro Mancuso": "알레산드로 만쿠소",
  // Juve Stabia
  "Andrea Adorante": "안드레아 아도란테",
  // Catanzaro
  "Pietro Iemmello": "피에트로 옘멜로",
  "Iemmello": "피에트로 옘멜로",
  // Cosenza
  "Tommaso D'Orazio": "톰마소 도라치오",
  // Avellino
  "Gabriele Gori": "가브리엘레 고리",
  // Empoli
  "Lorenzo Colombo": "로렌초 콜롬보",

  // ===== LaLiga 2 (스페인 2부) — 2025-26 핵심 선수 =====
  // Sporting Gijon
  "Juan Otero": "후안 오테로",
  "Gaspar Campos": "가스파르 캄포스",
  "Dubasin": "두바신",
  // Zaragoza
  "Iván Azón": "이반 아손",
  "Ivan Azon": "이반 아손",
  // Real Oviedo
  "Alemão": "알레망",
  "Alemao": "알레망",
  "Aarón Escandell": "아아론 에스칸델",
  // Granada
  "Lucas Boyé": "루카스 보예",
  "Lucas Boye": "루카스 보예",
  "Bryan Zaragoza": "브라이언 사라고사",
  "Famara Diédhiou": "파마라 디에디우",
  "Famara Diedhiou": "파마라 디에디우",
  // Cádiz
  "Christopher Ramos": "크리스토페르 라모스",
  "Brian Ocampo": "브라이언 오캄포",
  // Levante
  "Iván Romero": "이반 로메로",
  "Ivan Romero": "이반 로메로",
  "Carlos Álvarez": "카를로스 알바레스",
  "Carlos Alvarez": "카를로스 알바레스",
  "Roger Brugué": "로제르 브루게",
  "Roger Brugue": "로제르 브루게",
  // Racing Santander
  "Andrés Martín": "안드레스 마르틴",
  "Andres Martin": "안드레스 마르틴",
  "Íñigo Vicente": "이니고 비센테",
  "Inigo Vicente": "이니고 비센테",
  "Juan Carlos Arana": "후안 카를로스 아라나",
  // Mirandes
  "Carlos Martín": "카를로스 마르틴",
  "Hugo Rincón": "우고 린콘",
  // Almería
  "Adrián Embarba": "아드리안 엠바르바",
  "Adrian Embarba": "아드리안 엠바르바",
  "Luis Suárez": "루이스 수아레스",
  "Luis Suarez": "루이스 수아레스",
  "Léo Baptistão": "레오 바프티스탕",
  "Leo Baptistao": "레오 바프티스탕",
  // Burgos
  "Fer Niño": "페르 니뇨",
  "Fer Nino": "페르 니뇨",
  // Cartagena
  "Ortuño": "오르투뇨",
  "Ortuno": "오르투뇨",
  // Eibar
  "Stoichkov": "스토이치코프",
  "Jon Bautista": "욘 바우티스타",
  // Eldense
  "Joan Femenías": "조안 페메니아스",
  // Huesca
  "Enric Gallego": "엔리크 가예고",
  // Albacete
  "Higinio Marín": "이히니오 마린",
  "Higinio Marin": "이히니오 마린",
  // Castellón
  "Mamadou Sylla": "마마두 시야",
  // Córdoba
  "Antonio Casas": "안토니오 카사스",
  // Málaga
  "Dioni Villalba": "디오니 비얄바",
  // Racing Ferrol
  "Jon Karrikaburu": "욘 카리카부루",
  // ─── 쉬페르 리그 (터키 1부) 핵심 선수 2025-26 ───
  // 갈라타사라이
  "Mauro Icardi": "마우로 이카르디",
  "Kerem Aktürkoğlu": "케렘 악튀르코을루",
  "Kerem Akturkoglu": "케렘 악튀르코을루",
  "Yunus Akgün": "유누스 아크균",
  "Yunus Akgun": "유누스 아크균",
  "Lucas Torreira": "루카스 토레이라",
  "Davinson Sánchez": "다빈손 산체스",
  "Davinson Sanchez": "다빈손 산체스",
  "Fernando Muslera": "페르난도 무슬레라",
  "Wilfried Zaha": "윌프리드 자하",
  "Mario Lemina": "마리오 르미나",
  "Sacha Boey": "사샤 부에이",
  "Dries Mertens": "드리스 메르텐스",
  "Sergio Oliveira": "세르지우 올리베이라",
  "Carlos Cuesta": "카를로스 쿠에스타",
  "Michy Batshuayi": "미시 바추아이",
  "Álvaro Morata": "알바로 모라타",
  "Alvaro Morata": "알바로 모라타",
  // 페네르바체
  "Edin Džeko": "에딘 제코",
  "Edin Dzeko": "에딘 제코",
  "Dušan Tadić": "두샨 타디치",
  "Dusan Tadic": "두샨 타디치",
  "Fred": "프레드",
  "Sebastian Szymański": "세바스티안 시만스키",
  "Sebastian Szymanski": "세바스티안 시만스키",
  "Cengiz Ünder": "젱기즈 윈데르",
  "Cengiz Under": "젱기즈 윈데르",
  "Ferdi Kadıoğlu": "페르디 카드오을루",
  "Ferdi Kadioglu": "페르디 카드오을루",
  "İrfan Can Kahveci": "이르판 잔 카흐베지",
  "Irfan Can Kahveci": "이르판 잔 카흐베지",
  "Bright Osayi-Samuel": "브라이트 오사이-새뮤얼",
  "Mert Hakan Yandaş": "메르트 하칸 얀다시",
  "Anatoliy Trubin": "아나톨리 트루빈",
  "Diego Carlos": "지에구 카를루스",
  "Sofyan Amrabat": "소피안 암라바트",
  "Filip Kostić": "필립 코스티치",
  "Filip Kostic": "필립 코스티치",
  "Jhon Durán": "존 두란",
  "Jhon Duran": "존 두란",
  "Youssef En-Nesyri": "유세프 엔네시리",
  "Çağlar Söyüncü": "찰라르 소윤주",
  "Caglar Soyuncu": "찰라르 소윤주",
  // 베식타스
  "Rafa Silva": "하파 시우바",
  "Ciro Immobile": "치로 임모빌레",
  "Gedson Fernandes": "제드송 페르난드스",
  "Vincent Aboubakar": "뱅상 아부바카르",
  "João Mário": "주앙 마리우",
  "Joao Mario": "주앙 마리우",
  "Felix Uduokhai": "펠릭스 우두오카이",
  "Salih Uçan": "살리흐 우잔",
  "Salih Ucan": "살리흐 우잔",
  // 트라브존스포르
  "Anthony Nwakaeme": "앤서니 은와카메",
  "Anthony Denswil": "앤서니 덴스빌",
  "Edin Višća": "에딘 비슈차",
  "Edin Visca": "에딘 비슈차",
  "Paul Onuachu": "폴 오누아추",
  // 기타 쉬페르
  "Hugo Mallo": "우고 마요",
  "Mostafa Mohamed": "모스타파 모하메드",
  "Tiago Çukur": "티아구 추쿠르",
  "Umut Bozok": "우무트 보조크",
  "Younès Belhanda": "유네스 벨한다",
  "Adam Bareiro": "아담 바레이로",
  "Eren Elmalı": "에렌 엘말르",
  "Eren Elmali": "에렌 엘말르",
  "Merih Demiral": "메리흐 데미랄",
  "Zeki Çelik": "제키 첼리크",
  "Zeki Celik": "제키 첼리크",
  "Orkun Kökçü": "오르쿤 쾨크쥐",
  "Orkun Kokcu": "오르쿤 쾨크쥐",
  "Kaan Ayhan": "칸 아이한",
  "Salih Özcan": "살리흐 외즈잔",
  "Salih Ozcan": "살리흐 외즈잔",
  "Yusuf Yazıcı": "유수프 야즈즈",
  "Yusuf Yazici": "유수프 야즈즈",
  "Enes Ünal": "에네스 위날",
  "Enes Unal": "에네스 위날",
  "Hakan Arslan": "하칸 아르슬란",
  "Halil Dervişoğlu": "할릴 데르비쇼을루",
  "Halil Dervisoglu": "할릴 데르비쇼을루",
  "Yusuf Sarı": "유수프 사르",
  "Yusuf Sari": "유수프 사르",

  // ─── 그리스 슈퍼리그 (1부) 핵심 선수 2025-26 ───
  // 올림피아코스
  "Ayoub El Kaabi": "아유브 엘 카비",
  "Konstantinos Tzolakis": "콘스탄티노스 촐라키스",
  "Sotiris Ninis": "소티리스 니니스",
  "Daniel Podence": "다니엘 포덴스",
  "Santiago Hezze": "산티아고 에세",
  "Francisco Ortega": "프란시스코 오르테가",
  "Stefanos Tzimas": "스테파노스 치마스",
  "David Carmo": "다비드 카르무",
  "Chiquinho": "시키뉴",
  "Costinha": "코스칭냐",
  // 파나티나이코스
  "Fotis Ioannidis": "포티스 이오아니디스",
  "Tin Jedvaj": "틴 예드바이",
  "Bart Schenkeveld": "바르트 스헹크벨트",
  "Aitor Cantalapiedra": "아이토르 칸탈라피에드라",
  "Tete": "테테",
  "Filip Đuričić": "필립 주리치치",
  "Filip Djuricic": "필립 주리치치",
  "Pelayo Suárez": "펠라요 수아레스",
  "Adam Gnezda Čerin": "아담 그네즈다 체린",
  // AEK 아테네
  "Sergio Araujo": "세르히오 아라우호",
  "Levi García": "레비 가르시아",
  "Levi Garcia": "레비 가르시아",
  "Petros Mantalos": "페트로스 만탈로스",
  "Dimitrios Moutas": "디미트리오스 무타스",
  "Razvan Marin": "러즈반 마린",
  "Răzvan Marin": "러즈반 마린",
  "Damián Szymański": "다미안 시만스키",
  "Damian Szymanski": "다미안 시만스키",
  // PAOK
  "Andrija Živković": "안드리야 지프코비치",
  "Andrija Zivkovic": "안드리야 지프코비치",
  "Stefan Schwab": "슈테판 슈바프",
  "Taison": "타이송",
  "Brandon Thomas": "브랜던 토마스",
  "Vieirinha": "비에이리냐",
  "Giannis Konstantelias": "야니스 콘스탄텔리아스",
  "Giannis Michailidis": "야니스 미하일리디스",
  "Dominik Kotarski": "도미니크 코타르스키",
  // 기타 그리스
  "Anastasios Bakasetas": "아나스타시오스 바카세타스",
  "Tasos Bakasetas": "타소스 바카세타스",
  "Pantelis Hatzidiakos": "판텔리스 하치디아코스",
  "Manolis Siopis": "마놀리스 시오피스",

  // ─── 주피러 프로 리그 (벨기에 1부) 핵심 선수 2025-26 ───
  // 클럽 브뤼헤
  "Hans Vanaken": "한스 파나컨",
  "Maxim De Cuyper": "막심 더 코이퍼르",
  "Andreas Skov Olsen": "안드레아스 스코우 올센",
  "Ferran Jutglà": "페란 후트글라",
  "Ferran Jutgla": "페란 후트글라",
  "Raphael Onyedika": "라파엘 온예디카",
  "Brandon Mechele": "브란던 메헬러",
  "Bjorn Meijer": "비외른 메이여르",
  "Joel Ordóñez": "호엘 오르도녜스",
  "Joel Ordonez": "호엘 오르도녜스",
  "Hugo Vetlesen": "후고 베틀레센",
  "Christos Tzolis": "크리스토스 촐리스",
  "Romeo Vermant": "로메오 페르만트",
  "Simon Mignolet": "시몽 미뇰레",
  // 위니옹 SG
  "Mohammed Amoura": "모하메드 아무라",
  "Anouar Ait El Hadj": "아누아르 아이트 엘 하지",
  "Cameron Puertas": "카메론 푸에르타스",
  "Anthony Moris": "앙토니 모리스",
  "Christian Burgess": "크리스천 버지스",
  "Ross Sykes": "로스 사이크스",
  "Charles Vanhoutte": "샤를 반후터",
  "Promise David": "프로미스 데이비드",
  // 안더레흐트
  "Kasper Dolberg": "카스페르 돌베리",
  "Mats Rits": "마츠 리츠",
  "Yari Verschaeren": "야리 베르스하렌",
  "Anders Dreyer": "안데르스 드레위에르",
  "Jan Vertonghen": "얀 베르통언",
  "Thorgan Hazard": "토르강 아자르",
  "Théo Leoni": "테오 레오니",
  "Theo Leoni": "테오 레오니",
  "Francis Amuzu": "프란시스 아무주",
  // 헹크
  "Bryan Heynen": "브라이언 헤이넌",
  "Patrik Hrosovsky": "파트리크 흐로숍스키",
  "Bilal El Khannouss": "빌랄 엘 칸누스",
  "Tolu Arokodare": "톨루 아로코다레",
  "Mike Trésor": "마이크 트레소르",
  "Mike Tresor": "마이크 트레소르",
  "Joseph Paintsil": "조지프 페인츨",
  "Maarten Vandevoordt": "마르턴 판더보르트",
  "Konstantinos Karetsas": "콘스탄티노스 카레차스",
  // 스탕다르 리에주
  "Aiden O'Neill": "에이든 오닐",
  "Cihan Canak": "지한 자나크",
  "Steven Alzate": "스티븐 알자테",
  "Bosko Sutalo": "보슈코 슈탈로",
  // 안트베르펀 / 헨트 / 기타
  "Vincent Janssen": "빈센트 얀선",
  "Toby Alderweireld": "토비 알더베이럴트",
  "Arthur Vermeeren": "아르튀르 페르메이런",
  "Tjaronn Chery": "차론 셰리",
  "Hyun-seok Hong": "홍현석",
  "Hong Hyun-seok": "홍현석",
  "Sven Kums": "스벤 쿰스",
  "Matías Fernández-Pardo": "마티아스 페르난데스-파르도",
  "Matias Fernandez-Pardo": "마티아스 페르난데스-파르도",
  "Gift Orban": "기프트 오르반",
  "Tarik Tissoudali": "타리크 티수달리",
  "Marco Kana": "마르코 카나",
  // ============================================================
  // Liga MX (멕시코 1부) — B3 2025-26 핵심 선수
  // ============================================================
  "Henry Martín": "엔리 마르틴",
  "Henry Martin": "엔리 마르틴",
  "Hirving Lozano": "이르빙 로사노",
  "Chucky Lozano": "이르빙 로사노",
  "Edson Álvarez": "에드손 알바레스",
  "Edson Alvarez": "에드손 알바레스",
  "Guillermo Ochoa": "기예르모 오초아",
  "Memo Ochoa": "기예르모 오초아",
  "Diego Lainez": "디에고 라이네스",
  "Carlos Vela": "카를로스 벨라",
  "Javier Hernández": "하비에르 에르난데스",
  "Javier Hernandez": "하비에르 에르난데스",
  "Chicharito": "치차리토",
  "Javier \"Chicharito\" Hernández": "하비에르 치차리토 에르난데스",
  "André-Pierre Gignac": "앙드레-피에르 지냑",
  "Andre-Pierre Gignac": "앙드레-피에르 지냑",
  "Gignac": "앙드레-피에르 지냑",
  "Sebastián Córdova": "세바스티안 코르도바",
  "Sebastian Cordova": "세바스티안 코르도바",
  "Luis Romo": "루이스 로모",
  "Néstor Araujo": "네스토르 아라우호",
  "Nestor Araujo": "네스토르 아라우호",
  "Jonathan dos Santos": "조나탄 두스 산투스",
  "Alan Pulido": "알란 풀리도",
  "César Montes": "세사르 몬테스",
  "Cesar Montes": "세사르 몬테스",
  "Erick Sánchez": "에릭 산체스",
  "Erick Sanchez": "에릭 산체스",
  "Rogelio Funes Mori": "로헬리오 푸네스 모리",
  "Funes Mori": "푸네스 모리",
  "Julián Quiñones": "훌리안 키뇨네스",
  "Julian Quinones": "훌리안 키뇨네스",
  "Diber Cambindo": "디베르 캄빈도",
  "Ángel Sepúlveda": "앙헬 세풀베다",
  "Angel Sepulveda": "앙헬 세풀베다",
  "Salvador Reyes": "살바도르 레예스",
  "Roberto Alvarado": "로베르토 알바라도",
  "Piojo Alvarado": "로베르토 알바라도",
  "Orbelín Pineda": "오르벨린 피네다",
  "Orbelin Pineda": "오르벨린 피네다",
  "Luis Chávez": "루이스 차베스",
  "Luis Chavez": "루이스 차베스",
  "Hector Herrera": "엑토르 에레라",
  "Héctor Herrera": "엑토르 에레라",
  "Andrés Guardado": "안드레스 과르다도",
  "Andres Guardado": "안드레스 과르다도",
  "Jesús Gallardo": "헤수스 가야르도",
  "Jesus Gallardo": "헤수스 가야르도",
  "Jorge Sánchez": "호르헤 산체스",
  "Jorge Sanchez": "호르헤 산체스",
  "Johan Vásquez": "요한 바스케스",
  "Johan Vasquez": "요한 바스케스",
  "Gerardo Arteaga": "헤라르도 아르테아가",
  "Israel Reyes": "이스라엘 레예스",
  "Kevin Álvarez": "케빈 알바레스",
  "Kevin Alvarez": "케빈 알바레스",
  "Uriel Antuna": "우리엘 안투나",
  "Diego Valdés": "디에고 발데스",
  "Diego Valdes": "디에고 발데스",
  "Rodrigo Aguirre": "로드리고 아기레",
  "Brian Rodríguez": "브라이언 로드리게스",
  "Brian Rodriguez": "브라이언 로드리게스",
  "Igor Lichnovsky": "이고르 리흐노프스키",
  "Sebastián Cáceres": "세바스티안 카세레스",
  "Sebastian Caceres": "세바스티안 카세레스",
  "Charly Rodríguez": "찰리 로드리게스",
  "Charly Rodriguez": "찰리 로드리게스",
  "Maxi Meza": "막시 메사",
  "Maximiliano Meza": "막시밀리아노 메사",
  "Sergio Canales": "세르히오 카날레스",
  "Lucas Ocampos": "루카스 오캄포스",
  "Paulinho": "파울리뉴",
  "Alexis Vega": "알렉시스 베가",
  "Fernando Beltrán": "페르난도 벨트란",
  "Fernando Beltran": "페르난도 벨트란",
  "Antuna": "우리엘 안투나",
  "Raúl Rangel": "라울 랑헬",
  "Raul Rangel": "라울 랑헬",
  "Luis García": "루이스 가르시아",
  "Nicolás Castillo": "니콜라스 카스티요",
  "Nicolas Castillo": "니콜라스 카스티요",
  "Salomón Rondón": "살로몬 론돈",
  "Salomon Rondon": "살로몬 론돈",
  "Oussama Idrissi": "우사마 이드리시",
  "Marcel Ruiz": "마르셀 루이스",
  "Juan Brunetta": "후안 브루네타",
  "Allan Saint-Maximin": "알랑 생-막시맹",
  "James Rodríguez": "하메스 로드리게스",
  "James Rodriguez": "하메스 로드리게스",
  "Anthony Martial": "앙토니 마르시알",
  "Sergio Ramos": "세르히오 라모스",

  // ============================================================
  // 잉글랜드 챔피언십 (2025-26) — B3 핵심 선수
  // ============================================================
  // Leeds United
  "Daniel James": "대니얼 제임스",
  "Dan James": "대니얼 제임스",
  "Joël Piroe": "요엘 피로",
  "Joel Piroe": "요엘 피로",
  "Patrick Bamford": "패트릭 뱀포드",
  "Crysencio Summerville": "크리센시오 서머빌",
  "Georginio Rutter": "조르지뉴 뤼테르",
  "Wilfried Gnonto": "윌프리드 뇽토",
  "Willy Gnonto": "윌프리드 뇽토",
  "Brenden Aaronson": "브렌든 아론슨",
  "Ethan Ampadu": "이단 암파두",
  "Pascal Struijk": "파스칼 스트라위크",
  "Ilia Gruev": "일리아 그루에프",
  "Illan Meslier": "일랑 멜리에",
  "Junior Firpo": "주니오르 피르포",
  "Mateo Joseph": "마테오 호세프",
  "Largie Ramazani": "라르히 라마자니",
  "Ao Tanaka": "타나카 아오",
  "Manor Solomon": "마노르 솔로몬",
  // Burnley
  "Lyle Foster": "라일 포스터",
  "Jay Rodriguez": "제이 로드리게스",
  "Josh Cullen": "조시 컬런",
  "Josh Brownhill": "조시 브라운힐",
  "Anass Zaroury": "아나스 자루리",
  "Manuel Benson": "마누엘 벤슨",
  "Dara O'Shea": "다라 오셰이",
  "James Trafford": "제임스 트래퍼드",
  "Sander Berge": "산데르 베르게",
  "Zeki Amdouni": "제키 암두니",
  // Sheffield United
  "Oliver McBurnie": "올리버 맥버니",
  "Oli McBurnie": "올리버 맥버니",
  "Gustavo Hamer": "구스타부 하메르",
  "Anel Ahmedhodžić": "아넬 아흐메드호지치",
  "Anel Ahmedhodzic": "아넬 아흐메드호지치",
  "Tyrese Campbell": "타이리스 캠벨",
  "Vinícius Souza": "비니시우스 소우자",
  "Vinicius Souza": "비니시우스 소우자",
  // Norwich City
  "Josh Sargent": "조시 사전트",
  "Borja Sainz": "보르하 사인스",
  "Gabriel Sara": "가브리엘 사라",
  "Jonathan Rowe": "조나단 로",
  "Ashley Barnes": "애슐리 반스",
  "Christian Fassnacht": "크리스티안 파스나흐트",
  // Watford
  "Imrân Louza": "임란 루자",
  "Imran Louza": "임란 루자",
  "Tom Cleverley": "톰 클레벌리",
  "Vakoun Bayo": "바쿤 바요",
  "Edo Kayembe": "에도 카옘베",
  // Middlesbrough
  "Emmanuel Latte Lath": "에마뉘엘 라테 라트",
  "Hayden Hackney": "헤이든 해크니",
  "Riley McGree": "라일리 맥그리",
  "Isaiah Jones": "이사야 존스",
  "Sam Greenwood": "샘 그린우드",
  // West Brom
  "Karlan Grant": "칼란 그랜트",
  "Brandon Thomas-Asante": "브랜든 토머스-아산테",
  "John Swift": "존 스위프트",
  "Jed Wallace": "제드 월리스",
  "Alex Mowatt": "알렉스 모와트",
  // Hull City
  "Liam Delap": "리암 딜랩",
  "Jaden Philogene": "제이든 필로진",
  "Jean Michaël Seri": "장 미카엘 세리",
  "Jean Michael Seri": "장 미카엘 세리",
  "Ozan Tufan": "오잔 투판",
  // Coventry City
  "Haji Wright": "하지 라이트",
  "Ellis Simms": "엘리스 심스",
  "Callum O'Hare": "캘럼 오헤어",
  "Tatsuhiro Sakamoto": "사카모토 다쓰히로",
  // Cardiff City
  "Aaron Ramsey": "에런 램지",
  "Karlan Grant CFC": "칼란 그랜트",
  "Yakou Méïté": "야쿠 메이테",
  "Yakou Meite": "야쿠 메이테",
  // Swansea City
  "Liam Cullen": "리암 컬런",
  "Jerry Yates": "제리 예이츠",
  "Joe Allen": "조 앨런",
  "Matt Grimes": "맷 그라임스",
  // Sunderland
  "Jack Clarke": "잭 클라크",
  "Patrick Roberts": "패트릭 로버츠",
  "Dan Neil": "댄 닐",
  "Dan Ballard": "댄 발라드",
  "Anthony Patterson": "앤서니 패터슨",
  "Eliezer Mayenda": "엘리에세르 마옌다",
  // Preston North End
  "Emil Riis": "에밀 리스",
  "Will Keane": "윌 킨",
  "Milutin Osmajic": "밀루틴 오스마이치",
  // Bristol City
  "Anis Mehmeti": "아니스 메흐메티",
  "Tommy Conway": "토미 콘웨이",
  "Nahki Wells": "나키 웰스",
  "Jason Knight": "제이슨 나이트",
  // Millwall
  "Zian Flemming": "지안 플레밍",
  "Tom Bradshaw": "톰 브래드쇼",
  "Duncan Watmore": "덩컨 왓모어",
  // QPR
  "Lyndon Dykes": "린든 다익스",
  "Ilias Chair": "일리아스 셰르",
  "Chris Willock": "크리스 윌록",
  // Blackburn Rovers
  "Sammie Szmodics": "새미 슈모딕스",
  "Tyrhys Dolan": "타이리스 돌란",
  "Andi Weimann": "안디 바이만",
  // Plymouth Argyle
  "Morgan Whittaker": "모건 휘태커",
  "Ryan Hardie": "라이언 하디",
  "Adam Randell": "애덤 랜덜",
  // Portsmouth
  "Colby Bishop": "콜비 비숍",
  "Marlon Pack": "말런 팩",
  "Conor Shaughnessy": "코너 쇼네시",
  // Stoke City
  "Tyrese Campbell SCFC": "타이리스 캠벨",
  "Andre Vidigal": "안드레 비디갈",
  "Wouter Burger": "바우터 뷔르거",
  "Bae Junho": "배준호",
  // Birmingham City
  "Jay Stansfield": "제이 스탠스필드",
  "Lukas Jutkiewicz": "루카스 유트키비치",
  "Juninho Bacuna": "주니뉴 바쿠나",
  "Krystian Bielik": "크리스티안 비엘리크",
  // Derby County
  "James Collins": "제임스 콜린스",
  "Conor Hourihane": "코너 후리한",
  // Oxford United
  "Mark Harris": "마크 해리스",
  "Cameron Brannagan": "캐머런 브래너건",
  // Luton Town
  "Carlton Morris": "칼튼 모리스",
  "Elijah Adebayo": "엘리야 아데바요",
  "Ross Barkley": "로스 바클리",
  "Alfie Doughty": "앨피 도티",
  "Jordan Clark": "조던 클라크",
  // Sheffield Wednesday
  "Lee Gregory": "리 그레고리",
  "Anthony Musaba": "앤서니 무사바",
  "Djeidi Gassama": "제이디 가사마",

  // ===== 에레디비시 2025-26 =====
  // PSV Eindhoven
  "Luuk de Jong": "뤽 더 용",
  "Ricardo Pepi": "리카르도 페피",
  "Ivan Perišić": "이반 페리시치",
  "Ivan Perisic": "이반 페리시치",
  "Joey Veerman": "조이 페르만",
  "Malik Tillman": "말리크 틸만",
  "Noa Lang": "노아 랑",
  "Walter Benítez": "발테르 베니테스",
  "Walter Benitez": "발테르 베니테스",
  "Olivier Boscagli": "올리비에 보스칼리",
  "André Ramalho": "안드레 라말류",
  "Andre Ramalho": "안드레 라말류",
  "Johan Bakayoko": "요한 바카요코",
  "Sergiño Dest": "세르지뇨 데스트",
  "Sergino Dest": "세르지뇨 데스트",
  "Jerdy Schouten": "예르디 스하우턴",
  "Guus Til": "휘스 틸",
  "Ismael Saibari": "이스마엘 사이바리",
  // Ajax
  "Davy Klaassen": "다비 클라선",
  "Steven Berghuis": "스테번 베르후이스",
  "Brian Brobbey": "브라이언 브로베이",
  "Bertrand Traoré": "베르트랑 트라오레",
  "Bertrand Traore": "베르트랑 트라오레",
  "Jordan Henderson": "조던 헨더슨",
  "Kenneth Taylor": "케네스 테일러",
  "Devyne Rensch": "데빈 렌스",
  "Mika Godts": "미카 호츠",
  "Branco van den Boomen": "브랑코 판 덴 부먼",
  "Anton Gaaei": "안톤 가에이",
  "Josip Šutalo": "요시프 슈탈로",
  "Josip Sutalo": "요시프 슈탈로",
  "Remko Pasveer": "렘코 파스페이르",
  "Chuba Akpom": "추바 악폼",
  // Feyenoord
  "Igor Paixão": "이고르 파이샹",
  "Igor Paixao": "이고르 파이샹",
  "Quinten Timber": "퀸텐 팀버",
  "Mats Wieffer": "마츠 비퍼",
  "Calvin Stengs": "칼빈 스텡스",
  "Luka Ivanušec": "루카 이바누셰츠",
  "Luka Ivanusec": "루카 이바누셰츠",
  "Ayase Ueda": "우에다 아야세",
  "David Hancko": "다비드 한츠코",
  "Lutsharel Geertruida": "루차렐 헤이르트라위다",
  "Justin Bijlow": "유스틴 베일로우",
  "Timon Wellenreuther": "티몬 벨렌로이터",
  // AZ Alkmaar
  "Vangelis Pavlidis": "반겔리스 파블리디스",
  "Sven Mijnans": "스벤 메이난스",
  "Jordy Clasie": "요르디 클라시",
  "Ruben van Bommel": "뤼번 판 보멀",
  "Mayckel Lahdo": "마이켈 라도",
  "Bruno Martins Indi": "브루누 마르팅스 인디",
  "Mathew Ryan": "매슈 라이언",
  // FC Twente / NEC / Heerenveen / Utrecht 등
  "Sem Steijn": "셈 스테인",
  "Ricky van Wolfswinkel": "리키 판 볼프스빙컬",
  "Tobias Lauritsen": "토비아스 라우리트센",
  "Anastasios Douvikas": "아나스타시오스 두비카스",
  "Sam Lammers": "샘 라머스",
  "Daan Rots": "단 로츠",
  "Lars Unnerstall": "라르스 우너슈탈",
  "Bart van Rooij": "바르트 판 로이",

  // ===== 프리메이라 리가 2025-26 =====
  // Sporting CP
  "Pedro Gonçalves": "페드루 곤살베스",
  "Pedro Goncalves": "페드루 곤살베스",
  "Geny Catamo": "게니 카타무",
  "Hidemasa Morita": "모리타 히데마사",
  "Morten Hjulmand": "모르텐 율만",
  "Ousmane Diomande": "우스만 디오만드",
  "Gonçalo Inácio": "곤살루 이나시우",
  "Goncalo Inacio": "곤살루 이나시우",
  "Marcus Edwards": "마커스 에드워즈",
  "Nuno Santos": "누누 산투스",
  "Franco Israel": "프랑코 이스라엘",
  "Conrad Harder": "콘라드 하르더",
  "Maximiliano Araújo": "막시밀리아노 아라우호",
  "Maximiliano Araujo": "막시밀리아노 아라우호",
  "Eduardo Quaresma": "에두아르두 카레스마",
  "Daniel Bragança": "다니엘 브라간사",
  "Daniel Braganca": "다니엘 브라간사",
  // Benfica
  "Ángel Di María": "앙헬 디 마리아",
  "Angel Di Maria": "앙헬 디 마리아",
  "Florentino Luís": "플로렌치누 루이스",
  "Florentino Luis": "플로렌치누 루이스",
  "António Silva": "안토니우 시우바",
  "Antonio Silva": "안토니우 시우바",
  "Tomás Araújo": "토마스 아라우주",
  "Tomas Araujo": "토마스 아라우주",
  "Nicolás Otamendi": "니콜라스 오타멘디",
  "Nicolas Otamendi": "니콜라스 오타멘디",
  "Alexander Bah": "알렉산데르 바",
  "Fredrik Aursnes": "프레드리크 아우르스네스",
  "António Silva Centurion": "안토니우 시우바 센투리온",
  "Andreas Schjelderup": "안드레아스 셸데루프",
  "Arthur Cabral": "아르투르 카브랄",
  // FC Porto
  "Samu Aghehowa": "사무 아게오와",
  "Galeno": "갈레누",
  "Stephen Eustáquio": "스티븐 에우스타키오",
  "Stephen Eustaquio": "스티븐 에우스타키오",
  "Pepê": "페페",
  "Diogo Costa": "디오구 코스타",
  "Wendell": "벤델",
  "Iván Marcano": "이반 마르카노",
  "Ivan Marcano": "이반 마르카노",
  "Alan Varela": "알란 바렐라",
  "Nico González": "니코 곤살레스",
  "Nico Gonzalez": "니코 곤살레스",
  "Francisco Conceição": "프란시스쿠 콘세이상",
  "Francisco Conceicao": "프란시스쿠 콘세이상",
  "Fábio Vieira": "파비우 비에이라",
  "Fabio Vieira": "파비우 비에이라",
  "Zaidu Sanusi": "자이두 사누시",
  // SC Braga
  "Ricardo Horta": "히카르두 오르타",
  "Bruma": "브루마",
  "Sikou Niakaté": "시쿠 니아카테",
  "Sikou Niakate": "시쿠 니아카테",
  "Vítor Carvalho": "비토르 카르발류",
  "Vitor Carvalho": "비토르 카르발류",
  "André Horta": "안드레 오르타",
  "Andre Horta": "안드레 오르타",
  "Roger Fernandes": "호제르 페르난데스",
  "Niakaté": "니아카테",
  // Vitória SC / Moreirense / Casa Pia / Famalicão / Estoril / Boavista 등
  "André Silva": "안드레 실바",
  "Andre Silva": "안드레 실바",
  "Tiago Silva": "티아구 실바",
  "Jota Silva": "조타 실바",
  "Cassiano": "카시아누",
  "Franculino Djú": "프랑쿨리누 주",
  "Franculino Dju": "프랑쿨리누 주",
  "Clayton Silva": "클레이튼 실바",
  "Heriberto Tavares": "에리베르투 타바레스",
  // ===== AFC CL Two 2025-26 =====
  // 동남아·인도·중앙아시아 핵심. 확신 가능 인물만.
  // ─── 태국 국가대표·BG 빠툼·부리람 ───
  "Theerathon Bunmathan": "티라톤 분마탄",
  "T. Bunmathan": "티라톤 분마탄",
  "Chanathip Songkrasin": "차나티프 송끄라신",
  "C. Songkrasin": "차나티프 송끄라신",
  "Supachok Sarachat": "수파촉 사라찻",
  "S. Sarachat": "수파촉 사라찻",
  "Suphanat Mueanta": "수파낫 무엔타",
  "S. Mueanta": "수파낫 무엔타",
  "Sarach Yooyen": "사랏 유옌",
  // ─── 인도 국가대표·ISL ───
  "Sunil Chhetri": "수닐 체트리",
  "S. Chhetri": "수닐 체트리",
  "Sandesh Jhingan": "산데시 진간",
  "S. Jhingan": "산데시 진간",
  "Gurpreet Singh Sandhu": "구르프리트 싱 산두",
  "Anirudh Thapa": "아니루드 타파",
  "Manvir Singh": "만비르 싱",
  "Sahal Abdul Samad": "사할 압둘 사마드",
  // ─── 인도네시아 ───
  "Marselino Ferdinan": "마르셀리노 페르디난",
  "M. Ferdinan": "마르셀리노 페르디난",
  "Pratama Arhan": "프라타마 아르한",
  "P. Arhan": "프라타마 아르한",
  "Egy Maulana Vikri": "에기 마울라나 비크리",
  // ─── 베트남 ───
  "Nguyễn Quang Hải": "응우옌 꽝 하이",
  "Nguyen Quang Hai": "응우옌 꽝 하이",
  "Quang Hai": "응우옌 꽝 하이",
  // ─── 우즈베키스탄 (파흐타코르·나사프) ───
  "Eldor Shomurodov": "엘도르 쇼무로도프",
  "E. Shomurodov": "엘도르 쇼무로도프",
  "Abbosbek Fayzullaev": "아보스벡 파이줄라예프",
  // ─── 사우디·ACL Two ───
  // (Al-Hilal·Al-Nassr 핵심은 기존 매핑 다수 — Cristiano Ronaldo·Neymar 등)
  // 추가 ACL Two 무대 인물:
  "Salem Al-Dawsari": "살렘 알다우사리",
  "Salem Al Dawsari": "살렘 알다우사리",
  "S. Al-Dawsari": "살렘 알다우사리",

  // ===== AFC U23 아시안컵 =====
  // 한국 U-23 — 본 대회 출전 가능성 + 확신 가능한 인물만.
  "Lee Young-jun": "이영준",
  "Lee Youngjun": "이영준",
  "Y. Lee (U23)": "이영준",
  "Jung Sang-bin": "정상빈",
  "Jung Sangbin": "정상빈",
  "Sang-bin Jung": "정상빈",
  "Hong Yun-sang": "홍윤상",
  "Hong Yunsang": "홍윤상",
  "Yun-sang Hong": "홍윤상",
  "Kang Sung-jin": "강성진",
  "Kang Sungjin": "강성진",
  "Sung-jin Kang": "강성진",
  "Eom Ji-sung": "엄지성",
  "Eom Jisung": "엄지성",
  "Ji-sung Eom": "엄지성",
  "Lee Han-beom": "이한범",
  "Lee Hanbeom": "이한범",
  "Han-beom Lee": "이한범",

  // ===== 코파 리베르타도레스 / 수다메리카나 =====
  // 브라질 세히 A 선수는 기존 매핑 다수 (Vinícius Jr·Rodrygo 는 별개 — 유럽).
  // 아르헨티나·우루과이·콜롬비아·칠레·에콰도르 핵심.
  // ─── 아르헨티나 ───
  "Miguel Borja": "미겔 보르하",
  "M. Borja": "미겔 보르하",
  "Sebastián Driussi": "세바스티안 드리우시",
  "Sebastian Driussi": "세바스티안 드리우시",
  "S. Driussi": "세바스티안 드리우시",
  "Maximiliano Salas": "막시밀리아노 살라스",
  // (Adam Bareiro 는 기존 매핑)
  "Cristian Medina": "크리스티안 메디나",
  "Equi Fernández": "에키 페르난데스",
  "Equi Fernandez": "에키 페르난데스",
  "Edinson Cavani": "에딘손 카바니",
  "E. Cavani": "에딘손 카바니",
  "Carlos Tevez": "카를로스 테베스",
  "Carlos Tévez": "카를로스 테베스",
  "Marcos Rojo": "마르코스 로호",
  "M. Rojo": "마르코스 로호",
  "Leandro Paredes": "레안드로 파레데스",
  "L. Paredes": "레안드로 파레데스",
  "Nahuel Molina": "나우엘 몰리나",
  // (Cristian Romero 는 기존 매핑)
  "C. Romero": "크리스티안 로메로",
  // ─── 우루과이 ───
  "Luis Suárez (Uruguay)": "루이스 수아레스",
  "Maxi Gómez": "막시 고메스",
  "Maxi Gomez": "막시 고메스",
  "M. Gómez": "막시 고메스",
  "Diego Forlán": "디에고 포를란",
  "Diego Forlan": "디에고 포를란",
  "D. Forlán": "디에고 포를란",
  "Sebastián Coates": "세바스티안 코아테스",
  "Sebastian Coates": "세바스티안 코아테스",
  "Nahitan Nández": "나이탄 난데스",
  "Nahitan Nandez": "나이탄 난데스",
  "Diego Godín": "디에고 고딘",
  "Diego Godin": "디에고 고딘",
  "Rodrigo Bentancur": "로드리고 벤탕쿠르",
  "R. Bentancur": "로드리고 벤탕쿠르",
  // (Darwin Núñez/Nunez 는 기존 매핑)
  // ─── 콜롬비아 ───
  "Radamel Falcao": "라다멜 팔카오",
  "R. Falcao": "라다멜 팔카오",
  "Falcao García": "라다멜 팔카오",
  "Juan Cuadrado": "후안 쿠아드라도",
  "J. Cuadrado": "후안 쿠아드라도",
  "Diego Valoyes": "디에고 발로예스",
  "D. Valoyes": "디에고 발로예스",
  "Jhon Arias": "존 아리아스",
  "Jhon Córdoba": "존 코르도바",
  "Jhon Cordoba": "존 코르도바",
  "David Ospina": "다비드 오스피나",
  "D. Ospina": "다비드 오스피나",
  "Wilmar Barrios": "윌마르 바리오스",
  "Mateus Uribe": "마테우스 우리베",
  "Luis Fernando Muriel": "루이스 무리엘",
  "Luis Muriel": "루이스 무리엘",
  // ─── 칠레 ───
  "Arturo Vidal": "아르투로 비달",
  "A. Vidal": "아르투로 비달",
  "Alexis Sánchez": "알렉시스 산체스",
  "Alexis Sanchez": "알렉시스 산체스",
  "A. Sánchez": "알렉시스 산체스",
  "Claudio Bravo": "클라우디오 브라보",
  "C. Bravo": "클라우디오 브라보",
  "Gary Medel": "게리 메델",
  "G. Medel": "게리 메델",
  "Eduardo Vargas": "에두아르도 바르가스",
  "E. Vargas": "에두아르도 바르가스",
  // ─── 파라과이 ───
  "Antonio Sanabria": "안토니오 사나브리아",
  "A. Sanabria": "안토니오 사나브리아",
  "Miguel Almirón": "미겔 알미론",
  "Miguel Almiron": "미겔 알미론",
  "M. Almirón": "미겔 알미론",
  // ─── 페루 ───
  "Paolo Guerrero": "파올로 게레로",
  "P. Guerrero": "파올로 게레로",
  "Gianluca Lapadula": "잔루카 라파둘라",
  // ─── 에콰도르 ───
  "Enner Valencia": "에네르 발렌시아",
  "E. Valencia": "에네르 발렌시아",
  // (Moisés/Moises Caicedo 는 기존 매핑)
  // ─── 브라질 (코파 무대 핵심·기존 매핑 없는 인물) ───
  "Hulk": "훌크",
  "Hulk Paraíba": "훌크",
  "Jonathan Calleri": "조나탄 카예리",
  "J. Calleri": "조나탄 카예리",
  "Pedro Raul": "페드루 하울",
  "Pedro Raúl": "페드루 하울",
  // ═══════════════════════════════════════════════════════════════
  // ▼▼▼ C3 — 스코틀랜드 SPL + CSL + A-리그 선수 한글화 (2025-26)
  // ═══════════════════════════════════════════════════════════════

  // ─── 스코틀랜드 프리미어십 (SPL) ───
  // Celtic
  "Kyogo Furuhashi": "후루하시 쿄고",
  "Daizen Maeda": "마에다 다이젠",
  "Adam Idah": "아담 이다",
  "Reo Hatate": "하타테 레오",
  "Matt O'Riley": "매트 오라일리",
  "Callum McGregor": "캘럼 맥그리거",
  "Cameron Carter-Vickers": "캐머런 카터-비커스",
  "Greg Taylor": "그렉 테일러",
  "Anthony Ralston": "앤서니 랠스턴",
  "Liam Scales": "리암 스케일스",
  "Nicolas Kühn": "니콜라스 퀸",
  "Nicolas Kuhn": "니콜라스 퀸",
  "Arne Engels": "아르네 엥엘스",
  "Paulo Bernardo": "파울로 베르나르도",
  // Rangers
  "James Tavernier": "제임스 태버니어",
  "Cyriel Dessers": "시리엘 데서스",
  "Mohamed Diomande": "모하메드 디오만드",
  "Ridvan Yilmaz": "리드반 일마즈",
  "Ridvan Yılmaz": "리드반 일마즈",
  "John Souttar": "존 수타르",
  "Nicolas Raskin": "니콜라스 라스킨",
  "Tom Lawrence": "톰 로런스",
  "Vaclav Cerny": "바츨라프 체르니",
  "Václav Černý": "바츨라프 체르니",
  "Hamza Igamane": "함자 이가마네",
  // Hearts
  "Lawrence Shankland": "로런스 섕클런드",
  "Cammy Devlin": "캐미 데블린",
  "Craig Halkett": "크레이그 핼킷",
  "Frankie Kent": "프랭키 켄트",
  // Hibernian
  "Martin Boyle": "마틴 보일",
  "Mykola Kukharevych": "미콜라 쿠하레비치",
  "Joe Newell": "조 뉴얼",
  // Aberdeen
  "Bojan Miovski": "보얀 미오프스키",
  "Graeme Shinnie": "그레임 시니",
  "Leighton Clarkson": "레이턴 클락슨",
  "Jamie McGrath": "제이미 맥그래스",
  // Dundee / Dundee Utd / Motherwell / Kilmarnock
  "Lyall Cameron": "라이얼 캐머런",
  "Sam Dalby": "샘 댈비",
  "Louis Moult": "루이스 몰트",
  "Theo Bair": "테오 베어",

  // ─── 중국 슈퍼리그 (CSL) ───
  // 외국인 스타
  "Marko Arnautović": "마르코 아르나우토비치",
  "Marko Arnautovic": "마르코 아르나우토비치",
  "Anthony Modeste": "앙토니 모데스트",
  "Lukas Podolski": "루카스 포돌스키",
  "Stefan Mugoša": "스테판 무고샤",
  "Stefan Mugosa": "스테판 무고샤",
  "Oscar dos Santos Emboaba Júnior": "오스카르",
  "Oscar Emboaba": "오스카르",
  "Aaron Mooy": "애런 무이",
  "Marouane Fellaini": "마루안 펠라이니",
  "Cedric Bakambu": "세드리크 바캄부",
  "Cédric Bakambu": "세드리크 바캄부",
  "Alex Teixeira": "알렉스 테이셰이라",
  // 중국 핵심
  "Wu Lei": "우레이",
  "Wei Shihao": "웨이 스하오",
  "Zhang Yuning": "장 위닝",
  "Wu Xinghan": "우 싱한",
  "Wang Shangyuan": "왕 상위안",
  "Zhang Linpeng": "장 린펑",
  "Zhu Chenjie": "주 천제",
  "Wang Dalei": "왕 다레이",
  "Yan Junling": "옌 쥔링",
  "Tao Qianglong": "타오 창룽",
  "Gao Tianyi": "가오 톈이",
  "Xie Pengfei": "셰 펑페이",
  "Han Pengfei": "한 펑페이",
  "Fang Hao": "팡 하오",

  // ─── 호주 A-리그 ───
  "Bruno Fornaroli": "브루노 포르나롤리",
  "Jamie Maclaren": "제이미 매클라런",
  "Adam Le Fondre": "애덤 르 폰드르",
  "Connor Metcalfe": "코너 메트칼프",
  "Tomi Juric": "토미 유리치",
  "Tolgay Arslan": "톨가이 아르슬란",
  "Juande": "후안데",
  "Aleksandar Susnjar": "알렉산다르 슈슈냐르",
  "Alessandro Diamanti": "알레산드로 디아만티",
  "Aleksandar Mitrović": "알렉산다르 미트로비치",
  "Mathew Leckie": "매슈 레키",
  "Mat Leckie": "매슈 레키",
  "Andrew Nabbout": "앤드루 내봇",
  "Rhyan Grant": "라이언 그랜트",
  "Joe Lolley": "조 롤리",
  "Bobô": "보보",
  "Bobo": "보보",
  "Apostolos Stamatelopoulos": "아포스톨로스 스타마텔로풀로스",
  "Bernie Ibini": "버니 이비니",
  "Steven Ugarkovic": "스티븐 우가르코비치",
  "Anthony Caceres": "앤서니 카세레스",
  "Marco Tilio": "마르코 틸리오",
  "Daniel Arzani": "대니얼 아르자니",
  "Awer Mabil": "아워 마빌",
  "Mitch Duke": "미치 듀크",
  "Brandon Borrello": "브랜던 보렐로",

  // ===== /predictions 리더보드 누락 (2026-05-19) =====
  // NHL 리더보드
  "Matt Boldy": "매트 볼디",
  "Brett Howden": "브렛 하우든",
  "Pavel Dorofeyev": "파벨 도로페예프",
  "Logan Stankoven": "로건 스탠코븐",
  "Brandon Hagel": "브랜든 헤이글",
  "Alex Newhook": "알렉스 뉴훅",
  "Jason Robertson": "제이슨 로버트슨",
  "Beckett Sennecke": "베킷 세네크",

  // EPL 리더보드
  "Thiago": "치아구",
  "Dominic Calvert-Lewin": "도미닉 칼버트-루윈",
  "D. Calvert-Lewin": "도미닉 칼버트-루윈",
  "Danny Welbeck": "대니 웰벡",
  "D. Welbeck": "대니 웰벡",
  "Evan Kroupi": "에브안 크루피",
  "E. Kroupi": "에브안 크루피",

  // LALIGA 리더보드
  "Vedat Muriqi": "베다트 무리치",
  "V. Muriqi": "베다트 무리치",
  "Ante Budimir": "안테 부디미르",
  "A. Budimir": "안테 부디미르",
  "Borja Iglesias": "보르하 이글레시아스",
  "Alexander Sørloth": "알렉산데르 쇠를로트",
  "A. Sørloth": "알렉산데르 쇠를로트",
  "Alexander Sorloth": "알렉산데르 쇠를로트",

  // UCL 리더보드 (Julián Álvarez/Luis Díaz 풀명은 상단에 이미 존재, alias 만 추가)
  "J. Álvarez": "훌리안 알바레스",
  "L. Díaz": "루이스 디아스",
  "Jens Petter Hauge": "옌스 페테르 하우게",
  "J. Hauge": "옌스 페테르 하우게",

  // NPB Romaji
  "Kaito Muramatsu": "무라마쓰 카이토",
  "Muku Ota": "오타 무쿠",

  // ===== MLB 선발투수 26명 (2026-05-20 /scores 발견 누락) =====
  "Aaron Civale": "에런 시발레",
  "Ben Brown": "벤 브라운",
  "Braxton Garrett": "브랙스턴 개럿",
  "Chase Burns": "체이스 번스",
  "Emerson Hancock": "에머슨 핸콕",
  "Foster Griffin": "포스터 그리핀",
  "Griffin Jax": "그리핀 잭스",
  "Jack Kochanowicz": "잭 코카노위츠",
  "Jack Leiter": "잭 라이터",
  "Jacob Misiorowski": "제이콥 미시오로프스키",
  "Keider Montero": "케이더 몬테로",
  "Kris Bubic": "크리스 부빅",
  "Kyle Bradish": "카일 브래디시",
  "Kyle Freeland": "카일 프릴랜드",
  "Lance McCullers Jr.": "랜스 매컬러스 주니어",
  "Lance McCullers": "랜스 매컬러스 주니어",
  "Martín Pérez": "마르틴 페레스",
  "Martin Perez": "마르틴 페레스",
  "Matthew Liberatore": "매튜 리베라토레",
  "Merrill Kelly": "메릴 켈리",
  "Mitch Keller": "미치 켈러",
  "Nolan McLean": "놀란 매클린",
  "Parker Messick": "파커 메식",
  "Randy Vásquez": "랜디 바스케스",
  "Randy Vasquez": "랜디 바스케스",
  "Sean Burke": "션 버크",
  "Tyler Mahle": "타일러 메일리",
  "Will Warren": "윌 워런",
  "Zebby Matthews": "제비 매튜스",
};

const RAW_LOWER: Record<string, string> = Object.fromEntries(
  Object.entries(RAW).map(([k, v]) => [k.toLowerCase(), v]),
);

// 흔한 약식 표기: "C. Doucoure", "B. Saka" 같은 이니셜 + 성
// → 매핑이 없으면 영문 그대로 (LLM 이 보고 한국 미디어 표기로 변환 시도)
const STRIP_ACCENT_RE = /[̀-ͯ]/g;

function normalize(s: string): string {
  return s
    .normalize("NFD")
    .replace(STRIP_ACCENT_RE, "")
    .toLowerCase()
    .trim();
}

const RAW_NORMALIZED: Record<string, string> = Object.fromEntries(
  Object.entries(RAW).map(([k, v]) => [normalize(k), v]),
);

// 성(last name) 기반 fallback — "C. Doucoure" 같은 약식 표기 대응.
// 풀네임에서 마지막 토큰(성) 만 떼어내 키로, 매핑값(한글 풀네임)을 그대로 값으로.
// 동성이인이 있으면 가장 마지막에 등록된 매핑이 우선 (현재 데이터 규모에선 충돌 거의 없음).
const LAST_NAME_MAP: Record<string, string> = {};
for (const [en, ko] of Object.entries(RAW)) {
  const tokens = normalize(en).split(/\s+/).filter(Boolean);
  if (tokens.length < 2) continue;
  const lastEn = tokens[tokens.length - 1];
  if (!lastEn || lastEn.endsWith(".")) continue;
  LAST_NAME_MAP[lastEn] = ko;
}

// 충돌 흔한 성(서로 다른 한글값을 가진 동성이인) — last-name fallback 사용 금지
const AMBIGUOUS_LAST_NAMES = new Set<string>();
{
  const lastToVals = new Map<string, Set<string>>();
  for (const [en, ko] of Object.entries(RAW)) {
    const tokens = normalize(en).split(/\s+/).filter(Boolean);
    if (tokens.length < 2) continue;
    const last = tokens[tokens.length - 1];
    if (!last || last.endsWith(".")) continue;
    if (!lastToVals.has(last)) lastToVals.set(last, new Set());
    lastToVals.get(last)!.add(ko);
  }
  for (const [k, set] of lastToVals) {
    if (set.size > 1) AMBIGUOUS_LAST_NAMES.add(k);
  }
  // 흔한 일반 성 — 한국에 알려진 1명만 등록돼도 동성이인 위험 크니 강제 제외
  for (const s of [
    "james",
    "wilson",
    "jones",
    "moore",
    "taylor",
    "thomas",
    "smith",
    "white",
    "miller",
    "garcia",
    "rodriguez",
    "martinez",
    "lopez",
    "young",
    "king",
    "scott",
    "green",
    "hill",
    "lee",
    "hall",
    "allen",
    "wright",
    "walker",
    "perez",
    "cook",
    "morris",
    "rogers",
    "kim",
    "park",
    "lopez",
    "ferguson",
    "davies",
    "evans",
    "robinson",
    "carter",
  ]) {
    AMBIGUOUS_LAST_NAMES.add(s);
  }
}

const SHORT_NAME_RE = /^(?:[A-Za-z]\.\s*|[A-Za-z]\s+)([\wÀ-ſ'\-]+)$/;

function tryLastName(name: string): string | null {
  // 약식 표기 "C. Doucoure" 형태만 fallback — 풀네임은 정확 매치만 사용
  // (예: "Reece James" 가 last name 'James' fallback 으로 르브론 제임스로 잘못 매핑되던 버그 차단)
  const m = name.trim().match(SHORT_NAME_RE);
  if (!m) return null;
  const last = normalize(m[1]);
  if (AMBIGUOUS_LAST_NAMES.has(last)) return null;
  if (LAST_NAME_MAP[last]) return LAST_NAME_MAP[last];
  return null;
}

export function toKoreanPlayerName(name: string | undefined | null): string {
  if (!name) return "";
  const trimmed = name.trim();
  // 리그별 전용 사전 우선 lookup — API-Football roman / BDL / ESPN 표기 매핑
  if (K_LEAGUE_PLAYER_NAMES_KO[trimmed]) return K_LEAGUE_PLAYER_NAMES_KO[trimmed];
  if (J_LEAGUE_PLAYER_NAMES_KO[trimmed]) return J_LEAGUE_PLAYER_NAMES_KO[trimmed];
  // 위키 표제어(정본, build-salary-names-wiki.ts 동기) > 수동 사전 > 음역 순.
  if (NBA_PLAYER_NAMES_WIKI_KO[trimmed]) return NBA_PLAYER_NAMES_WIKI_KO[trimmed];
  if (NBA_PLAYER_NAMES_KO[trimmed]) return NBA_PLAYER_NAMES_KO[trimmed];
  if (NBA_PLAYER_NAMES_HAIKU_KO[trimmed]) return NBA_PLAYER_NAMES_HAIKU_KO[trimmed];
  if (NHL_PLAYER_NAMES_WIKI_KO[trimmed]) return NHL_PLAYER_NAMES_WIKI_KO[trimmed];
  if (NHL_PLAYER_NAMES_KO[trimmed]) return NHL_PLAYER_NAMES_KO[trimmed];
  if (NHL_INJURY_NAMES_HAIKU_KO[trimmed]) return NHL_INJURY_NAMES_HAIKU_KO[trimmed];
  if (WNBA_PLAYER_NAMES_KO[trimmed]) return WNBA_PLAYER_NAMES_KO[trimmed];
  if (MLB_PLAYER_NAMES_KO[trimmed]) return MLB_PLAYER_NAMES_KO[trimmed];
  if (MLB_PLAYER_NAMES_HAIKU_KO[trimmed]) return MLB_PLAYER_NAMES_HAIKU_KO[trimmed];
  if (MLB_INJURY_NAMES_HAIKU_KO[trimmed]) return MLB_INJURY_NAMES_HAIKU_KO[trimmed];
  // 네이버 사전은 734/745 가 성(姓)만 표기라 풀네임(위키·Haiku) 뒤로 강등 — 최후 폴백
  if (MLB_PLAYER_NAMES_NAVER_KO[trimmed]) return MLB_PLAYER_NAMES_NAVER_KO[trimmed];
  // MLB 분음부호 폴딩 재시도 — ESPN "Javier Báez" vs 사전 "Javier Baez" 불일치 구제 (중남미 선수)
  const mlbDeburred = trimmed.normalize("NFD").replace(/[̀-ͯ]/g, "");
  if (mlbDeburred !== trimmed) {
    if (MLB_PLAYER_NAMES_KO[mlbDeburred]) return MLB_PLAYER_NAMES_KO[mlbDeburred];
    if (MLB_PLAYER_NAMES_HAIKU_KO[mlbDeburred]) return MLB_PLAYER_NAMES_HAIKU_KO[mlbDeburred];
    if (MLB_INJURY_NAMES_HAIKU_KO[mlbDeburred]) return MLB_INJURY_NAMES_HAIKU_KO[mlbDeburred];
    if (MLB_PLAYER_NAMES_NAVER_KO[mlbDeburred]) return MLB_PLAYER_NAMES_NAVER_KO[mlbDeburred];
  }
  if (MLS_PLAYER_NAMES_KO[trimmed]) return MLS_PLAYER_NAMES_KO[trimmed];
  if (ESPN_LEADER_NAMES_KO[trimmed]) return ESPN_LEADER_NAMES_KO[trimmed];
  if (RAW[trimmed]) return RAW[trimmed];
  const lower = trimmed.toLowerCase();
  if (RAW_LOWER[lower]) return RAW_LOWER[lower];
  const normalized = normalize(trimmed);
  if (RAW_NORMALIZED[normalized]) return RAW_NORMALIZED[normalized];
  const byLast = tryLastName(trimmed);
  if (byLast) return byLast;
  // 매핑 누락 — 빌드/잡 환경 stderr 로만 출력 (production 사이트 로그엔 안 남김)
  if (process.env.NODE_ENV !== "production" || process.env.LOG_PLAYER_MISS) {
    console.warn(`[player-names] 매핑 없음: "${trimmed}"`);
  }
  return trimmed;
}
