// 영문 팀명 → 한글 표시명 매핑.
// 외부 데이터 소스(football-data, ESPN, MLB Stats, NHL API 등)가 영문으로만 응답하므로
// UI 표시 시에만 한글로 변환한다. DB(Team.name)는 원본 영문 그대로 유지.
//
// 매핑 누락 시 toKoreanTeamName 은 원본 영문을 그대로 반환 (fallback).
// 외래어 표기는 국립국어원 표기법 + 한국 스포츠 미디어 관행을 따른다.

const RAW: Record<string, string> = {
  // ─── EPL (2025-26) ───
  "Arsenal": "아스널",
  "Arsenal FC": "아스널",
  "Aston Villa": "아스톤 빌라",
  "Aston Villa FC": "아스톤 빌라",
  "Bournemouth": "본머스",
  "AFC Bournemouth": "본머스",
  "Brentford": "브렌트포드",
  "Brentford FC": "브렌트포드",
  "Brighton & Hove Albion": "브라이턴",
  "Brighton & Hove Albion FC": "브라이턴",
  "Brighton and Hove Albion": "브라이턴",
  "Burnley": "번리",
  "Burnley FC": "번리",
  "Chelsea": "첼시",
  "Chelsea FC": "첼시",
  "Crystal Palace": "크리스털 팰리스",
  "Crystal Palace FC": "크리스털 팰리스",
  "Everton": "에버턴",
  "Everton FC": "에버턴",
  "Fulham": "풀럼",
  "Fulham FC": "풀럼",
  "Ipswich Town": "입스위치",
  "Ipswich Town FC": "입스위치",
  "Leicester City": "레스터 시티",
  "Leicester City FC": "레스터 시티",
  "Leeds United": "리즈 유나이티드",
  "Leeds": "리즈 유나이티드",
  "Leeds United FC": "리즈 유나이티드",
  "Liverpool": "리버풀",
  "Liverpool FC": "리버풀",
  "Manchester City": "맨체스터 시티",
  "Manchester City FC": "맨체스터 시티",
  "Man City": "맨체스터 시티",
  "Manchester United": "맨체스터 유나이티드",
  "Manchester United FC": "맨체스터 유나이티드",
  "Man United": "맨체스터 유나이티드",
  "Newcastle": "뉴캐슬",
  "Newcastle United": "뉴캐슬",
  "Newcastle United FC": "뉴캐슬",
  "Nottingham Forest": "노팅엄 포레스트",
  "Nottingham Forest FC": "노팅엄 포레스트",
  "Nott'm Forest": "노팅엄 포레스트",
  "Southampton": "사우샘프턴",
  "Southampton FC": "사우샘프턴",
  "Sunderland": "선덜랜드",
  "Sunderland AFC": "선덜랜드",
  "Tottenham": "토트넘",
  "Tottenham Hotspur": "토트넘",
  "Tottenham Hotspur FC": "토트넘",
  "Spurs": "토트넘",
  "West Ham": "웨스트햄",
  "West Ham United": "웨스트햄",
  "West Ham United FC": "웨스트햄",
  "Wolverhampton": "울버햄튼",
  "Wolverhampton Wanderers": "울버햄튼",
  "Wolverhampton Wanderers FC": "울버햄튼",
  "Wolves": "울버햄튼",

  // ─── La Liga (2025-26) ───
  "Athletic Bilbao": "아틀레틱 빌바오",
  "Athletic Club": "아틀레틱 빌바오",
  "Atletico Madrid": "아틀레티코 마드리드",
  "Atlético Madrid": "아틀레티코 마드리드",
  "Atletico": "아틀레티코 마드리드",
  "Barcelona": "바르셀로나",
  "FC Barcelona": "바르셀로나",
  "Real Betis": "레알 베티스",
  "Betis": "레알 베티스",
  "Celta Vigo": "셀타 비고",
  "RC Celta": "셀타 비고",
  "Elche": "엘체",
  "Elche CF": "엘체",
  "Espanyol": "에스파뇰",
  "RCD Espanyol": "에스파뇰",
  "Getafe": "헤타페",
  "Getafe CF": "헤타페",
  "Girona": "지로나",
  "Girona FC": "지로나",
  "Levante": "레반테",
  "Levante UD": "레반테",
  "Mallorca": "마요르카",
  "RCD Mallorca": "마요르카",
  "Osasuna": "오사수나",
  "CA Osasuna": "오사수나",
  "Oviedo": "오비에도",
  "Real Oviedo": "오비에도",
  "Rayo Vallecano": "라요 바예카노",
  "Real Madrid": "레알 마드리드",
  "Real Sociedad": "레알 소시에다드",
  "Sevilla": "세비야",
  "Sevilla FC": "세비야",
  "Valencia": "발렌시아",
  "Valencia CF": "발렌시아",
  "Villarreal": "비야레알",
  "Villarreal CF": "비야레알",

  // ─── Bundesliga (2025-26) ───
  "Augsburg": "아우크스부르크",
  "FC Augsburg": "아우크스부르크",
  "Bayer Leverkusen": "레버쿠젠",
  "Leverkusen": "레버쿠젠",
  "Bayern Munich": "바이에른 뮌헨",
  "Bayern München": "바이에른 뮌헨",
  "FC Bayern München": "바이에른 뮌헨",
  "Borussia Dortmund": "도르트문트",
  "Borussia Dortmund FC": "도르트문트",
  "BV Borussia 09 Dortmund": "도르트문트",
  "BVB": "도르트문트",
  "Dortmund": "도르트문트",
  "Borussia Mönchengladbach": "묀헨글라트바흐",
  "Borussia Monchengladbach": "묀헨글라트바흐",
  "Mönchengladbach": "묀헨글라트바흐",
  "Eintracht Frankfurt": "프랑크푸르트",
  "Frankfurt": "프랑크푸르트",
  "Freiburg": "프라이부르크",
  "SC Freiburg": "프라이부르크",
  "Hamburger SV": "함부르크",
  "Hamburg": "함부르크",
  "Heidenheim": "하이덴하임",
  "1. FC Heidenheim": "하이덴하임",
  "Hoffenheim": "호펜하임",
  "TSG Hoffenheim": "호펜하임",
  "Holstein Kiel": "킬",
  "1. FC Köln": "쾰른",
  "Köln": "쾰른",
  "FC Köln": "쾰른",
  "Mainz": "마인츠",
  "Mainz 05": "마인츠",
  "1. FSV Mainz 05": "마인츠",
  "RB Leipzig": "RB 라이프치히",
  "Leipzig": "RB 라이프치히",
  "Stuttgart": "슈투트가르트",
  "VfB Stuttgart": "슈투트가르트",
  "Union Berlin": "우니온 베를린",
  "1. FC Union Berlin": "우니온 베를린",
  "Werder Bremen": "베르더 브레멘",
  "SV Werder Bremen": "베르더 브레멘",
  "Wolfsburg": "볼프스부르크",
  "VfL Wolfsburg": "볼프스부르크",
  "St. Pauli": "장크트 파울리",
  "FC St. Pauli": "장크트 파울리",

  // ─── Serie A (2025-26) ───
  "AC Milan": "AC 밀란",
  "Milan": "AC 밀란",
  "Atalanta": "아탈란타",
  "Atalanta BC": "아탈란타",
  "Bologna": "볼로냐",
  "Bologna FC 1909": "볼로냐",
  "Cagliari": "칼리아리",
  "Cagliari Calcio": "칼리아리",
  "Como": "코모",
  "Como 1907": "코모",
  "Empoli": "엠폴리",
  "Empoli FC": "엠폴리",
  "Fiorentina": "피오렌티나",
  "ACF Fiorentina": "피오렌티나",
  "Genoa": "제노아",
  "Genoa CFC": "제노아",
  "Hellas Verona": "베로나",
  "Verona": "베로나",
  "Inter": "인터 밀란",
  "Inter Milan": "인터 밀란",
  "Internazionale": "인터 밀란",
  "FC Internazionale Milano": "인터 밀란",
  "Juventus": "유벤투스",
  "Juventus FC": "유벤투스",
  "Lazio": "라치오",
  "SS Lazio": "라치오",
  "Lecce": "레체",
  "US Lecce": "레체",
  "Monza": "몬차",
  "AC Monza": "몬차",
  "Napoli": "나폴리",
  "SSC Napoli": "나폴리",
  "Parma": "파르마",
  "Parma Calcio 1913": "파르마",
  "Pisa": "피사",
  "Pisa SC": "피사",
  "Roma": "AS 로마",
  "AS Roma": "AS 로마",
  "Sassuolo": "사수올로",
  "US Sassuolo": "사수올로",
  "Torino": "토리노",
  "Torino FC": "토리노",
  "Udinese": "우디네세",
  "Udinese Calcio": "우디네세",
  "Venezia": "베네치아",
  "Venezia FC": "베네치아",
  "Cremonese": "크레모네세",
  "US Cremonese": "크레모네세",

  // ─── Ligue 1 (2025-26) ───
  "Angers": "앙제",
  "Angers SCO": "앙제",
  "Auxerre": "오세르",
  "AJ Auxerre": "오세르",
  "Brest": "브레스트",
  "Stade Brestois 29": "브레스트",
  "Le Havre": "르아브르",
  "Le Havre AC": "르아브르",
  "Lens": "랭스",
  "RC Lens": "랭스",
  "Lille": "릴",
  "LOSC Lille": "릴",
  "Lorient": "로리앙",
  "FC Lorient": "로리앙",
  "Lyon": "리옹",
  "Olympique Lyonnais": "리옹",
  "Marseille": "마르세유",
  "Olympique de Marseille": "마르세유",
  "Olympique Marseille": "마르세유",
  "Metz": "메스",
  "FC Metz": "메스",
  "Monaco": "AS 모나코",
  "AS Monaco": "AS 모나코",
  "Nantes": "낭트",
  "FC Nantes": "낭트",
  "Nice": "니스",
  "OGC Nice": "니스",
  "Paris FC": "파리 FC",
  "Paris Saint-Germain": "파리 생제르맹",
  "Paris Saint Germain": "파리 생제르맹",
  "PSG": "파리 생제르맹",
  "Reims": "랭스 SR",
  "Stade Reims": "랭스 SR",
  "Stade de Reims": "랭스 SR",
  "Rennes": "렌",
  "Stade Rennais": "렌",
  "Stade Rennais FC": "렌",
  "Saint-Étienne": "생테티엔",
  "AS Saint-Étienne": "생테티엔",
  "Saint-Etienne": "생테티엔",
  "Strasbourg": "스트라스부르",
  "RC Strasbourg Alsace": "스트라스부르",
  "Toulouse": "툴루즈",
  "Toulouse FC": "툴루즈",

  // ─── MLS (편의: 도시명 위주 한글, 2026 시즌) ───
  "Atlanta United FC": "애틀랜타 유나이티드",
  "Austin FC": "오스틴 FC",
  "CF Montréal": "CF 몬트리올",
  "Charlotte FC": "샬럿 FC",
  "Chicago Fire FC": "시카고 파이어",
  "Colorado Rapids": "콜로라도 래피즈",
  "Columbus Crew": "콜럼버스 크루",
  "D.C. United": "DC 유나이티드",
  "FC Cincinnati": "FC 신시내티",
  "FC Dallas": "FC 댈러스",
  "Houston Dynamo FC": "휴스턴 다이너모",
  "Inter Miami CF": "인터 마이애미",
  "LA Galaxy": "LA 갤럭시",
  "Los Angeles FC": "LAFC",
  "Minnesota United FC": "미네소타 유나이티드",
  "Nashville SC": "내슈빌 SC",
  "New England Revolution": "뉴잉글랜드 레볼루션",
  "New York City FC": "뉴욕 시티 FC",
  "New York Red Bulls": "뉴욕 레드불스",
  "Orlando City SC": "올랜도 시티",
  "Philadelphia Union": "필라델피아 유니언",
  "Portland Timbers": "포틀랜드 팀버스",
  "Real Salt Lake": "리얼 솔트레이크",
  "San Diego FC": "샌디에이고 FC",
  "San Jose Earthquakes": "산호세 어스퀘이크",
  "Seattle Sounders FC": "시애틀 사운더스",
  "Sporting Kansas City": "스포팅 캔자스시티",
  "St. Louis City SC": "세인트루이스 시티",
  "Toronto FC": "토론토 FC",
  "Vancouver Whitecaps FC": "밴쿠버 화이트캡스",

  // ─── NBA ───
  "Atlanta Hawks": "애틀랜타 호크스",
  "Boston Celtics": "보스턴 셀틱스",
  "Brooklyn Nets": "브루클린 네츠",
  "Charlotte Hornets": "샬럿 호네츠",
  "Chicago Bulls": "시카고 불스",
  "Cleveland Cavaliers": "클리블랜드 캐벌리어스",
  "Dallas Mavericks": "댈러스 매버릭스",
  "Denver Nuggets": "덴버 너기츠",
  "Detroit Pistons": "디트로이트 피스턴스",
  "Golden State Warriors": "골든스테이트 워리어스",
  "Houston Rockets": "휴스턴 로키츠",
  "Indiana Pacers": "인디애나 페이서스",
  "LA Clippers": "LA 클리퍼스",
  "Los Angeles Clippers": "LA 클리퍼스",
  "Los Angeles Lakers": "LA 레이커스",
  "LA Lakers": "LA 레이커스",
  "Memphis Grizzlies": "멤피스 그리즐리스",
  "Miami Heat": "마이애미 히트",
  "Milwaukee Bucks": "밀워키 벅스",
  "Minnesota Timberwolves": "미네소타 팀버울브스",
  "New Orleans Pelicans": "뉴올리언스 펠리컨스",
  "New York Knicks": "뉴욕 닉스",
  "Oklahoma City Thunder": "오클라호마시티 썬더",
  "Orlando Magic": "올랜도 매직",
  "Philadelphia 76ers": "필라델피아 76ers",
  "Phoenix Suns": "피닉스 선스",
  "Portland Trail Blazers": "포틀랜드 트레일블레이저스",
  "Sacramento Kings": "새크라멘토 킹스",
  "San Antonio Spurs": "샌안토니오 스퍼스",
  "Toronto Raptors": "토론토 랩터스",
  "Utah Jazz": "유타 재즈",
  "Washington Wizards": "워싱턴 위저즈",

  // ─── NHL ───
  "Anaheim Ducks": "애너하임 덕스",
  "Boston Bruins": "보스턴 브루인스",
  "Buffalo Sabres": "버펄로 세이버스",
  "Calgary Flames": "캘거리 플레임스",
  "Carolina Hurricanes": "캐롤라이나 허리케인스",
  "Chicago Blackhawks": "시카고 블랙호크스",
  "Colorado Avalanche": "콜로라도 애벌랜치",
  "Columbus Blue Jackets": "콜럼버스 블루재키츠",
  "Dallas Stars": "댈러스 스타스",
  "Detroit Red Wings": "디트로이트 레드윙스",
  "Edmonton Oilers": "에드먼턴 오일러스",
  "Florida Panthers": "플로리다 팬서스",
  "Los Angeles Kings": "LA 킹스",
  "LA Kings": "LA 킹스",
  "Minnesota Wild": "미네소타 와일드",
  "Montreal Canadiens": "몬트리올 캐나디언스",
  "Montréal Canadiens": "몬트리올 캐나디언스",
  "Nashville Predators": "내슈빌 프레데터스",
  "New Jersey Devils": "뉴저지 데블스",
  "New York Islanders": "뉴욕 아일랜더스",
  "New York Rangers": "뉴욕 레인저스",
  "Ottawa Senators": "오타와 세너터스",
  "Philadelphia Flyers": "필라델피아 플라이어스",
  "Pittsburgh Penguins": "피츠버그 펭귄스",
  "San Jose Sharks": "산호세 샤크스",
  "Seattle Kraken": "시애틀 크라켄",
  "St. Louis Blues": "세인트루이스 블루스",
  "Tampa Bay Lightning": "탬파베이 라이트닝",
  "Toronto Maple Leafs": "토론토 메이플리프스",
  "Utah Hockey Club": "유타 하키 클럽",
  "Utah Mammoth": "유타 매머드",
  "Vancouver Canucks": "밴쿠버 캐넉스",
  "Vegas Golden Knights": "베이거스 골든나이츠",
  "Washington Capitals": "워싱턴 캐피털스",
  "Winnipeg Jets": "위니펙 제츠",

  // ─── MLB ───
  "Arizona Diamondbacks": "애리조나 다이아몬드백스",
  "Atlanta Braves": "애틀랜타 브레이브스",
  "Baltimore Orioles": "볼티모어 오리올스",
  "Boston Red Sox": "보스턴 레드삭스",
  "Chicago Cubs": "시카고 컵스",
  "Chicago White Sox": "시카고 화이트삭스",
  "Cincinnati Reds": "신시내티 레즈",
  "Cleveland Guardians": "클리블랜드 가디언스",
  "Colorado Rockies": "콜로라도 로키스",
  "Detroit Tigers": "디트로이트 타이거스",
  "Houston Astros": "휴스턴 애스트로스",
  "Kansas City Royals": "캔자스시티 로열스",
  "Los Angeles Angels": "LA 에인절스",
  "Los Angeles Dodgers": "LA 다저스",
  "LA Dodgers": "LA 다저스",
  "Miami Marlins": "마이애미 말린스",
  "Milwaukee Brewers": "밀워키 브루어스",
  "Minnesota Twins": "미네소타 트윈스",
  "New York Mets": "뉴욕 메츠",
  "New York Yankees": "뉴욕 양키스",
  "Oakland Athletics": "오클랜드 애슬레틱스",
  "Athletics": "오클랜드 애슬레틱스",
  "Philadelphia Phillies": "필라델피아 필리스",
  "Pittsburgh Pirates": "피츠버그 파이리츠",
  "San Diego Padres": "샌디에이고 파드리스",
  "San Francisco Giants": "샌프란시스코 자이언츠",
  "Seattle Mariners": "시애틀 매리너스",
  "St. Louis Cardinals": "세인트루이스 카디널스",
  "Tampa Bay Rays": "탬파베이 레이스",
  "Texas Rangers": "텍사스 레인저스",
  "Toronto Blue Jays": "토론토 블루제이스",
  "Washington Nationals": "워싱턴 내셔널스",

  // ─── KBO (kbo.ts 와 일치) ───
  "KIA Tigers": "KIA 타이거즈",
  "Samsung Lions": "삼성 라이온즈",
  "LG Twins": "LG 트윈스",
  "Doosan Bears": "두산 베어스",
  "KT Wiz": "KT 위즈",
  "KT Wiz Suwon": "KT 위즈",
  "SSG Landers": "SSG 랜더스",
  "Lotte Giants": "롯데 자이언츠",
  "Hanwha Eagles": "한화 이글스",
  "NC Dinos": "NC 다이노스",
  "Kiwoom Heroes": "키움 히어로즈",

  // ─── 월드컵 진출국 (편의 — 한글 국가명) ───
  "South Korea": "대한민국",
  "Korea Republic": "대한민국",
  "Japan": "일본",
  "United States": "미국",
  "USA": "미국",
  "Canada": "캐나다",
  "Mexico": "멕시코",
  "Argentina": "아르헨티나",
  "Brazil": "브라질",
  "Uruguay": "우루과이",
  "Colombia": "콜롬비아",
  "Ecuador": "에콰도르",
  "Paraguay": "파라과이",
  "Bolivia": "볼리비아",
  "Chile": "칠레",
  "Peru": "페루",
  "Venezuela": "베네수엘라",
  "Spain": "스페인",
  "England": "잉글랜드",
  "France": "프랑스",
  "Germany": "독일",
  "Portugal": "포르투갈",
  "Italy": "이탈리아",
  "Netherlands": "네덜란드",
  "Belgium": "벨기에",
  "Croatia": "크로아티아",
  "Switzerland": "스위스",
  "Austria": "오스트리아",
  "Denmark": "덴마크",
  "Sweden": "스웨덴",
  "Norway": "노르웨이",
  "Poland": "폴란드",
  "Czech Republic": "체코",
  "Czechia": "체코",
  "Turkey": "튀르키예",
  "Türkiye": "튀르키예",
  "Australia": "호주",
  "Saudi Arabia": "사우디아라비아",
  "Iran": "이란",
  "Iraq": "이라크",
  "Qatar": "카타르",
  "United Arab Emirates": "아랍에미리트",
  "Uzbekistan": "우즈베키스탄",
  "Jordan": "요르단",
  "Morocco": "모로코",
  "Senegal": "세네갈",
  "Tunisia": "튀니지",
  "Egypt": "이집트",
  "Nigeria": "나이지리아",
  "Cameroon": "카메룬",
  "Ghana": "가나",
  "Ivory Coast": "코트디부아르",
  "Côte d'Ivoire": "코트디부아르",
  "Algeria": "알제리",
  "Costa Rica": "코스타리카",
  "Panama": "파나마",
  "Jamaica": "자메이카",
  "New Zealand": "뉴질랜드",

  // K리그 1
  "FC Seoul": "FC 서울",
  "Daejeon Citizen": "대전 하나 시티즌",
  "Daejeon Hana Citizen": "대전 하나 시티즌",
  "Incheon United": "인천 유나이티드",
  "Gwangju FC": "광주 FC",
  "Jeonbuk Motors": "전북 현대 모터스",
  "Jeonbuk Hyundai Motors": "전북 현대 모터스",
  "Gimcheon Sangmu FC": "김천 상무",
  "Gimcheon Sangmu": "김천 상무",
  "Jeju United FC": "제주 SK FC",
  "Jeju United": "제주 SK FC",
  "FC Anyang": "FC 안양",
  "Anyang": "FC 안양",
  "Bucheon FC 1995": "부천 FC 1995",
  "Bucheon FC": "부천 FC 1995",
  "Pohang Steelers": "포항 스틸러스",
  "Gangwon FC": "강원 FC",
  "Ulsan Hyundai FC": "울산 HD",
  "Ulsan Hyundai": "울산 HD",
  "Ulsan HD FC": "울산 HD",
  "Ulsan HD": "울산 HD",
  "Suwon Samsung Bluewings": "수원 삼성",
  "Daegu FC": "대구 FC",

  // K리그 2
  "Seoul E-Land FC": "서울 이랜드",
  "Seoul E-Land": "서울 이랜드",
  "Yongin City": "용인 시티",
  "Jeonnam Dragons": "전남 드래곤즈",
  "Cheongju": "충북 청주",
  "Chungbuk Cheongju": "충북 청주",
  "Ansan Greeners": "안산 그리너스",
  "Gimpo Citizen": "김포 FC",
  "Gimpo FC": "김포 FC",
  "Cheonan City": "천안 시티",
  "Cheonan City FC": "천안 시티",
  "Paju Citizen": "파주 시티즌",
  "Seongnam FC": "성남 FC",
  "Gyeongnam FC": "경남 FC",
  "Gimhae City": "김해 FC",
  "Hwaseong": "화성 FC",
  "Hwaseong FC": "화성 FC",
  "Busan I Park": "부산 아이파크",
  "Busan IPark": "부산 아이파크",
  "Asan Mugunghwa": "충남 아산",
  "Chungnam Asan FC": "충남 아산",
  "Suwon City FC": "수원 FC",
  "Suwon FC": "수원 FC",

  // J1 리그
  "Urawa Red Diamonds": "우라와 레드 다이아몬즈",
  "Urawa": "우라와",
  "FC Tokyo": "FC 도쿄",
  "Yokohama F. Marinos": "요코하마 F. 마리노스",
  "Yokohama FMarinos": "요코하마 F. 마리노스",
  "Kashiwa Reysol": "가시와 레이솔",
  "Vissel Kobe": "비셀 고베",
  "Gamba Osaka": "감바 오사카",
  "Cerezo Osaka": "세레소 오사카",
  "Kashima": "가시마 앤틀러스",
  "Kashima Antlers": "가시마 앤틀러스",
  "Sanfrecce Hiroshima": "산프레체 히로시마",
  "Avispa Fukuoka": "아비스파 후쿠오카",
  "Nagoya Grampus": "나고야 그램퍼스",
  "Kawasaki Frontale": "가와사키 프론탈레",
  "Shonan Bellmare": "쇼난 벨마레",
  "Fagiano Okayama": "파지아노 오카야마",
  "V-varen Nagasaki": "V-바렌 나가사키",
  "Tokyo Verdy": "도쿄 베르디",
  "Sagan Tosu": "사강 토스",
  "Albirex Niigata": "알비렉스 니가타",
  "Kyoto Sanga": "교토 상가",
  "Kyoto Sanga FC": "교토 상가",
  "Machida Zelvia": "마치다 젤비아",
  "FC Machida Zelvia": "마치다 젤비아",
  "Yokohama FC": "요코하마 FC",
  "Shimizu S-Pulse": "시미즈 S펄스",

  // 추가 — 분데스리가 영문 변형 + LCK + 한국 K2 / J2 잔여
  // ("Hamburger SV"/"1. FC Köln"/"FC Köln" 은 위에 이미 매핑 있음)
  "Hamburg SV": "함부르크",
  "HSV": "함부르크",
  "FC Cologne": "쾰른",
  "Cologne": "쾰른",
  "Mito Hollyhock": "미토 홀리호크",
  "Tokyo Verdy 1969": "도쿄 베르디",
  "Verdy": "도쿄 베르디",
  "Gen.G": "젠지",
  "Gen.G eSports": "젠지",
  "Ibiza": "이비사",
  "UD Ibiza": "이비사",

  // AFC 챔피언스리그 — 자주 등장하는 아시아 클럽 (자국 매핑 보강)
  "Al Hilal": "알 힐랄",
  "Al Nassr": "알 나스르",
  "Al Ittihad": "알 이티하드",
  "Al Ahli": "알 아흘리",
  "Buriram United": "부리람 유나이티드",
  "Shanghai Port": "상하이 하이강",
  "Shanghai SIPG": "상하이 하이강",
  "Shandong Taishan": "산둥 타이산",
  "Yokohama F Marinos": "요코하마 F. 마리노스",

  // 사우디 프로 리그 추가
  "Al Ittihad Jeddah": "알 이티하드",
  "Al-Ittihad": "알 이티하드",
  "Al-Hilal": "알 힐랄",
  "Al-Nassr": "알 나스르",
  "Al-Ahli": "알 아흘리",
  "Al-Shabab": "알 셰바브",
  "Al Shabab": "알 셰바브",
  "Al Taawoun": "알 타아원",
  "Al-Taawoun": "알 타아원",
  "Al Ettifaq": "담맘 알 이티파크",
  "Al-Ettifaq": "담맘 알 이티파크",
  "Al Fateh": "알 파테",
  "Al-Fateh": "알 파테",
  "Al Qadsiah": "알 카드시아",
  "Al-Qadsiah": "알 카드시아",
  "Al Wehda": "알 와다",
  "Al-Wehda": "알 와다",
  "Al Riyadh": "알 리야드",
  "Al-Riyadh": "알 리야드",
  "Al Khaleej": "알 칼리지",
  "Al-Khaleej": "알 칼리지",
  "Damac": "다막",

  // 중국 슈퍼리그 (CSL)
  "Shanghai Shenhua": "상하이 션화",
  "Beijing Guoan": "베이징 궈안",
  "Shenzhen Peng City": "선전 펑청",
  "Tianjin Jinmen Tiger": "톈진 진먼후",
  "Wuhan Three Towns": "우한 싼전",
  "Chengdu Rongcheng": "청두 룽청",
  "Henan Songshan Longmen": "허난 쑹산",
  "Zhejiang FC": "저장 FC",
  "Changchun Yatai": "창춘 야타이",
  "Qingdao West Coast": "칭다오 시윤",
  "Nantong Zhiyun": "난통 즈윈",
  "Meizhou Hakka": "메이저우 하카",
  "Yunnan Yukun": "윈난 위쿤",
  "Qingdao Hainiu": "칭다오 하이뉴",

  // 호주 A-리그
  "Melbourne Victory": "멜버른 빅토리",
  "Sydney FC": "시드니 FC",
  "Western Sydney Wanderers": "웨스턴 시드니 원더러스",
  "Adelaide United": "애들레이드 유나이티드",
  "Perth Glory": "퍼스 글로리",
  "Newcastle Jets": "뉴캐슬 제츠",
  "Brisbane Roar": "브리즈번 로어",
  "Macarthur FC": "매카서 FC",
  "Wellington Phoenix": "웰링턴 피닉스",
  "Western United": "웨스턴 유나이티드",
  "Melbourne City": "멜버른 시티",
  "Central Coast Mariners": "센트럴 코스트 매리너스",
  "Auckland FC": "오클랜드 FC",

  // 네덜란드 에레디비시
  "Ajax": "아약스",
  "PSV Eindhoven": "PSV 에인트호번",
  "PSV": "PSV 에인트호번",
  "Feyenoord": "페예노르트",
  "AZ Alkmaar": "AZ 알크마르",
  "AZ": "AZ 알크마르",
  "FC Twente": "FC 트벤터",
  "Twente": "FC 트벤터",
  "FC Utrecht": "FC 위트레흐트",
  "Utrecht": "FC 위트레흐트",
  "Sparta Rotterdam": "스파르타 로테르담",
  "Heerenveen": "헤렌베인",
  "SC Heerenveen": "헤렌베인",
  "NEC Nijmegen": "NEC 네이메헌",
  "NEC": "NEC 네이메헌",
  "Vitesse": "비테세",
  "Heracles": "헤라클레스",
  "Heracles Almelo": "헤라클레스",
  "Go Ahead Eagles": "고 어헤드 이글스",
  "RKC Waalwijk": "RKC 발베이크",
  "Volendam": "폴렌담",
  "FC Volendam": "폴렌담",
  "Almere City": "알메러 시티",
  "PEC Zwolle": "PEC 즈볼레",
  "NAC Breda": "NAC 브레다",
  "Fortuna Sittard": "포르투나 시타르트",
  "Excelsior": "엑셀시오르",

  // 포르투갈 프리메이라 리가
  "Porto": "FC 포르투",
  "FC Porto": "FC 포르투",
  "Benfica": "벤피카",
  "SL Benfica": "벤피카",
  "Sporting CP": "스포르팅 CP",
  "Sporting Lisbon": "스포르팅 CP",
  "Braga": "SC 브라가",
  "SC Braga": "SC 브라가",
  "Vitoria Guimaraes": "비토리아 SC",
  "Vitoria SC": "비토리아 SC",
  "Famalicao": "파말리캉",
  "FC Famalicao": "파말리캉",
  "Estoril": "에스토릴",
  "Boavista": "보아비스타",
  "Rio Ave": "히우 아브",
  "Casa Pia": "카사 피아",
  "Moreirense": "모레이렌세",
  "Estrela": "에스트렐라",
  "Chaves": "샤베스",
  "Portimonense": "포르티모넨세",
  "Gil Vicente": "질 비센테",
  "Arouca": "아루카",
  "AVS": "AVS",
  "Nacional": "나시오날",
  "Santa Clara": "산타 클라라",
  "Farense": "파렌세",

  // 터키 쉬페르 리그
  "Galatasaray": "갈라타사라이",
  "Fenerbahce": "페네르바체",
  "Fenerbahçe": "페네르바체",
  "Besiktas": "베식타스",
  "Beşiktaş": "베식타스",
  "Trabzonspor": "트라브존스포르",
  "Basaksehir": "바샤크셰히르",
  "Başakşehir": "바샤크셰히르",
  "Konyaspor": "코냐스포르",
  "Antalyaspor": "안탈리아스포르",
  "Alanyaspor": "알라니아스포르",
  "Adana Demirspor": "아다나 데미르스포르",
  "Kasimpasa": "카심파샤",
  "Kasımpaşa": "카심파샤",
  "Goztepe": "괴즈테페",
  "Göztepe": "괴즈테페",
  "Eyupspor": "에이윱스포르",
  "Pendikspor": "펜디크스포르",
  "Samsunspor": "삼순스포르",
  "Hatayspor": "하타이스포르",
  "Bodrumspor": "보드룸스포르",
  "Kayserispor": "카이세리스포르",
  "Sivasspor": "시바스스포르",
  "Gaziantep": "가지안테프",
  "Gaziantep FK": "가지안테프",
  "Rizespor": "리제스포르",
  "Caykur Rizespor": "리제스포르",

  // 벨기에 주피러 프로 리그
  "Anderlecht": "안더레흐트",
  "RSC Anderlecht": "안더레흐트",
  "Club Brugge": "클럽 브뤼헤",
  "Club Brugge KV": "클럽 브뤼헤",
  "Genk": "헹크",
  "KRC Genk": "헹크",
  "Standard Liege": "스탕다르 리에주",
  "Standard Liège": "스탕다르 리에주",
  "Antwerp": "안트베르펜",
  "Royal Antwerp": "안트베르펜",
  "Royale Union SG": "위니옹 SG",
  "Union St. Gilloise": "위니옹 SG",
  "Union Saint-Gilloise": "위니옹 SG",
  "Mechelen": "메헬렌",
  "KV Mechelen": "메헬렌",
  "Gent": "헨트",
  "KAA Gent": "헨트",
  "Westerlo": "베스털로",
  "Cercle Brugge": "세르클 브뤼헤",
  "OH Leuven": "OH 뢰번",
  "Charleroi": "샤를루아",
  "Sint-Truidense": "신트트라위던",
  "Kortrijk": "코르트레이크",
  "Beerschot": "베르스호트",
  "Dender": "덴더르",

  // 스코틀랜드 SPL
  "Celtic": "셀틱",
  "Rangers": "레인저스",
  "Aberdeen": "애버딘",
  "Hearts": "하츠",
  "Heart of Midlothian": "하츠",
  "Hibernian": "히버니언",
  "Motherwell": "머더웰",
  "St Mirren": "세인트 미렌",
  "St. Mirren": "세인트 미렌",
  "Dundee": "던디",
  "Dundee United": "던디 유나이티드",
  "Kilmarnock": "킬마녹",
  "St Johnstone": "세인트 존스턴",
  "St. Johnstone": "세인트 존스턴",
  "Ross County": "로스 카운티",

  // 그리스 슈퍼리그
  "Olympiacos": "올림피아코스",
  "Olympiakos Piraeus": "올림피아코스",
  "Panathinaikos": "파나티나이코스",
  "PAOK": "PAOK",
  "PAOK Salonika": "PAOK",
  "AEK Athens": "AEK 아테네",
  "AEK Athens FC": "AEK 아테네",
  "Aris": "아리스",
  "Aris Thessaloniki": "아리스",
  "OFI": "OFI",
  "OFI Crete": "OFI",
  "Volos NPS": "볼로스",
  "Atromitos": "아트로미토스",
  "Lamia": "라미아",
  "Panaitolikos": "파나이톨리코스",
  "Kifissia": "키피시아",
  "Asteras Tripolis": "아스테라스 트리폴리스",
  "Levadiakos": "레바디아코스",

  // 브라질 세리에 A
  "Flamengo": "플라멩구",
  "Palmeiras": "팔메이라스",
  "Sao Paulo": "상파울루",
  "São Paulo": "상파울루",
  "Corinthians": "코린치앙스",
  "Santos": "산투스",
  "Botafogo": "보타포구",
  "Fluminense": "플루미네시",
  "Vasco DA Gama": "바스쿠 다 가마",
  "Vasco da Gama": "바스쿠 다 가마",
  "Internacional": "인테르나시오나우",
  "Gremio": "그레미우",
  "Grêmio": "그레미우",
  "Atletico-MG": "아틀레치쿠 미네이루",
  "Atlético Mineiro": "아틀레치쿠 미네이루",
  "Cruzeiro": "크루제이루",
  "Bahia": "바이아",
  "Vitoria": "비토리아",
  "Vitória": "비토리아",
  "Fortaleza": "포르탈레자",
  "EC Vitoria": "비토리아",
  "Ceara": "세아라",
  "Ceará": "세아라",
  "Sport Recife": "스포르치 헤시피",
  "Bragantino": "브라간치누",
  "RB Bragantino": "브라간치누",
  "Red Bull Bragantino": "브라간치누",
  "Athletico-PR": "아틀레치쿠 파라넨세",
  "Athletico Paranaense": "아틀레치쿠 파라넨세",
  "Juventude": "주벤투지",
  "Mirassol": "미라솔",

  // 멕시코 Liga MX
  "America": "클럽 아메리카",
  "Club America": "클럽 아메리카",
  "Club América": "클럽 아메리카",
  "Cruz Azul": "크루스 아술",
  "Chivas Guadalajara": "치바스",
  "Chivas": "치바스",
  "CD Guadalajara": "치바스",
  "Club Deportivo Guadalajara": "치바스",
  "Guadalajara": "치바스",
  "Pumas UNAM": "푸마스",
  "U.N.A.M.- Pumas": "푸마스",
  "Tigres": "티그레스",
  "Tigres UANL": "티그레스",
  "Monterrey": "몬테레이",
  "Toluca": "톨루카",
  "Pachuca": "파추카",
  "Leon": "레온",
  "León": "레온",
  "Club Leon": "레온",
  "Santos Laguna": "산토스 라구나",
  "Atlas": "아틀라스",
  "Mazatlan": "마사틀란",
  "Mazatlán": "마사틀란",
  "Necaxa": "네카사",
  "Queretaro": "케레타로",
  "Querétaro": "케레타로",
  "Puebla": "푸에블라",
  "Tijuana": "티후아나",
  "FC Juarez": "FC 후아레스",
  "FC Juárez": "FC 후아레스",
  "Atletico San Luis": "아틀레티코 산 루이스",
  "Atlético San Luis": "아틀레티코 산 루이스",

  // CSL 추가
  "Shenyang Urban": "선양 어반",
  "Chongqing Tongliang Long": "충칭 퉁량 룽",
  "Chongqing Tongliangloong": "충칭 퉁량 룽",

  // 라리가 2 (세군다) 추가
  "Real Sociedad II": "레알 소시에다드 B",
  "Real Sociedad B": "레알 소시에다드 B",
  "Mirandes": "미란데스",
  "CD Mirandes": "미란데스",
  "AD Ceuta FC": "AD 세우타",
  "Ceuta": "AD 세우타",
  "AD Ceuta": "AD 세우타",

  // 분데스리가 풀네임 alias
  "1. FC Heidenheim 1846": "하이덴하임",
  "1.FC Heidenheim 1846": "하이덴하임",

  // EPL/UCL short alias
  "Brighton Hove": "브라이턴",
  "Brighton Hove Albion": "브라이턴",
  "Brighton": "브라이턴",
  "Nottingham": "노팅엄 포레스트",

  // 사우디 spelling 변형
  "Al-Fayha": "알 파이하",
  "Al Fayha": "알 파이하",
  "Al Taawon": "알 타아원",
  "Al-Taawon": "알 타아원",

  // 세리에 B
  "Sudtirol": "쥐드티롤",
  "Südtirol": "쥐드티롤",
  "FC Sudtirol": "쥐드티롤",
  "Bari": "바리",
  "SSC Bari": "바리",

  // 스코틀랜드 추가
  "Falkirk": "팔커크",

  // ═══════════════════════════════════════════════════════════════
  // ▼▼▼ 신규 리그 팀명 한글화 확장 (Member 3 — team-translator v2)
  // 한국 미디어 통용 표기로 통일. 변형 표기까지 모두 등록.
  // ═══════════════════════════════════════════════════════════════

  // ─── K리그1 (K_LEAGUE_1) 보강 ───
  "Ulsan": "울산 HD",
  "Jeonbuk Hyundai": "전북 현대 모터스",
  "Jeonbuk Hyundai Motors FC": "전북 현대 모터스",
  "Pohang": "포항 스틸러스",
  "Gimcheon": "김천 상무",
  "Suwon City": "수원 FC",
  "Gwangju": "광주 FC",
  "Daegu": "대구 FC",
  "Gangwon": "강원 FC",
  "Incheon": "인천 유나이티드",
  "Jeju SK": "제주 SK FC",
  "Jeju SK FC": "제주 SK FC",
  "Daejeon": "대전 하나 시티즌",
  "Seoul": "FC 서울",

  // ─── K리그2 (K_LEAGUE_2) 보강 ───
  "Busan": "부산 아이파크",
  "Seongnam": "성남 FC",
  "Bucheon": "부천 FC 1995",
  "Asan": "충남 아산",
  "Chungnam Asan": "충남 아산",
  "Gyeongnam": "경남 FC",
  "Ansan": "안산 그리너스",
  "Ansan Greeners FC": "안산 그리너스",
  "Chungbuk": "충북 청주",
  "Cheongju FC": "충북 청주",
  "Gimpo": "김포 FC",
  "Cheonan": "천안 시티 FC",
  "Seoul ELand": "서울 이랜드 FC",
  "Anyang FC": "안양 FC",

  // ─── J1 리그 보강 (한국 미디어 통용 표기) ───
  "Vissel Kobe FC": "비셀 고베",
  "Yokohama F·Marinos": "요코하마 F. 마리노스",
  "Yokohama F Marinos FC": "요코하마 F. 마리노스",
  "Kawasaki": "가와사키 프론탈레",
  "Kawasaki Frontale FC": "가와사키 프론탈레",
  "Urawa Reds": "우라와 레드 다이아몬즈",
  "Hokkaido Consadole Sapporo": "홋카이도 콘사도레 삿포로",
  "Consadole Sapporo": "홋카이도 콘사도레 삿포로",
  "Sapporo": "홋카이도 콘사도레 삿포로",
  "Kashima Antlers FC": "가시마 앤틀러스",
  "Hiroshima": "산프레체 히로시마",
  "Cerezo": "세레소 오사카",
  "Gamba": "감바 오사카",
  "Kashiwa": "가시와 레이솔",
  "Nagoya": "나고야 그램퍼스",

  // ─── J2 리그 ───
  "Shimizu S-Pulse FC": "시미즈 S-펄스",
  "Shimizu": "시미즈 S-펄스",
  "Vegalta Sendai": "베갈타 센다이",
  "Sendai": "베갈타 센다이",
  "Omiya Ardija": "오미야 아르디자",
  "Iwaki": "이와키 FC",
  "Iwaki FC": "이와키 FC",
  "Fujieda MYFC": "후지에다 MYFC",
  "V-Varen Nagasaki": "V-바렌 나가사키",
  "Tochigi SC": "도치기 SC",
  "Tochigi": "도치기 SC",
  "Montedio Yamagata": "몬테디오 야마가타",
  "Yamagata": "몬테디오 야마가타",
  "Blaublitz Akita": "블라우블리츠 아키타",
  "Akita": "블라우블리츠 아키타",

  // ─── AFC 챔피언스리그 보강 (지시안 한국 미디어 표기) ───
  "Al-Hilal Saudi FC": "알 힐랄",
  "Al-Hilal FC": "알 힐랄",
  "Al-Hilal SFC": "알 힐랄",
  "Al Hilal SFC": "알 힐랄",
  "Al-Hilal Saudi Arabia": "알 힐랄",
  "Al-Nassr FC": "알 나스르",
  "Al Nassr FC": "알 나스르",
  "Al-Nassr Saudi": "알 나스르",
  "Al-Ittihad Club": "알 이티하드",
  "Al-Ittihad FC": "알 이티하드",
  "Al-Ittihad Saudi": "알 이티하드",
  "Al-Ahli Saudi FC": "알 아흘리",
  "Al-Ahli Jeddah": "알 아흘리",
  "Al Ain": "알 아인",
  "Al-Ain": "알 아인",
  "Al Ain FC": "알 아인",
  "Shanghai Shenhua FC": "상하이 션화",
  "Shanghai Haigang": "상하이 하이강",
  "Guangzhou Evergrande": "광저우 헝다",
  "Guangzhou FC": "광저우 헝다",
  "Al Wahda": "알 와다",
  "Al-Wahda": "알 와다",
  "Persepolis": "페르세폴리스",
  "Persepolis FC": "페르세폴리스",
  "Al Duhail": "알 두하일",
  "Al-Duhail": "알 두하일",
  "Al Duhail SC": "알 두하일",

  // ─── 사우디 프로 리그 (SAUDI_PL) 통용 표기 ───
  // 한국 미디어 통용: 알 힐랄 / 알 나스르 / 알 이티하드 / 알 아흘리 / 알 셰바브 / 알 파테 / 알 타아원 / 알 라이드 / 알 칼리지 / 알 카드시아 / 알 와다 / 담맘 알 이티파크
  "Al-Shabab Riyadh": "알 셰바브",
  "Al Shabab Riyadh": "알 셰바브",
  "Al-Shabab FC": "알 셰바브",
  "Al-Fateh SC": "알 파테",
  "Al Fateh SC": "알 파테",
  "Al-Taawoun FC": "알 타아원",
  "Al Taawoun FC": "알 타아원",
  "Al-Raed": "알 라이드",
  "Al Raed": "알 라이드",
  "Al-Raed Club": "알 라이드",
  "Al Khaleej Saihat": "알 칼리지",
  "Al-Khaleej Saihat": "알 칼리지",
  "Al Qadsiah FC": "알 카드시아",
  "Al-Qadsiah FC": "알 카드시아",
  "Al-Qadsiah Al-Khubar": "알 카드시아",
  "Al Wahda FC": "알 와다",
  "Ettifaq": "담맘 알 이티파크",
  "Ettifaq FC": "담맘 알 이티파크",
  "Al-Ittifaq": "담맘 알 이티파크",
  "Al Ittifaq": "담맘 알 이티파크",
  "Al Ettifaq Dammam": "담맘 알 이티파크",

  // ─── 중국 슈퍼리그 (CSL) 한국 미디어 통용 ───
  "Shanghai SIPG FC": "상하이 하이강",
  "Shanghai Shenhua F.C.": "상하이 션화",
  "Shandong Luneng": "산둥 타이산",
  "Shandong Taishan FC": "산둥 타이산",
  "Beijing Guoan FC": "베이징 궈안",
  "Chengdu Better City": "청두 룽청",
  "Wuhan Three Towns FC": "우한 싼전",
  "Tianjin Jinmen Tiger FC": "톈진 진먼후",
  "Tianjin Jinmenhu": "톈진 진먼후",
  "Qingdao Hainiu FC": "칭다오 시윤",
  "Qingdao West Coast FC": "칭다오 시윤",

  // ─── 호주 A-리그 (A_LEAGUE) 보강 ───
  "Melbourne City FC": "멜버른 시티",
  "Sydney": "시드니 FC",
  "Melbourne Victory FC": "멜버른 빅토리",
  "Central Coast Mariners FC": "센트럴 코스트 매리너스",
  "Wellington Phoenix FC": "웰링턴 피닉스",
  "Macarthur": "매카서 FC",
  "Western Sydney": "웨스턴 시드니 원더러스",
  "Adelaide": "애들레이드 유나이티드",
  "Brisbane": "브리즈번 로어",
  "Perth": "퍼스 글로리",
  "Newcastle Jets FC": "뉴캐슬 제츠",

  // ─── 네덜란드 에레디비시 (EREDIVISIE) 통용 표기 (PSV 에인트호번 / 아약스 등) ───
  "PSV Eindhoven FC": "PSV 에인트호번",
  "AFC Ajax": "아약스",
  "Ajax Amsterdam": "아약스",
  "Feyenoord Rotterdam": "페예노르트",
  "FC Twente Enschede": "FC 트벤터",
  "Twente Enschede": "FC 트벤터",
  "Vitesse Arnhem": "비테세",
  "Sparta": "스파르타 로테르담",
  "RKC": "RKC 발베이크",

  // ─── 포르투갈 프리메이라 리가 (PRIMEIRA_LIGA) 통용 표기 ───
  "Sporting": "스포르팅 CP",
  "Sporting CP Lisbon": "스포르팅 CP",
  "SL Benfica Lisbon": "벤피카",
  "FC Porto Porto": "FC 포르투",
  "Porto FC": "FC 포르투",
  "SC Braga Braga": "SC 브라가",
  "Vitória SC": "비토리아 SC",
  "Vitoria Guimaraes SC": "비토리아 SC",
  "Vitoria SC Guimaraes": "비토리아 SC",
  "Moreirense FC": "모레이렌세",
  "Casa Pia AC": "카사 피아",
  "Boavista FC": "보아비스타",
  "FC Famalicão": "파말리캉",
  "Famalicão": "파말리캉",
  "GD Estoril Praia": "에스토릴",
  "Estoril Praia": "에스토릴",
  "Rio Ave FC": "히우 아브",
  "FC Arouca": "아루카",

  // ─── 브라질 세리에 A (BRASILEIRAO) 한국 미디어 통용 ───
  "Botafogo FR": "보타포구",
  "SE Palmeiras": "팔메이라스",
  "Flamengo RJ": "플라멩구",
  "CR Flamengo": "플라멩구",
  "Fluminense FC": "플루미네시",
  "São Paulo FC": "상파울루",
  "Sao Paulo FC": "상파울루",
  "Internacional RS": "인테르나시오나우",
  "SC Internacional": "인테르나시오나우",
  "Gremio FBPA": "그레미우",
  "Grêmio FBPA": "그레미우",
  "Clube Atlético Mineiro": "아틀레치쿠 미네이루",
  "Atletico Mineiro": "아틀레치쿠 미네이루",
  "Corinthians SP": "코린치앙스",
  "SC Corinthians Paulista": "코린치앙스",
  "Corinthians Paulista": "코린치앙스",
  "Cruzeiro EC": "크루제이루",
  "Vasco": "바스쿠 다 가마",
  "CR Vasco da Gama": "바스쿠 다 가마",
  "Santos FC": "산투스",

  // ===== 신규 누락 보강 (2026-05 사용자 보고) =====
  // LaLiga / LaLiga 2 — 액센트 변형 + 승강 팀
  "Alavés": "알라베스",
  "Alaves": "알라베스",
  "Deportivo Alavés": "알라베스",
  "Deportivo Alaves": "알라베스",
  "Sporting Gijon": "스포르팅 히혼",
  "Sporting Gijón": "스포르팅 히혼",
  "Sporting de Gijón": "스포르팅 히혼",
  "Real Sporting": "스포르팅 히혼",
  "Zaragoza": "사라고사",
  "Real Zaragoza": "사라고사",

  // 쉬페르 리그 (터키)
  "Kocaelispor": "코자엘리스포르",
  "Gençlerbirliği": "겐체르비를리이",
  "Gençlerbirliği S.K.": "겐체르비를리이",
  "Genclerbirligi": "겐체르비를리이",
  "Eyüpspor": "에위프스포르",

  // Serie B (이탈리아 2부)
  "Palermo": "팔레르모",
  "Palermo FC": "팔레르모",
  "Catanzaro": "카탄차로",
  "US Catanzaro": "카탄차로",

  // Brasileirao 변형 / 누락
  "Atletico Paranaense": "아틀레치쿠 파라나엔시",
  "Club Athletico Paranaense": "아틀레치쿠 파라나엔시",
  "Chapecoense": "샤페코엔시",
  "Chapecoense-sc": "샤페코엔시",
  "Associação Chapecoense de Futebol": "샤페코엔시",
  "Remo": "헤모",
  "Clube do Remo": "헤모",

  // Liga MX 변형 (기존 매핑에 alias 추가)
  "CF Pachuca": "파추카",
  "Club Pachuca": "파추카",
  "U.N.A.M. - Pumas": "푸마스",
  "UNAM Pumas": "푸마스",
  "Club Universidad Nacional": "푸마스",
  "América": "클루브 아메리카",
  "CF Monterrey": "몬테레이",
  "Deportivo Toluca": "톨루카",
  "Club Tijuana": "티후아나",
  "Atlas FC": "아틀라스",
  "Club León": "레온",
  "Club Necaxa": "네카사",
  "Mazatlan FC": "마사틀란",
  "Club Puebla": "푸에블라",
  "Juárez": "후아레스",

  // ===== Serie B (이탈리아 2부) — 2025-26 =====
  // Palermo / Catanzaro / Sampdoria / Sassuolo / Cremonese / Bari / Parma / Pisa /
  // Venezia / Bologna / Sudtirol / Mirandes 등은 이미 등록됨 (skip)
  "Sampdoria": "삼프도리아",
  "UC Sampdoria": "삼프도리아",
  "Brescia": "브레시아",
  "Brescia Calcio": "브레시아",
  "Cesena": "체세나",
  "Cesena FC": "체세나",
  "Cittadella": "치타델라",
  "AS Cittadella": "치타델라",
  "Cosenza": "코센차",
  "Cosenza Calcio": "코센차",
  "Frosinone": "프로시노네",
  "Frosinone Calcio": "프로시노네",
  "Lecco": "레코",
  "Calcio Lecco 1912": "레코",
  "Mantova": "만토바",
  "Mantova 1911": "만토바",
  "Modena": "모데나",
  "Modena FC": "모데나",
  "Reggiana": "레지아나",
  "AC Reggiana": "레지아나",
  "AC Reggiana 1919": "레지아나",
  "Salernitana": "살레르니타나",
  "US Salernitana 1919": "살레르니타나",
  "Spezia": "스페치아",
  "Spezia Calcio": "스페치아",
  "FC Südtirol": "쥐트티롤",
  "Ternana": "테르나나",
  "Ternana Calcio": "테르나나",
  "Carrarese": "카라레세",
  "Carrarese Calcio": "카라레세",
  "Juve Stabia": "유베 스타비아",
  "SS Juve Stabia": "유베 스타비아",
  "Avellino": "아벨리노",
  "US Avellino 1912": "아벨리노",
  "Padova": "파도바",
  "Calcio Padova": "파도바",

  // ===== LaLiga 2 (스페인 2부) — 2025-26 =====
  // Sporting Gijon / Zaragoza / Levante / Oviedo / Elche / Real Sociedad B / Mirandes 는 이미 등록됨 (skip)
  "Albacete": "알바세테",
  "Albacete Balompié": "알바세테",
  "Albacete Balompie": "알바세테",
  "Almería": "알메리아",
  "Almeria": "알메리아",
  "UD Almería": "알메리아",
  "UD Almeria": "알메리아",
  "Burgos": "부르고스",
  "Burgos CF": "부르고스",
  "Cádiz": "카디스",
  "Cadiz": "카디스",
  "Cádiz CF": "카디스",
  "Cadiz CF": "카디스",
  "Cartagena": "카르타헤나",
  "FC Cartagena": "카르타헤나",
  "Castellón": "카스테욘",
  "Castellon": "카스테욘",
  "CD Castellón": "카스테욘",
  "CD Castellon": "카스테욘",
  "Córdoba": "코르도바",
  "Cordoba": "코르도바",
  "Córdoba CF": "코르도바",
  "Cordoba CF": "코르도바",
  "Deportivo": "데포르티보 라코루냐",
  "Deportivo La Coruña": "데포르티보 라코루냐",
  "Deportivo La Coruna": "데포르티보 라코루냐",
  "RC Deportivo": "데포르티보 라코루냐",
  "RC Deportivo La Coruña": "데포르티보 라코루냐",
  "Eibar": "에이바르",
  "SD Eibar": "에이바르",
  "Eldense": "엘덴세",
  "CD Eldense": "엘덴세",
  "Granada": "그라나다",
  "Granada CF": "그라나다",
  "Huesca": "우에스카",
  "SD Huesca": "우에스카",
  "Málaga": "말라가",
  "Malaga": "말라가",
  "Málaga CF": "말라가",
  "Malaga CF": "말라가",
  "Mirandés": "미란데스",
  "CD Mirandés": "미란데스",
  "Racing Santander": "라싱 산탄데르",
  "Racing de Santander": "라싱 산탄데르",
  "Real Racing Club": "라싱 산탄데르",
  "Racing Ferrol": "라싱 페롤",
  "Racing de Ferrol": "라싱 페롤",
  "Racing Club Ferrol": "라싱 페롤",
  "Tenerife": "테네리페",
  "CD Tenerife": "테네리페",
  "Villarreal B": "비야레알 B",
  "Andorra": "안도라",
  "FC Andorra": "안도라",
  // ─── 쉬페르 리그 (터키 1부) 2025-26 — alias 보강 + 누락 팀 ───
  "Galatasaray SK": "갈라타사라이",
  "Galatasaray AŞ": "갈라타사라이",
  "Galatasaray Istanbul": "갈라타사라이",
  "Fenerbahce SK": "페네르바체",
  "Fenerbahçe SK": "페네르바체",
  "Fenerbahce Istanbul": "페네르바체",
  "Besiktas JK": "베식타스",
  "Beşiktaş JK": "베식타스",
  "Besiktas Istanbul": "베식타스",
  "Trabzonspor AS": "트라브존스포르",
  "Trabzonspor A.Ş.": "트라브존스포르",
  "Istanbul Basaksehir": "바샤크셰히르",
  "Istanbul Başakşehir FK": "바샤크셰히르",
  "İstanbul Başakşehir": "바샤크셰히르",
  "Basaksehir FK": "바샤크셰히르",
  "Konyaspor Kulübü": "코냐스포르",
  "Ittifak Holding Konyaspor": "코냐스포르",
  "Antalyaspor Kulübü": "안탈리아스포르",
  "FT Antalyaspor": "안탈리아스포르",
  "Alanyaspor Kulübü": "알라니아스포르",
  "Corendon Alanyaspor": "알라니아스포르",
  "Kasimpasa SK": "카심파샤",
  "Kasımpaşa SK": "카심파샤",
  "Gaziantep Futbol Kulübü": "가지안테프",
  "Gaziantep Büyükşehir Belediyespor": "가지안테프",
  "Rizespor Kulübü": "리제스포르",
  "Samsunspor Kulübü": "삼순스포르",
  "Yilport Samsunspor": "삼순스포르",
  "Hatayspor AS": "하타이스포르",
  "Atakas Hatayspor": "하타이스포르",
  "Adana Demirspor Kulübü": "아다나 데미르스포르",
  "Yukatel Adana Demirspor": "아다나 데미르스포르",
  "Sivasspor Kulübü": "시바스스포르",
  "Demir Grup Sivasspor": "시바스스포르",
  "Kayserispor Kulübü": "카이세리스포르",
  "Mondihome Kayserispor": "카이세리스포르",
  "Bodrum FK": "보드룸스포르",
  "Bodrumspor Kulübü": "보드룸스포르",
  "Pendikspor Kulübü": "펜디크스포르",
  "Siltaş Yapı Pendikspor": "펜디크스포르",
  "Eyupspor Kulübü": "에이윱스포르",
  "Eyüpspor Kulübü": "에이윱스포르",
  "Ikas Eyupspor": "에이윱스포르",
  "Goztepe SK": "괴즈테페",
  "Göztepe SK": "괴즈테페",
  "Goztepe Izmir": "괴즈테페",
  "Kocaelispor Kulübü": "코자엘리스포르",
  "MKE Ankaragücü": "앙카라귀쥐",
  "Ankaragucu": "앙카라귀쥐",
  "Ankaragücü": "앙카라귀쥐",
  "Genclerbirligi SK": "겐체르비를리이",
  "Gençlerbirliği SK": "겐체르비를리이",

  // ─── 그리스 슈퍼리그 (1부) 2025-26 — alias 보강 + 누락 팀 ───
  "Olympiakos": "올림피아코스",
  "Olympiakos CFP": "올림피아코스",
  "Olympiacos FC": "올림피아코스",
  "Olympiacos Piraeus": "올림피아코스",
  "Olympiakos Pireus": "올림피아코스",
  "Panathinaikos FC": "파나티나이코스",
  "Panathinaikos AO": "파나티나이코스",
  "Panathinaikos Athens": "파나티나이코스",
  "PAOK FC": "PAOK",
  "PAOK Thessaloniki": "PAOK",
  "PAOK Saloniki": "PAOK",
  "AEK": "AEK 아테네",
  "AEK FC": "AEK 아테네",
  "AEK Athens 1924": "AEK 아테네",
  "AEK Athen": "AEK 아테네",
  "Aris FC": "아리스",
  "Aris Saloniki": "아리스",
  "Aris Salonika": "아리스",
  "OFI Crete FC": "OFI 크레타",
  "OFI Kreta": "OFI 크레타",
  "OFI Heraklion": "OFI 크레타",
  "Atromitos Athinon": "아트로미토스",
  "Atromitos Athens": "아트로미토스",
  "PAS Lamia": "라미아",
  "PAS Lamia 1964": "라미아",
  "Volos": "볼로스",
  "NPS Volos": "볼로스",
  "Volos NFC": "볼로스",
  "Levadiakos FC": "레바디아코스",
  "PAS Levadiakos": "레바디아코스",
  "Panetolikos": "파나이톨리코스",
  "Panetolikos GFS": "파나이톨리코스",
  "Panaitolikos GFS": "파나이톨리코스",
  "Kifisia": "키피시아",
  "Kifisia FC": "키피시아",
  "AE Kifisia": "키피시아",
  "Panserraikos FC": "판세라이코스",
  "Panserraikos": "판세라이코스",
  "PAE Panserraikos": "판세라이코스",
  "Asteras Tripoli": "아스테라스 트리폴리스",
  "Asteras Aktor": "아스테라스 트리폴리스",
  "Asteras Tripolis FC": "아스테라스 트리폴리스",

  // ─── 주피러 프로 리그 (벨기에 1부) 2025-26 — alias 보강 + 누락 팀 ───
  "Club Brugge KV NV": "클럽 브뤼헤",
  "FC Bruges": "클럽 브뤼헤",
  "Brugge": "클럽 브뤼헤",
  "Royale Union Saint-Gilloise": "위니옹 SG",
  "Union SG": "위니옹 SG",
  "USG": "위니옹 SG",
  "Royal Sporting Club Anderlecht": "안더레흐트",
  "Anderlecht RSC": "안더레흐트",
  "RC Genk": "헹크",
  "Racing Genk": "헹크",
  "Standard de Liège": "스탕다르 리에주",
  "Standard de Liege": "스탕다르 리에주",
  "R. Standard de Liège": "스탕다르 리에주",
  "Royal Antwerp FC": "안트베르펜",
  "Antwerp FC": "안트베르펜",
  "K Beerschot VA": "베르스호트",
  "Beerschot VA": "베르스호트",
  "K. Beerschot V.A.": "베르스호트",
  "KAA Ghent": "헨트",
  "KAA Gent NV": "헨트",
  "RSC Charleroi": "샤를루아",
  "Sporting Charleroi": "샤를루아",
  "Royal Charleroi SC": "샤를루아",
  "Oud-Heverlee Leuven": "OH 뢰번",
  "OH Leuven NV": "OH 뢰번",
  "Cercle Brugge KSV": "세르클 브뤼헤",
  "Cercle Bruges": "세르클 브뤼헤",
  "Yellow-Red KV Mechelen": "메헬렌",
  "KV Mechelen NV": "메헬렌",
  "K.V. Mechelen": "메헬렌",
  "KVC Westerlo": "베스털로",
  "K.V.C. Westerlo": "베스털로",
  "Sint-Truiden": "신트트라위던",
  "Sint-Truidense VV": "신트트라위던",
  "STVV": "신트트라위던",
  "K Sint-Truidense VV": "신트트라위던",
  "KV Kortrijk": "코르트레이크",
  "K.V. Kortrijk": "코르트레이크",
  "Royal Excel Mouscron": "무스크롱",
  "RWD Molenbeek": "몰렌베이크",
  "RWDM": "몰렌베이크",
  "Daring Club Brussels": "몰렌베이크",
  "Eupen": "외펜",
  "KAS Eupen": "외펜",
  "K.A.S. Eupen": "외펜",
  "FCV Dender EH": "덴더르",
  "Dender EH": "덴더르",
  "K Beerschot": "베르스호트",
  "Patro Eisden": "파트로 에이스던",
  "K. Patro Eisden Maasmechelen": "파트로 에이스던",
  // Liga MX 추가 변형 alias (B3 2025-26 보강)
  "Pumas": "푸마스",
  "Universidad Nacional": "푸마스",
  "Club Universidad": "푸마스",
  "Club Atlas": "아틀라스",
  "Atlas Guadalajara": "아틀라스",
  "CD Cruz Azul": "크루스 아술",
  "Club Cruz Azul": "크루스 아술",
  "Cruz Azul FC": "크루스 아술",
  "Rayados": "몬테레이",
  "Rayados de Monterrey": "몬테레이",
  "Club de Fútbol Monterrey": "몬테레이",
  "Club Toluca": "톨루카",
  "Toluca FC": "톨루카",
  "Diablos Rojos": "톨루카",
  "Xolos": "티후아나",
  "Club Xolos": "티후아나",
  "Xolos de Tijuana": "티후아나",
  "Club Santos": "산토스 라구나",
  "Club Santos Laguna": "산토스 라구나",
  "Guerreros": "산토스 라구나",
  "UANL Tigres": "티그레스",
  "Tigres de la UANL": "티그레스",
  "Tigres FC": "티그레스",
  "CF León": "레온",
  "CF Leon": "레온",
  "Rayos del Necaxa": "네카사",
  "Mazatlán FC": "마사틀란",
  "Cañoneros": "마사틀란",
  "Club de Fútbol Puebla": "푸에블라",
  "Bravos de Juárez": "FC 후아레스",
  "Querétaro FC": "케레타로",
  "Queretaro FC": "케레타로",
  "Gallos Blancos": "케레타로",
  "Chivas de Guadalajara": "치바스",
  "Club Guadalajara": "치바스",
  "C.D. Guadalajara": "치바스",
  "Atlético de San Luis": "아틀레티코 산 루이스",
  "Atletico de San Luis": "아틀레티코 산 루이스",
  "San Luis": "아틀레티코 산 루이스",
  "Tuzos": "파추카",
  "CF Pumas": "푸마스",

  // 잉글랜드 챔피언십 (2025-26 시즌) — B3 보강
  "Sheffield United": "셰필드 유나이티드",
  "Sheffield United FC": "셰필드 유나이티드",
  "Sheffield Utd": "셰필드 유나이티드",
  "Sheffield Wednesday": "셰필드 웬즈데이",
  "Sheffield Wednesday FC": "셰필드 웬즈데이",
  "Sheffield Wed": "셰필드 웬즈데이",
  "Norwich City": "노리치 시티",
  "Norwich City FC": "노리치 시티",
  "Norwich": "노리치 시티",
  "Watford": "왓퍼드",
  "Watford FC": "왓퍼드",
  "Middlesbrough": "미들즈브러",
  "Middlesbrough FC": "미들즈브러",
  "Boro": "미들즈브러",
  "West Bromwich Albion": "웨스트 브롬",
  "West Bromwich": "웨스트 브롬",
  "West Brom": "웨스트 브롬",
  "WBA": "웨스트 브롬",
  "West Bromwich Albion FC": "웨스트 브롬",
  "Hull City": "헐 시티",
  "Hull City AFC": "헐 시티",
  "Hull": "헐 시티",
  "Coventry City": "코번트리 시티",
  "Coventry City FC": "코번트리 시티",
  "Coventry": "코번트리 시티",
  "Cardiff City": "카디프 시티",
  "Cardiff City FC": "카디프 시티",
  "Cardiff": "카디프 시티",
  "Swansea City": "스완지 시티",
  "Swansea City AFC": "스완지 시티",
  "Swansea": "스완지 시티",
  "Preston North End": "프레스턴",
  "Preston North End FC": "프레스턴",
  "Preston": "프레스턴",
  "PNE": "프레스턴",
  "Bristol City": "브리스톨 시티",
  "Bristol City FC": "브리스톨 시티",
  "Millwall": "밀월",
  "Millwall FC": "밀월",
  "Queens Park Rangers": "QPR",
  "QPR": "QPR",
  "Queens Park Rangers FC": "QPR",
  "Blackburn Rovers": "블랙번 로버스",
  "Blackburn": "블랙번 로버스",
  "Blackburn Rovers FC": "블랙번 로버스",
  "Plymouth Argyle": "플리머스 아가일",
  "Plymouth": "플리머스 아가일",
  "Plymouth Argyle FC": "플리머스 아가일",
  "Portsmouth": "포츠머스",
  "Portsmouth FC": "포츠머스",
  "Pompey": "포츠머스",
  "Stoke City": "스토크 시티",
  "Stoke City FC": "스토크 시티",
  "Stoke": "스토크 시티",
  "Birmingham City": "버밍엄 시티",
  "Birmingham City FC": "버밍엄 시티",
  "Birmingham": "버밍엄 시티",
  "Derby County": "더비 카운티",
  "Derby County FC": "더비 카운티",
  "Derby": "더비 카운티",
  "Oxford United": "옥스퍼드 유나이티드",
  "Oxford United FC": "옥스퍼드 유나이티드",
  "Oxford Utd": "옥스퍼드 유나이티드",
  "Luton Town": "루턴 타운",
  "Luton Town FC": "루턴 타운",
  "Luton": "루턴 타운",
  "Leeds Utd": "리즈 유나이티드",
  "Leeds United AFC": "리즈 유나이티드",

  // ===== AFC CL Two 2025-26 =====
  // 동남아·중앙아시아·인도 — 기존 매핑 (Al-Hilal·Al-Nassr·울산·전북·요코하마 F. 마리노스·
  // 가와사키 프론탈레·포항·부리람) 외 ACL Two 만 출전하는 클럽 위주.
  // 기존 클럽 응답 변형 alias 보강:
  "Al Hilal Saudi": "알 힐랄",
  "Al Hilal Riyadh": "알 힐랄",
  "Al Nassr Riyadh": "알 나스르",
  "Ulsan HD FC AFC": "울산 HD",
  "Jeonbuk Hyundai FC": "전북 현대 모터스",
  "Pohang Steelers FC": "포항 스틸러스",
  "Yokohama F.Marinos": "요코하마 F. 마리노스",
  "Yokohama F-Marinos": "요코하마 F. 마리노스",
  "Kawasaki Frontale AFC": "가와사키 프론탈레",
  "Buriram United FC": "부리람 유나이티드",
  "Buriram": "부리람 유나이티드",
  // 인도 — Indian Super League 강팀, ACL Two 본선 진출.
  "Mohun Bagan Super Giant": "모훈 바간",
  "Mohun Bagan SG": "모훈 바간",
  "Mohun Bagan": "모훈 바간",
  "ATK Mohun Bagan": "모훈 바간",
  "FC Goa": "FC 고아",
  "Goa": "FC 고아",
  "Mumbai City": "뭄바이 시티",
  "Mumbai City FC": "뭄바이 시티",
  // 태국 — ACL Two 무대 단골.
  "BG Pathum United": "BG 빠툼",
  "BG Pathum": "BG 빠툼",
  "BG Pathum United FC": "BG 빠툼",
  // 인도네시아 — Liga 1 챔피언/AFC 출전 클럽.
  "Persib Bandung": "페르시브 반둥",
  "Persib": "페르시브 반둥",
  "PSM Makassar": "PSM 마카사르",
  "PSM": "PSM 마카사르",
  "Bali United": "발리 유나이티드",
  "Bali United FC": "발리 유나이티드",
  "Bali United Pusam": "발리 유나이티드",
  // 싱가포르·말레이시아.
  "Lion City Sailors": "라이온 시티 세일러스",
  "Lion City Sailors FC": "라이온 시티 세일러스",
  "Tampines Rovers": "탬피니스 로버스",
  "Tampines Rovers FC": "탬피니스 로버스",
  "Kuala Lumpur City": "쿠알라룸푸르 시티",
  "Kuala Lumpur City FC": "쿠알라룸푸르 시티",
  "Kuala Lumpur": "쿠알라룸푸르 시티",
  "Johor Darul Ta'zim": "조호르 다룰 타지름",
  "Johor Darul Tazim": "조호르 다룰 타지름",
  "Johor Darul Ta'zim FC": "조호르 다룰 타지름",
  "JDT": "조호르 다룰 타지름",
  // 방글라데시.
  "Sheikh Russel KC": "셰이크 루셀 KC",
  "Sheikh Russel Krira Chakra": "셰이크 루셀 KC",
  // 중앙아시아.
  "Pakhtakor Tashkent": "파흐타코르 타슈켄트",
  "Pakhtakor": "파흐타코르 타슈켄트",
  "FC Pakhtakor": "파흐타코르 타슈켄트",
  "Nasaf Qarshi": "나사프 카르시",
  "Nasaf": "나사프 카르시",
  "FC Nasaf": "나사프 카르시",
  "Istiklol": "이스티클롤",
  "FC Istiklol": "이스티클롤",
  "FK Istiklol": "이스티클롤",
  "Istiklol Dushanbe": "이스티클롤",
  "Altyn Asyr": "알튼 아스르",
  "FC Altyn Asyr": "알튼 아스르",

  // ===== AFC U23 아시안컵 =====
  // 23세 이하 국가대표 — AFC U23 응답에 다양한 표기로 등장.
  "South Korea U23": "한국 U-23",
  "South Korea U-23": "한국 U-23",
  "Korea Republic U23": "한국 U-23",
  "Korea Republic U-23": "한국 U-23",
  "Korea U23": "한국 U-23",
  "Japan U23": "일본 U-23",
  "Japan U-23": "일본 U-23",
  "China U23": "중국 U-23",
  "China PR U23": "중국 U-23",
  "China U-23": "중국 U-23",
  "Iraq U23": "이라크 U-23",
  "Iraq U-23": "이라크 U-23",
  "Uzbekistan U23": "우즈베키스탄 U-23",
  "Uzbekistan U-23": "우즈베키스탄 U-23",
  "Saudi Arabia U23": "사우디 U-23",
  "Saudi Arabia U-23": "사우디 U-23",
  "Qatar U23": "카타르 U-23",
  "Qatar U-23": "카타르 U-23",
  "Australia U23": "호주 U-23",
  "Australia U-23": "호주 U-23",
  "Indonesia U23": "인도네시아 U-23",
  "Indonesia U-23": "인도네시아 U-23",
  "Vietnam U23": "베트남 U-23",
  "Vietnam U-23": "베트남 U-23",
  "Thailand U23": "태국 U-23",
  "Thailand U-23": "태국 U-23",
  "Malaysia U23": "말레이시아 U-23",
  "Malaysia U-23": "말레이시아 U-23",
  "Jordan U23": "요르단 U-23",
  "Jordan U-23": "요르단 U-23",
  "UAE U23": "UAE U-23",
  "UAE U-23": "UAE U-23",
  "United Arab Emirates U23": "UAE U-23",
  "Tajikistan U23": "타지키스탄 U-23",
  "Tajikistan U-23": "타지키스탄 U-23",
  "Kyrgyzstan U23": "키르기스스탄 U-23",
  "Kyrgyzstan U-23": "키르기스스탄 U-23",
  "Iran U23": "이란 U-23",
  "Iran U-23": "이란 U-23",
  "Bahrain U23": "바레인 U-23",
  "Bahrain U-23": "바레인 U-23",

  // ===== 코파 리베르타도레스 / 수다메리카나 =====
  // 브라질 세히 A (보타포구·플라멩구·팔메이라스 등) 는 이미 매핑됨.
  // 아르헨티나·칠레·우루과이·콜롬비아·에콰도르·파라과이·페루·볼리비아 추가.
  // ─── 아르헨티나 프리메라 디비전 ───
  "River Plate": "리버 플레이트",
  "Club Atlético River Plate": "리버 플레이트",
  "CA River Plate": "리버 플레이트",
  "Boca Juniors": "보카 주니어스",
  "Club Atlético Boca Juniors": "보카 주니어스",
  "CA Boca Juniors": "보카 주니어스",
  "Racing Club": "라싱 클루브",
  "Racing Club de Avellaneda": "라싱 클루브",
  "Independiente": "인데펜디엔테",
  "Club Atlético Independiente": "인데펜디엔테",
  "CA Independiente": "인데펜디엔테",
  "San Lorenzo": "산 로렌소",
  "San Lorenzo de Almagro": "산 로렌소",
  "CA San Lorenzo": "산 로렌소",
  "Estudiantes": "에스투디안테스",
  "Estudiantes de La Plata": "에스투디안테스",
  "Estudiantes La Plata": "에스투디안테스",
  "Vélez Sársfield": "벨레스 사르스피엘드",
  "Velez Sarsfield": "벨레스 사르스피엘드",
  "Vélez": "벨레스 사르스피엘드",
  "Velez": "벨레스 사르스피엘드",
  "Club Atlético Vélez Sársfield": "벨레스 사르스피엘드",
  "Talleres": "타예레스",
  "Talleres de Córdoba": "타예레스",
  "Talleres Cordoba": "타예레스",
  "CA Talleres": "타예레스",
  "Newell's Old Boys": "뉴웰스 올드 보이스",
  "Newells Old Boys": "뉴웰스 올드 보이스",
  "Newell's": "뉴웰스 올드 보이스",
  "Rosario Central": "로사리오 센트랄",
  "CA Rosario Central": "로사리오 센트랄",
  "Defensa y Justicia": "데펜사 이 후스티시아",
  "Defensa": "데펜사 이 후스티시아",
  "Lanús": "라누스",
  "Lanus": "라누스",
  "Club Atlético Lanús": "라누스",
  "CA Lanus": "라누스",
  // ─── 칠레 프리메라 디비전 ───
  "Colo-Colo": "콜로콜로",
  "Colo Colo": "콜로콜로",
  "CSD Colo-Colo": "콜로콜로",
  "Universidad de Chile": "우니베르시닫 데 칠레",
  "Club Universidad de Chile": "우니베르시닫 데 칠레",
  "U. de Chile": "우니베르시닫 데 칠레",
  "Universidad Católica": "우니베르시닫 카톨리카",
  "Universidad Catolica": "우니베르시닫 카톨리카",
  "Club Deportivo Universidad Católica": "우니베르시닫 카톨리카",
  "CD Universidad Catolica": "우니베르시닫 카톨리카",
  // ─── 우루과이 ───
  "Peñarol": "페냐롤",
  "Penarol": "페냐롤",
  "Club Atlético Peñarol": "페냐롤",
  "CA Peñarol": "페냐롤",
  "Nacional Montevideo": "나시오날 (우루과이)",
  "Club Nacional de Football": "나시오날 (우루과이)",
  "Nacional (URU)": "나시오날 (우루과이)",
  "Liverpool FC (Uruguay)": "리버풀 FC 우루과이",
  "Liverpool Montevideo": "리버풀 FC 우루과이",
  "Liverpool FC Montevideo": "리버풀 FC 우루과이",
  // ─── 콜롬비아 ───
  "Atlético Nacional": "아틀레티코 나시오날",
  "Atletico Nacional": "아틀레티코 나시오날",
  "Club Atlético Nacional": "아틀레티코 나시오날",
  "Atletico Nacional Medellin": "아틀레티코 나시오날",
  "Millonarios": "미요나리오스",
  "Millonarios FC": "미요나리오스",
  "Junior": "후니오르",
  "Junior FC": "후니오르",
  "Atlético Junior": "후니오르",
  "Atletico Junior": "후니오르",
  "Junior Barranquilla": "후니오르",
  "América de Cali": "아메리카 데 칼리",
  "America de Cali": "아메리카 데 칼리",
  // ─── 에콰도르 ───
  "LDU Quito": "LDU 키토",
  "Liga de Quito": "LDU 키토",
  "Liga Deportiva Universitaria": "LDU 키토",
  "LDU": "LDU 키토",
  "Independiente del Valle": "인데펜디엔테 델 바예",
  "Independiente Del Valle": "인데펜디엔테 델 바예",
  "Barcelona SC": "바르셀로나 SC (에콰도르)",
  "Barcelona Sporting Club": "바르셀로나 SC (에콰도르)",
  "Barcelona SC Guayaquil": "바르셀로나 SC (에콰도르)",
  // ─── 파라과이 ───
  "Olimpia": "올림피아 (파라과이)",
  "Club Olimpia": "올림피아 (파라과이)",
  "Olimpia Asunción": "올림피아 (파라과이)",
  "Olimpia Asuncion": "올림피아 (파라과이)",
  "Cerro Porteño": "세로 포르테뇨",
  "Cerro Porteno": "세로 포르테뇨",
  "Club Cerro Porteño": "세로 포르테뇨",
  // ─── 페루 ───
  "Universitario": "우니베르시타리오",
  "Universitario de Deportes": "우니베르시타리오",
  "Club Universitario de Deportes": "우니베르시타리오",
  "Alianza Lima": "알리안사 리마",
  "Club Alianza Lima": "알리안사 리마",
  // ─── 볼리비아 ───
  "The Strongest": "더 스트롱기스트",
  "Club The Strongest": "더 스트롱기스트",
  "Bolívar": "볼리바르",
  "Bolivar": "볼리바르",
  "Club Bolívar": "볼리바르",
  "Club Bolivar": "볼리바르",
};

// 다양한 표기를 통합하기 위한 lookup helper.
// 1) 정확 매치 → 2) 소문자 매치 → 3) 흔한 접미어 제거 후 매치 → 4) fallback (원본)
const RAW_LOWER: Record<string, string> = Object.fromEntries(
  Object.entries(RAW).map(([k, v]) => [k.toLowerCase(), v]),
);

const STRIP_RE = /\s+(fc|cf|sc|afc|ac|cfc|club|football club)\.?$/i;

export function toKoreanTeamName(name: string | undefined | null): string {
  if (!name) return "";
  const trimmed = name.trim();
  if (RAW[trimmed]) return RAW[trimmed];
  const lower = trimmed.toLowerCase();
  if (RAW_LOWER[lower]) return RAW_LOWER[lower];
  const stripped = trimmed.replace(STRIP_RE, "").trim();
  if (RAW[stripped]) return RAW[stripped];
  const strippedLower = stripped.toLowerCase();
  if (RAW_LOWER[strippedLower]) return RAW_LOWER[strippedLower];
  return trimmed;
}
