// 영문 팀명 → 한글 표시명 매핑.
// 외부 데이터 소스(football-data, ESPN, MLB Stats, NHL API 등)가 영문으로만 응답하므로
// UI 표시 시에만 한글로 변환한다. DB(Team.name)는 원본 영문 그대로 유지.
//
// 매핑 누락 시 toKoreanTeamName 은 원본 영문을 그대로 반환 (fallback).
// 외래어 표기는 국립국어원 표기법 + 한국 스포츠 미디어 관행을 따른다.

const RAW: Record<string, string> = {
  // ─── EPL (2025-26) ───
  "Arsenal": "아스널",
  "Arsenal FC": "아스널",
  "Aston Villa": "아스톤 빌라",
  "Aston Villa FC": "아스톤 빌라",
  "Bournemouth": "본머스",
  "AFC Bournemouth": "본머스",
  "Brentford": "브렌트포드",
  "Brentford FC": "브렌트포드",
  "Brighton & Hove Albion": "브라이턴",
  "Brighton & Hove Albion FC": "브라이턴",
  "Brighton and Hove Albion": "브라이턴",
  "Burnley": "번리",
  "Burnley FC": "번리",
  "Chelsea": "첼시",
  "Chelsea FC": "첼시",
  "Crystal Palace": "크리스털 팰리스",
  "Crystal Palace FC": "크리스털 팰리스",
  "Everton": "에버턴",
  "Everton FC": "에버턴",
  "Fulham": "풀럼",
  "Fulham FC": "풀럼",
  "Ipswich Town": "입스위치",
  "Ipswich Town FC": "입스위치",
  "Leicester City": "레스터 시티",
  "Leicester City FC": "레스터 시티",
  "Leeds United": "리즈 유나이티드",
  "Leeds": "리즈 유나이티드",
  "Leeds United FC": "리즈 유나이티드",
  "Liverpool": "리버풀",
  "Liverpool FC": "리버풀",
  "Manchester City": "맨체스터 시티",
  "Manchester City FC": "맨체스터 시티",
  "Man City": "맨체스터 시티",
  "Manchester United": "맨체스터 유나이티드",
  "Manchester United FC": "맨체스터 유나이티드",
  "Man United": "맨체스터 유나이티드",
  "Newcastle": "뉴캐슬",
  "Newcastle United": "뉴캐슬",
  "Newcastle United FC": "뉴캐슬",
  "Nottingham Forest": "노팅엄 포레스트",
  "Nottingham Forest FC": "노팅엄 포레스트",
  "Nott'm Forest": "노팅엄 포레스트",
  "Southampton": "사우샘프턴",
  "Southampton FC": "사우샘프턴",
  "Sunderland": "선덜랜드",
  "Sunderland AFC": "선덜랜드",
  "Tottenham": "토트넘",
  "Tottenham Hotspur": "토트넘",
  "Tottenham Hotspur FC": "토트넘",
  "Spurs": "토트넘",
  "West Ham": "웨스트햄",
  "West Ham United": "웨스트햄",
  "West Ham United FC": "웨스트햄",
  "Wolverhampton": "울버햄튼",
  "Wolverhampton Wanderers": "울버햄튼",
  "Wolverhampton Wanderers FC": "울버햄튼",
  "Wolves": "울버햄튼",

  // ─── La Liga (2025-26) ───
  "Athletic Bilbao": "아틀레틱 빌바오",
  "Athletic Club": "아틀레틱 빌바오",
  "Atletico Madrid": "아틀레티코 마드리드",
  "Atlético Madrid": "아틀레티코 마드리드",
  "Atletico": "아틀레티코 마드리드",
  "Barcelona": "바르셀로나",
  "FC Barcelona": "바르셀로나",
  "Real Betis": "레알 베티스",
  "Betis": "레알 베티스",
  "Celta Vigo": "셀타 비고",
  "RC Celta": "셀타 비고",
  "Elche": "엘체",
  "Elche CF": "엘체",
  "Espanyol": "에스파뇰",
  "RCD Espanyol": "에스파뇰",
  "Getafe": "헤타페",
  "Getafe CF": "헤타페",
  "Girona": "지로나",
  "Girona FC": "지로나",
  "Levante": "레반테",
  "Levante UD": "레반테",
  "Mallorca": "마요르카",
  "RCD Mallorca": "마요르카",
  "Osasuna": "오사수나",
  "CA Osasuna": "오사수나",
  "Oviedo": "오비에도",
  "Real Oviedo": "오비에도",
  "Rayo Vallecano": "라요 바예카노",
  "Real Madrid": "레알 마드리드",
  "Real Sociedad": "레알 소시에다드",
  "Sevilla": "세비야",
  "Sevilla FC": "세비야",
  "Valencia": "발렌시아",
  "Valencia CF": "발렌시아",
  "Villarreal": "비야레알",
  "Villarreal CF": "비야레알",

  // ─── Bundesliga (2025-26) ───
  "Augsburg": "아우크스부르크",
  "FC Augsburg": "아우크스부르크",
  "Bayer Leverkusen": "레버쿠젠",
  "Leverkusen": "레버쿠젠",
  "Bayern Munich": "바이에른 뮌헨",
  "Bayern München": "바이에른 뮌헨",
  "FC Bayern München": "바이에른 뮌헨",
  "Borussia Dortmund": "도르트문트",
  "Dortmund": "도르트문트",
  "Borussia Mönchengladbach": "묀헨글라트바흐",
  "Borussia Monchengladbach": "묀헨글라트바흐",
  "Mönchengladbach": "묀헨글라트바흐",
  "Eintracht Frankfurt": "프랑크푸르트",
  "Frankfurt": "프랑크푸르트",
  "Freiburg": "프라이부르크",
  "SC Freiburg": "프라이부르크",
  "Hamburger SV": "함부르크",
  "Hamburg": "함부르크",
  "Heidenheim": "하이덴하임",
  "1. FC Heidenheim": "하이덴하임",
  "Hoffenheim": "호펜하임",
  "TSG Hoffenheim": "호펜하임",
  "Holstein Kiel": "킬",
  "1. FC Köln": "쾰른",
  "Köln": "쾰른",
  "FC Köln": "쾰른",
  "Mainz": "마인츠",
  "Mainz 05": "마인츠",
  "1. FSV Mainz 05": "마인츠",
  "RB Leipzig": "RB 라이프치히",
  "Leipzig": "RB 라이프치히",
  "Stuttgart": "슈투트가르트",
  "VfB Stuttgart": "슈투트가르트",
  "Union Berlin": "우니온 베를린",
  "1. FC Union Berlin": "우니온 베를린",
  "Werder Bremen": "베르더 브레멘",
  "SV Werder Bremen": "베르더 브레멘",
  "Wolfsburg": "볼프스부르크",
  "VfL Wolfsburg": "볼프스부르크",
  "St. Pauli": "장크트 파울리",
  "FC St. Pauli": "장크트 파울리",

  // ─── Serie A (2025-26) ───
  "AC Milan": "AC 밀란",
  "Milan": "AC 밀란",
  "Atalanta": "아탈란타",
  "Atalanta BC": "아탈란타",
  "Bologna": "볼로냐",
  "Bologna FC 1909": "볼로냐",
  "Cagliari": "칼리아리",
  "Cagliari Calcio": "칼리아리",
  "Como": "코모",
  "Como 1907": "코모",
  "Empoli": "엠폴리",
  "Empoli FC": "엠폴리",
  "Fiorentina": "피오렌티나",
  "ACF Fiorentina": "피오렌티나",
  "Genoa": "제노아",
  "Genoa CFC": "제노아",
  "Hellas Verona": "베로나",
  "Verona": "베로나",
  "Inter": "인터 밀란",
  "Inter Milan": "인터 밀란",
  "Internazionale": "인터 밀란",
  "FC Internazionale Milano": "인터 밀란",
  "Juventus": "유벤투스",
  "Juventus FC": "유벤투스",
  "Lazio": "라치오",
  "SS Lazio": "라치오",
  "Lecce": "레체",
  "US Lecce": "레체",
  "Monza": "몬차",
  "AC Monza": "몬차",
  "Napoli": "나폴리",
  "SSC Napoli": "나폴리",
  "Parma": "파르마",
  "Parma Calcio 1913": "파르마",
  "Pisa": "피사",
  "Pisa SC": "피사",
  "Roma": "AS 로마",
  "AS Roma": "AS 로마",
  "Sassuolo": "사수올로",
  "US Sassuolo": "사수올로",
  "Torino": "토리노",
  "Torino FC": "토리노",
  "Udinese": "우디네세",
  "Udinese Calcio": "우디네세",
  "Venezia": "베네치아",
  "Venezia FC": "베네치아",
  "Cremonese": "크레모네세",
  "US Cremonese": "크레모네세",

  // ─── Ligue 1 (2025-26) ───
  "Angers": "앙제",
  "Angers SCO": "앙제",
  "Auxerre": "오세르",
  "AJ Auxerre": "오세르",
  "Brest": "브레스트",
  "Stade Brestois 29": "브레스트",
  "Le Havre": "르아브르",
  "Le Havre AC": "르아브르",
  "Lens": "랭스",
  "RC Lens": "랭스",
  "Lille": "릴",
  "LOSC Lille": "릴",
  "Lorient": "로리앙",
  "FC Lorient": "로리앙",
  "Lyon": "리옹",
  "Olympique Lyonnais": "리옹",
  "Marseille": "마르세유",
  "Olympique de Marseille": "마르세유",
  "Olympique Marseille": "마르세유",
  "Metz": "메스",
  "FC Metz": "메스",
  "Monaco": "AS 모나코",
  "AS Monaco": "AS 모나코",
  "Nantes": "낭트",
  "FC Nantes": "낭트",
  "Nice": "니스",
  "OGC Nice": "니스",
  "Paris FC": "파리 FC",
  "Paris Saint-Germain": "파리 생제르맹",
  "Paris Saint Germain": "파리 생제르맹",
  "PSG": "파리 생제르맹",
  "Reims": "랭스 SR",
  "Stade Reims": "랭스 SR",
  "Stade de Reims": "랭스 SR",
  "Rennes": "렌",
  "Stade Rennais": "렌",
  "Stade Rennais FC": "렌",
  "Saint-Étienne": "생테티엔",
  "AS Saint-Étienne": "생테티엔",
  "Saint-Etienne": "생테티엔",
  "Strasbourg": "스트라스부르",
  "RC Strasbourg Alsace": "스트라스부르",
  "Toulouse": "툴루즈",
  "Toulouse FC": "툴루즈",

  // ─── MLS (편의: 도시명 위주 한글, 2026 시즌) ───
  "Atlanta United FC": "애틀랜타 유나이티드",
  "Austin FC": "오스틴 FC",
  "CF Montréal": "CF 몬트리올",
  "Charlotte FC": "샬럿 FC",
  "Chicago Fire FC": "시카고 파이어",
  "Colorado Rapids": "콜로라도 래피즈",
  "Columbus Crew": "콜럼버스 크루",
  "D.C. United": "DC 유나이티드",
  "FC Cincinnati": "FC 신시내티",
  "FC Dallas": "FC 댈러스",
  "Houston Dynamo FC": "휴스턴 다이너모",
  "Inter Miami CF": "인터 마이애미",
  "LA Galaxy": "LA 갤럭시",
  "Los Angeles FC": "LAFC",
  "Minnesota United FC": "미네소타 유나이티드",
  "Nashville SC": "내슈빌 SC",
  "New England Revolution": "뉴잉글랜드 레볼루션",
  "New York City FC": "뉴욕 시티 FC",
  "New York Red Bulls": "뉴욕 레드불스",
  "Orlando City SC": "올랜도 시티",
  "Philadelphia Union": "필라델피아 유니언",
  "Portland Timbers": "포틀랜드 팀버스",
  "Real Salt Lake": "리얼 솔트레이크",
  "San Diego FC": "샌디에이고 FC",
  "San Jose Earthquakes": "산호세 어스퀘이크",
  "Seattle Sounders FC": "시애틀 사운더스",
  "Sporting Kansas City": "스포팅 캔자스시티",
  "St. Louis City SC": "세인트루이스 시티",
  "Toronto FC": "토론토 FC",
  "Vancouver Whitecaps FC": "밴쿠버 화이트캡스",

  // ─── NBA ───
  "Atlanta Hawks": "애틀랜타 호크스",
  "Boston Celtics": "보스턴 셀틱스",
  "Brooklyn Nets": "브루클린 네츠",
  "Charlotte Hornets": "샬럿 호네츠",
  "Chicago Bulls": "시카고 불스",
  "Cleveland Cavaliers": "클리블랜드 캐벌리어스",
  "Dallas Mavericks": "댈러스 매버릭스",
  "Denver Nuggets": "덴버 너기츠",
  "Detroit Pistons": "디트로이트 피스턴스",
  "Golden State Warriors": "골든스테이트 워리어스",
  "Houston Rockets": "휴스턴 로키츠",
  "Indiana Pacers": "인디애나 페이서스",
  "LA Clippers": "LA 클리퍼스",
  "Los Angeles Clippers": "LA 클리퍼스",
  "Los Angeles Lakers": "LA 레이커스",
  "LA Lakers": "LA 레이커스",
  "Memphis Grizzlies": "멤피스 그리즐리스",
  "Miami Heat": "마이애미 히트",
  "Milwaukee Bucks": "밀워키 벅스",
  "Minnesota Timberwolves": "미네소타 팀버울브스",
  "New Orleans Pelicans": "뉴올리언스 펠리컨스",
  "New York Knicks": "뉴욕 닉스",
  "Oklahoma City Thunder": "오클라호마시티 썬더",
  "Orlando Magic": "올랜도 매직",
  "Philadelphia 76ers": "필라델피아 76ers",
  "Phoenix Suns": "피닉스 선스",
  "Portland Trail Blazers": "포틀랜드 트레일블레이저스",
  "Sacramento Kings": "새크라멘토 킹스",
  "San Antonio Spurs": "샌안토니오 스퍼스",
  "Toronto Raptors": "토론토 랩터스",
  "Utah Jazz": "유타 재즈",
  "Washington Wizards": "워싱턴 위저즈",

  // ─── NHL ───
  "Anaheim Ducks": "애너하임 덕스",
  "Boston Bruins": "보스턴 브루인스",
  "Buffalo Sabres": "버펄로 세이버스",
  "Calgary Flames": "캘거리 플레임스",
  "Carolina Hurricanes": "캐롤라이나 허리케인스",
  "Chicago Blackhawks": "시카고 블랙호크스",
  "Colorado Avalanche": "콜로라도 애벌랜치",
  "Columbus Blue Jackets": "콜럼버스 블루재키츠",
  "Dallas Stars": "댈러스 스타스",
  "Detroit Red Wings": "디트로이트 레드윙스",
  "Edmonton Oilers": "에드먼턴 오일러스",
  "Florida Panthers": "플로리다 팬서스",
  "Los Angeles Kings": "LA 킹스",
  "LA Kings": "LA 킹스",
  "Minnesota Wild": "미네소타 와일드",
  "Montreal Canadiens": "몬트리올 캐나디언스",
  "Montréal Canadiens": "몬트리올 캐나디언스",
  "Nashville Predators": "내슈빌 프레데터스",
  "New Jersey Devils": "뉴저지 데블스",
  "New York Islanders": "뉴욕 아일랜더스",
  "New York Rangers": "뉴욕 레인저스",
  "Ottawa Senators": "오타와 세너터스",
  "Philadelphia Flyers": "필라델피아 플라이어스",
  "Pittsburgh Penguins": "피츠버그 펭귄스",
  "San Jose Sharks": "산호세 샤크스",
  "Seattle Kraken": "시애틀 크라켄",
  "St. Louis Blues": "세인트루이스 블루스",
  "Tampa Bay Lightning": "탬파베이 라이트닝",
  "Toronto Maple Leafs": "토론토 메이플리프스",
  "Utah Hockey Club": "유타 하키 클럽",
  "Utah Mammoth": "유타 매머드",
  "Vancouver Canucks": "밴쿠버 캐넉스",
  "Vegas Golden Knights": "베이거스 골든나이츠",
  "Washington Capitals": "워싱턴 캐피털스",
  "Winnipeg Jets": "위니펙 제츠",

  // ─── MLB ───
  "Arizona Diamondbacks": "애리조나 다이아몬드백스",
  "Atlanta Braves": "애틀랜타 브레이브스",
  "Baltimore Orioles": "볼티모어 오리올스",
  "Boston Red Sox": "보스턴 레드삭스",
  "Chicago Cubs": "시카고 컵스",
  "Chicago White Sox": "시카고 화이트삭스",
  "Cincinnati Reds": "신시내티 레즈",
  "Cleveland Guardians": "클리블랜드 가디언스",
  "Colorado Rockies": "콜로라도 로키스",
  "Detroit Tigers": "디트로이트 타이거스",
  "Houston Astros": "휴스턴 애스트로스",
  "Kansas City Royals": "캔자스시티 로열스",
  "Los Angeles Angels": "LA 에인절스",
  "Los Angeles Dodgers": "LA 다저스",
  "LA Dodgers": "LA 다저스",
  "Miami Marlins": "마이애미 말린스",
  "Milwaukee Brewers": "밀워키 브루어스",
  "Minnesota Twins": "미네소타 트윈스",
  "New York Mets": "뉴욕 메츠",
  "New York Yankees": "뉴욕 양키스",
  "Oakland Athletics": "오클랜드 애슬레틱스",
  "Athletics": "오클랜드 애슬레틱스",
  "Philadelphia Phillies": "필라델피아 필리스",
  "Pittsburgh Pirates": "피츠버그 파이리츠",
  "San Diego Padres": "샌디에이고 파드리스",
  "San Francisco Giants": "샌프란시스코 자이언츠",
  "Seattle Mariners": "시애틀 매리너스",
  "St. Louis Cardinals": "세인트루이스 카디널스",
  "Tampa Bay Rays": "탬파베이 레이스",
  "Texas Rangers": "텍사스 레인저스",
  "Toronto Blue Jays": "토론토 블루제이스",
  "Washington Nationals": "워싱턴 내셔널스",

  // ─── KBO (kbo.ts 와 일치) ───
  "KIA Tigers": "KIA 타이거즈",
  "Samsung Lions": "삼성 라이온즈",
  "LG Twins": "LG 트윈스",
  "Doosan Bears": "두산 베어스",
  "KT Wiz": "KT 위즈",
  "KT Wiz Suwon": "KT 위즈",
  "SSG Landers": "SSG 랜더스",
  "Lotte Giants": "롯데 자이언츠",
  "Hanwha Eagles": "한화 이글스",
  "NC Dinos": "NC 다이노스",
  "Kiwoom Heroes": "키움 히어로즈",

  // ─── 월드컵 진출국 (편의 — 한글 국가명) ───
  "South Korea": "대한민국",
  "Korea Republic": "대한민국",
  "Japan": "일본",
  "United States": "미국",
  "USA": "미국",
  "Canada": "캐나다",
  "Mexico": "멕시코",
  "Argentina": "아르헨티나",
  "Brazil": "브라질",
  "Uruguay": "우루과이",
  "Colombia": "콜롬비아",
  "Ecuador": "에콰도르",
  "Paraguay": "파라과이",
  "Bolivia": "볼리비아",
  "Chile": "칠레",
  "Peru": "페루",
  "Venezuela": "베네수엘라",
  "Spain": "스페인",
  "England": "잉글랜드",
  "France": "프랑스",
  "Germany": "독일",
  "Portugal": "포르투갈",
  "Italy": "이탈리아",
  "Netherlands": "네덜란드",
  "Belgium": "벨기에",
  "Croatia": "크로아티아",
  "Switzerland": "스위스",
  "Austria": "오스트리아",
  "Denmark": "덴마크",
  "Sweden": "스웨덴",
  "Norway": "노르웨이",
  "Poland": "폴란드",
  "Czech Republic": "체코",
  "Czechia": "체코",
  "Turkey": "튀르키예",
  "Türkiye": "튀르키예",
  "Australia": "호주",
  "Saudi Arabia": "사우디아라비아",
  "Iran": "이란",
  "Iraq": "이라크",
  "Qatar": "카타르",
  "United Arab Emirates": "아랍에미리트",
  "Uzbekistan": "우즈베키스탄",
  "Jordan": "요르단",
  "Morocco": "모로코",
  "Senegal": "세네갈",
  "Tunisia": "튀니지",
  "Egypt": "이집트",
  "Nigeria": "나이지리아",
  "Cameroon": "카메룬",
  "Ghana": "가나",
  "Ivory Coast": "코트디부아르",
  "Côte d'Ivoire": "코트디부아르",
  "Algeria": "알제리",
  "Costa Rica": "코스타리카",
  "Panama": "파나마",
  "Jamaica": "자메이카",
  "New Zealand": "뉴질랜드",

  // K리그 1
  "FC Seoul": "FC 서울",
  "Daejeon Citizen": "대전 하나",
  "Daejeon Hana Citizen": "대전 하나",
  "Incheon United": "인천 유나이티드",
  "Gwangju FC": "광주 FC",
  "Jeonbuk Motors": "전북 현대",
  "Jeonbuk Hyundai Motors": "전북 현대",
  "Gimcheon Sangmu FC": "김천 상무",
  "Gimcheon Sangmu": "김천 상무",
  "Jeju United FC": "제주 SK",
  "Jeju United": "제주 SK",
  "FC Anyang": "FC 안양",
  "Anyang": "FC 안양",
  "Bucheon FC 1995": "부천 FC 1995",
  "Bucheon FC": "부천 FC 1995",
  "Pohang Steelers": "포항 스틸러스",
  "Gangwon FC": "강원 FC",
  "Ulsan Hyundai FC": "울산 HD",
  "Ulsan Hyundai": "울산 HD",
  "Ulsan HD FC": "울산 HD",
  "Ulsan HD": "울산 HD",
  "Suwon Samsung Bluewings": "수원 삼성",
  "Daegu FC": "대구 FC",

  // K리그 2
  "Seoul E-Land FC": "서울 이랜드",
  "Seoul E-Land": "서울 이랜드",
  "Yongin City": "용인 시티",
  "Jeonnam Dragons": "전남 드래곤즈",
  "Cheongju": "충북 청주",
  "Chungbuk Cheongju": "충북 청주",
  "Ansan Greeners": "안산 그리너스",
  "Gimpo Citizen": "김포 FC",
  "Gimpo FC": "김포 FC",
  "Cheonan City": "천안 시티",
  "Cheonan City FC": "천안 시티",
  "Paju Citizen": "파주 시티즌",
  "Seongnam FC": "성남 FC",
  "Gyeongnam FC": "경남 FC",
  "Gimhae City": "김해 FC",
  "Hwaseong": "화성 FC",
  "Hwaseong FC": "화성 FC",
  "Busan I Park": "부산 아이파크",
  "Busan IPark": "부산 아이파크",
  "Asan Mugunghwa": "충남 아산",
  "Chungnam Asan FC": "충남 아산",
  "Suwon City FC": "수원 FC",
  "Suwon FC": "수원 FC",

  // J1 리그
  "Urawa Red Diamonds": "우라와 레드 다이아몬즈",
  "Urawa": "우라와",
  "FC Tokyo": "FC 도쿄",
  "Yokohama F. Marinos": "요코하마 F. 마리노스",
  "Yokohama FMarinos": "요코하마 F. 마리노스",
  "Kashiwa Reysol": "카시와 레이솔",
  "Vissel Kobe": "비셀 고베",
  "Gamba Osaka": "감바 오사카",
  "Cerezo Osaka": "세레소 오사카",
  "Kashima": "카시마 앤틀러스",
  "Kashima Antlers": "카시마 앤틀러스",
  "Sanfrecce Hiroshima": "산프레체 히로시마",
  "Avispa Fukuoka": "아비스파 후쿠오카",
  "Nagoya Grampus": "나고야 그램퍼스",
  "Kawasaki Frontale": "가와사키 프론탈레",
  "Shonan Bellmare": "쇼난 벨마레",
  "Fagiano Okayama": "파지아노 오카야마",
  "V-varen Nagasaki": "V-바렌 나가사키",
  "Tokyo Verdy": "도쿄 베르디",
  "Sagan Tosu": "사강 토스",
  "Albirex Niigata": "알비렉스 니가타",
  "Kyoto Sanga": "교토 상가",
  "Kyoto Sanga FC": "교토 상가",
  "Machida Zelvia": "마치다 젤비아",
  "FC Machida Zelvia": "마치다 젤비아",
  "Yokohama FC": "요코하마 FC",
  "Shimizu S-Pulse": "시미즈 S펄스",

  // 추가 — 분데스리가 영문 변형 + LCK + 한국 K2 / J2 잔여
  // ("Hamburger SV"/"1. FC Köln"/"FC Köln" 은 위에 이미 매핑 있음)
  "Hamburg SV": "함부르크",
  "HSV": "함부르크",
  "FC Cologne": "쾰른",
  "Cologne": "쾰른",
  "Mito Hollyhock": "미토 홀리호크",
  "Tokyo Verdy 1969": "도쿄 베르디",
  "Verdy": "도쿄 베르디",
  "Gen.G": "젠지",
  "Gen.G eSports": "젠지",
  "Ibiza": "이비사",
  "UD Ibiza": "이비사",

  // AFC 챔피언스리그 — 자주 등장하는 아시아 클럽 (자국 매핑 보강)
  "Al Hilal": "알 힐랄",
  "Al Nassr": "알 나스르",
  "Al Ittihad": "알 이티하드",
  "Al Ahli": "알 아흘리",
  "Buriram United": "부리람 유나이티드",
  "Shanghai Port": "상하이 포트",
  "Shanghai SIPG": "상하이 포트",
  "Shandong Taishan": "산둥 타이샨",
  "Yokohama F Marinos": "요코하마 F. 마리노스",

  // 사우디 프로 리그 추가
  "Al Ittihad Jeddah": "알 이티하드",
  "Al-Ittihad": "알 이티하드",
  "Al-Hilal": "알 힐랄",
  "Al-Nassr": "알 나스르",
  "Al-Ahli": "알 아흘리",
  "Al-Shabab": "알 샤바브",
  "Al Shabab": "알 샤바브",
  "Al Taawoun": "알 타아운",
  "Al-Taawoun": "알 타아운",
  "Al Ettifaq": "알 에티팍",
  "Al-Ettifaq": "알 에티팍",
  "Al Fateh": "알 파테흐",
  "Al-Fateh": "알 파테흐",
  "Al Qadsiah": "알 카드시아",
  "Al-Qadsiah": "알 카드시아",
  "Al Wehda": "알 웨흐다",
  "Al-Wehda": "알 웨흐다",
  "Al Riyadh": "알 리야드",
  "Al-Riyadh": "알 리야드",
  "Al Khaleej": "알 칼리지",
  "Al-Khaleej": "알 칼리지",
  "Damac": "다막",

  // 중국 슈퍼리그 (CSL)
  "Shanghai Shenhua": "상하이 선화",
  "Beijing Guoan": "베이징 궈안",
  "Shenzhen Peng City": "선전 펑청",
  "Tianjin Jinmen Tiger": "톈진 진먼",
  "Wuhan Three Towns": "우한 스리타운즈",
  "Chengdu Rongcheng": "청두 룽청",
  "Henan Songshan Longmen": "허난 쑹산",
  "Zhejiang FC": "저장 FC",
  "Changchun Yatai": "창춘 야타이",
  "Qingdao West Coast": "칭다오 웨스트 코스트",
  "Nantong Zhiyun": "난통 즈윈",
  "Meizhou Hakka": "메이저우 하카",
  "Yunnan Yukun": "윈난 위쿤",
  "Qingdao Hainiu": "칭다오 하이뉴",

  // 호주 A-리그
  "Melbourne Victory": "멜버른 빅토리",
  "Sydney FC": "시드니 FC",
  "Western Sydney Wanderers": "웨스턴 시드니 원더러스",
  "Adelaide United": "애들레이드 유나이티드",
  "Perth Glory": "퍼스 글로리",
  "Newcastle Jets": "뉴캐슬 제츠",
  "Brisbane Roar": "브리즈번 로어",
  "Macarthur FC": "매카서 FC",
  "Wellington Phoenix": "웰링턴 피닉스",
  "Western United": "웨스턴 유나이티드",
  "Melbourne City": "멜버른 시티",
  "Central Coast Mariners": "센트럴 코스트 매리너스",
  "Auckland FC": "오클랜드 FC",

  // 네덜란드 에레디비시
  "Ajax": "아약스",
  "PSV Eindhoven": "PSV 아인트호벤",
  "PSV": "PSV 아인트호벤",
  "Feyenoord": "페예노르트",
  "AZ Alkmaar": "AZ 알크마르",
  "AZ": "AZ 알크마르",
  "FC Twente": "FC 트벤테",
  "Twente": "FC 트벤테",
  "FC Utrecht": "FC 위트레흐트",
  "Utrecht": "FC 위트레흐트",
  "Sparta Rotterdam": "스파르타 로테르담",
  "Heerenveen": "헤이렌베인",
  "SC Heerenveen": "헤이렌베인",
  "NEC Nijmegen": "NEC 네이메헌",
  "NEC": "NEC 네이메헌",
  "Vitesse": "비테세",
  "Heracles": "헤라클레스",
  "Heracles Almelo": "헤라클레스",
  "Go Ahead Eagles": "고 어헤드 이글스",
  "RKC Waalwijk": "RKC 와알베이크",
  "Volendam": "폴렌담",
  "FC Volendam": "폴렌담",
  "Almere City": "알메러 시티",
  "PEC Zwolle": "PEC 즈볼레",
  "NAC Breda": "NAC 브레다",
  "Fortuna Sittard": "포르투나 시타르트",
  "Excelsior": "엑셀시오르",

  // 포르투갈 프리메이라 리가
  "Porto": "포르투",
  "FC Porto": "포르투",
  "Benfica": "벤피카",
  "SL Benfica": "벤피카",
  "Sporting CP": "스포르팅",
  "Sporting Lisbon": "스포르팅",
  "Braga": "브라가",
  "SC Braga": "브라가",
  "Vitoria Guimaraes": "비토리아 기마랑이스",
  "Vitoria SC": "비토리아 기마랑이스",
  "Famalicao": "파말리캉",
  "FC Famalicao": "파말리캉",
  "Estoril": "에스토릴",
  "Boavista": "보아비스타",
  "Rio Ave": "히우 아브",
  "Casa Pia": "카자 피아",
  "Moreirense": "모레이렌세",
  "Estrela": "에스트렐라",
  "Chaves": "샤베스",
  "Portimonense": "포르티모넨세",
  "Gil Vicente": "질 비센테",
  "Arouca": "아로카",
  "AVS": "AVS",
  "Nacional": "나시오날",
  "Santa Clara": "산타 클라라",
  "Farense": "파렌세",

  // 터키 쉬페르 리그
  "Galatasaray": "갈라타사라이",
  "Fenerbahce": "페네르바체",
  "Fenerbahçe": "페네르바체",
  "Besiktas": "베식타스",
  "Beşiktaş": "베식타스",
  "Trabzonspor": "트라브존스포르",
  "Basaksehir": "바샤크셰히르",
  "Başakşehir": "바샤크셰히르",
  "Konyaspor": "코냐스포르",
  "Antalyaspor": "안탈리아스포르",
  "Alanyaspor": "알라니아스포르",
  "Adana Demirspor": "아다나 데미르스포르",
  "Kasimpasa": "카심파샤",
  "Kasımpaşa": "카심파샤",
  "Goztepe": "괴즈테페",
  "Göztepe": "괴즈테페",
  "Eyupspor": "에이윱스포르",
  "Pendikspor": "펜디크스포르",
  "Samsunspor": "삼순스포르",
  "Hatayspor": "하타이스포르",
  "Bodrumspor": "보드룸스포르",
  "Kayserispor": "카이세리스포르",
  "Sivasspor": "시바스스포르",
  "Gaziantep": "가지안테프",
  "Gaziantep FK": "가지안테프",
  "Rizespor": "리제스포르",
  "Caykur Rizespor": "리제스포르",

  // 벨기에 주피러 프로 리그
  "Anderlecht": "안더레흐트",
  "RSC Anderlecht": "안더레흐트",
  "Club Brugge": "클럽 브뤼헤",
  "Club Brugge KV": "클럽 브뤼헤",
  "Genk": "헹크",
  "KRC Genk": "헹크",
  "Standard Liege": "스탕다르 리에주",
  "Standard Liège": "스탕다르 리에주",
  "Antwerp": "안트베르펜",
  "Royal Antwerp": "안트베르펜",
  "Royale Union SG": "위니옹 SG",
  "Union St. Gilloise": "위니옹 SG",
  "Union Saint-Gilloise": "위니옹 SG",
  "Mechelen": "메헬렌",
  "KV Mechelen": "메헬렌",
  "Gent": "헨트",
  "KAA Gent": "헨트",
  "Westerlo": "베스털로",
  "Cercle Brugge": "세르클 브뤼헤",
  "OH Leuven": "OH 뢰번",
  "Charleroi": "샤를루아",
  "Sint-Truidense": "신트트라위던",
  "Kortrijk": "코르트레이크",
  "Beerschot": "베르스호트",
  "Dender": "덴더르",

  // 스코틀랜드 SPL
  "Celtic": "셀틱",
  "Rangers": "레인저스",
  "Aberdeen": "애버딘",
  "Hearts": "하츠",
  "Heart of Midlothian": "하츠",
  "Hibernian": "히버니언",
  "Motherwell": "머더웰",
  "St Mirren": "세인트 미렌",
  "St. Mirren": "세인트 미렌",
  "Dundee": "던디",
  "Dundee United": "던디 유나이티드",
  "Kilmarnock": "킬마녹",
  "St Johnstone": "세인트 존스턴",
  "St. Johnstone": "세인트 존스턴",
  "Ross County": "로스 카운티",

  // 그리스 슈퍼리그
  "Olympiacos": "올림피아코스",
  "Olympiakos Piraeus": "올림피아코스",
  "Panathinaikos": "파나티나이코스",
  "PAOK": "PAOK",
  "PAOK Salonika": "PAOK",
  "AEK Athens": "AEK 아테네",
  "AEK Athens FC": "AEK 아테네",
  "Aris": "아리스",
  "Aris Thessaloniki": "아리스",
  "OFI": "OFI",
  "OFI Crete": "OFI",
  "Volos NPS": "볼로스",
  "Atromitos": "아트로미토스",
  "Lamia": "라미아",
  "Panaitolikos": "파나이톨리코스",
  "Kifissia": "키피시아",
  "Asteras Tripolis": "아스테라스 트리폴리스",
  "Levadiakos": "레바디아코스",

  // 브라질 세리에 A
  "Flamengo": "플라멩구",
  "Palmeiras": "팔메이라스",
  "Sao Paulo": "상파울루",
  "São Paulo": "상파울루",
  "Corinthians": "코린치안스",
  "Santos": "산토스",
  "Botafogo": "보타포구",
  "Fluminense": "플루미넨세",
  "Vasco DA Gama": "바스쿠 다 가마",
  "Vasco da Gama": "바스쿠 다 가마",
  "Internacional": "인테르나시오나우",
  "Gremio": "그레미우",
  "Grêmio": "그레미우",
  "Atletico-MG": "아틀레치쿠 미네이루",
  "Atlético Mineiro": "아틀레치쿠 미네이루",
  "Cruzeiro": "크루제이루",
  "Bahia": "바이아",
  "Vitoria": "비토리아",
  "Vitória": "비토리아",
  "Fortaleza": "포르탈레자",
  "EC Vitoria": "비토리아",
  "Ceara": "세아라",
  "Ceará": "세아라",
  "Sport Recife": "스포르치 헤시피",
  "Bragantino": "브라간치누",
  "RB Bragantino": "브라간치누",
  "Red Bull Bragantino": "브라간치누",
  "Athletico-PR": "아틀레치쿠 파라넨세",
  "Athletico Paranaense": "아틀레치쿠 파라넨세",
  "Juventude": "주벤투지",
  "Mirassol": "미라솔",

  // 멕시코 Liga MX
  "America": "클럽 아메리카",
  "Club America": "클럽 아메리카",
  "Club América": "클럽 아메리카",
  "Cruz Azul": "크루스 아술",
  "Chivas Guadalajara": "차바스",
  "Guadalajara": "차바스",
  "Pumas UNAM": "푸마스",
  "U.N.A.M.- Pumas": "푸마스",
  "Tigres": "티그레스",
  "Tigres UANL": "티그레스",
  "Monterrey": "몬테레이",
  "Toluca": "톨루카",
  "Pachuca": "파추카",
  "Leon": "레온",
  "León": "레온",
  "Club Leon": "레온",
  "Santos Laguna": "산토스 라구나",
  "Atlas": "아틀라스",
  "Mazatlan": "마사틀란",
  "Mazatlán": "마사틀란",
  "Necaxa": "네카사",
  "Queretaro": "케레타로",
  "Querétaro": "케레타로",
  "Puebla": "푸에블라",
  "Tijuana": "티후아나",
  "FC Juarez": "FC 후아레스",
  "FC Juárez": "FC 후아레스",
  "Atletico San Luis": "아틀레티코 산 루이스",
  "Atlético San Luis": "아틀레티코 산 루이스",

  // CSL 추가
  "Shenyang Urban": "선양 어반",
  "Chongqing Tongliang Long": "충칭 퉁량 룽",
  "Chongqing Tongliangloong": "충칭 퉁량 룽",

  // 라리가 2 (세군다) 추가
  "Real Sociedad II": "레알 소시에다드 B",
  "Real Sociedad B": "레알 소시에다드 B",
  "Mirandes": "미란데스",
  "CD Mirandes": "미란데스",
  "AD Ceuta FC": "AD 세우타",
  "Ceuta": "AD 세우타",
  "AD Ceuta": "AD 세우타",

  // 분데스리가 풀네임 alias
  "1. FC Heidenheim 1846": "하이덴하임",
  "1.FC Heidenheim 1846": "하이덴하임",

  // EPL/UCL short alias
  "Brighton Hove": "브라이턴",
  "Brighton": "브라이턴",
  "Nottingham": "노팅엄 포레스트",

  // 사우디 spelling 변형
  "Al-Fayha": "알 파이하",
  "Al Fayha": "알 파이하",
  "Al Taawon": "알 타아운",
  "Al-Taawon": "알 타아운",

  // 세리에 B
  "Sudtirol": "쥐드티롤",
  "Südtirol": "쥐드티롤",
  "FC Sudtirol": "쥐드티롤",
  "Bari": "바리",
  "SSC Bari": "바리",

  // 스코틀랜드 추가
  "Falkirk": "팔커크",
};

// 다양한 표기를 통합하기 위한 lookup helper.
// 1) 정확 매치 → 2) 소문자 매치 → 3) 흔한 접미어 제거 후 매치 → 4) fallback (원본)
const RAW_LOWER: Record<string, string> = Object.fromEntries(
  Object.entries(RAW).map(([k, v]) => [k.toLowerCase(), v]),
);

const STRIP_RE = /\s+(fc|cf|sc|afc|ac|cfc|club|football club)\.?$/i;

export function toKoreanTeamName(name: string | undefined | null): string {
  if (!name) return "";
  const trimmed = name.trim();
  if (RAW[trimmed]) return RAW[trimmed];
  const lower = trimmed.toLowerCase();
  if (RAW_LOWER[lower]) return RAW_LOWER[lower];
  const stripped = trimmed.replace(STRIP_RE, "").trim();
  if (RAW[stripped]) return RAW[stripped];
  const strippedLower = stripped.toLowerCase();
  if (RAW_LOWER[strippedLower]) return RAW_LOWER[strippedLower];
  return trimmed;
}
