import { NextResponse } from "next/server";
import { isCronAuthorized as authorized } from "@/lib/cron-auth";
import { runPreview } from "@/jobs/generate-previews";
import { recordCronRun } from "@/lib/cron-registry";
import { withLlmTag } from "@/lib/ai/usage-track";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

export async function GET(req: Request) {
  if (!authorized(req)) {
    return new NextResponse("Unauthorized", { status: 401 });
  }
  const url = new URL(req.url);
  // 2026-05-29: 프리뷰 자동 발행 재개. article 은 noindex(isAutoGenerated) 유지 →
  // 검색 색인 안 됨 = scaled content abuse 위험 없음. 회원/방문자용 경기 미리보기 콘텐츠.
  // ?league=EPL · ?horizonDays=2 · ?take=10 — 수동 trigger 시 잘게 처리.
  const league = url.searchParams.get("league") ?? undefined;
  const horizonDays = Number(url.searchParams.get("horizonDays")) || undefined;
  const take = Number(url.searchParams.get("take")) || undefined;
  // 시작 시점에 먼저 기록 — 발행이 maxDuration(300s)에 걸려 잘리면 완료 기록에 도달하지 못해
  // "미실행" 오탐이 났다 (2026-07-21 07:30 UTC 실행분). 시작 기록은 잘려도 남는다.
  await recordCronRun("preview");
  try {
    await withLlmTag("preview", () => runPreview({ league, horizonDays, take }));
    // 완료 기록 — cron-freshness dead-man's switch 가 preview 미실행·실패(529 등)를 직접 감지.
    await recordCronRun("preview");
    return NextResponse.json({ ok: true, league, horizonDays, take });
  } catch (e) {
    // 실패도 기록 — "미실행" 오탐 대신 "실행 실패" 로 알리게.
    await recordCronRun("preview", { ok: false, error: (e as Error).message });
    return NextResponse.json(
      { ok: false, error: (e as Error).message },
      { status: 500 },
    );
  }
}
