// collect cron(api-football 수집)의 대상 리그 목록 — 라우트 파일은 임의 export 를 못 해서 여기로 뺐다.
// 일정 공백 감시(schedule-gap-audit)도 "af 수집 대상인가"를 같은 목록으로 판정한다(2026-10-03).
// 리그를 추가·삭제할 때 주석·이력은 이 파일에 남긴다.
import type { League } from "./types";

export const ALL_LEAGUES: League[] = [
  "EPL",
  "LALIGA",
  "BUNDESLIGA",
  "SERIE_A",
  "LIGUE_1",
  "MLS",
  "UCL",
  "K_LEAGUE_1",
  "K_LEAGUE_2",
  "J1_LEAGUE",
  "J2_LEAGUE",
  "AFC_CL",
  "SAUDI_PL",
  "UEL",
  "UECL",
  "CHAMPIONSHIP",
  "LALIGA_2",
  "BUNDESLIGA_2",
  "SERIE_B",
  "LIGUE_2",
  "CLUB_WORLD_CUP",
  "AFC_CL_TWO",
  "AFC_U23",
  "ASEAN_CHAMP",
  // 국가대표 — 2026-09-23. UEFA_NL 은 한 번도 수집된 적이 없었고(주석엔 "af 계속 사용"이라 적혀 있었으나 목록엔 없음),
  //  INTL_FRIENDLY 는 5/24 월드컵 대비 백필 이후 0건(ts 매핑에 시즌 id 가 있어 TS_COVERED 로 분류돼 af 가 skip 했는데
  //  ts 는 실제로 매치를 하나도 안 만들었다 → TS_COVERED_EXCEPTIONS 에 등재). 베트맨 발매 경기(A매치·네이션스리그·걸프컵)
  //  연결이 이 수집에 걸려 있다.
  "UEFA_NL",
  "INTL_FRIENDLY",
  "GULF_CUP",
  "CSL",
  "A_LEAGUE",
  "EREDIVISIE",
  "PRIMEIRA_LIGA",
  "SUPER_LIG",
  "JUPILER_PL",
  "SPL",
  "SCO_LEAGUE_CUP", // 스코틀랜드 리그컵 (af 185, 2026 시즌 진행 중)
  "GREEK_SL",
  "BRASILEIRAO",
  "LIGA_MX",
  "COPA_LIB",
  "COPA_SUD",
  "EKSTRAKLASA",
  "POLAND_1L",
  "BULGARIA_PL",
  "LIGA_I",
  "SWISS_SL",
  "CHALLENGE_LEAGUE",
  "ARMENIA_PL",
  "AUSTRIA_BL",
  "CZECH_L",
  "HNL",
  "UKRAINE_PL",
  "HUNGARY_NB1",
  "SERBIA_SL",
  "SLOVAKIA_SL",
  "SLOVENIA_SNL",
  "CYPRUS_1D",
  "DENMARK_SL",
  "IRELAND_PD",
  "BOSNIA_PL",
  "ALBANIA_SL",
  "MOLDOVA_SL",
  "ELITESERIEN",
  "NORWAY_1L",
  "ALLSVENSKAN",
  "SUPERETTAN",
  "VEIKKAUSLIIGA",
  "YKKONEN",
  "URVALSDEILD",
  "ICELAND_1L",
  "CHILE_PD",
  "CHILE_PB",
  "ECUADOR_LP",
  "COLOMBIA_PA",
  "PERU_PD",
  "VENEZUELA_PD",
  "PARAGUAY_PD", // 2026-08-01 — ts 롤오버 정지로 af 수집 재개 (클라우수라 id 는 collector 가 월별 분기)
  "EGYPT_PL",
  "ISRAEL_PL",
  "INDIA_ISL",
  "VIETNAM_VL1",
  "INDONESIA_L1",
  "SINGAPORE_PL",
  "UAE_PL",
  "QATAR_SL",
  "MOROCCO_BP",
  "SOUTHAFRICA_PSL",
  "USA_USL_CH",
  "CANADA_PL",
  // 2026-05-24 추가 (4개)
  "SUI_CUP",
  // KFA컵 (2026-09-25) — af 294 매핑·컬렉터는 있었는데 이 목록에 없어 한 번도 수집되지 않았다(DB 0건).
  "KFA_CUP",
  "LEAGUE_ONE",
  "LATVIA_VL",
  "BELARUS_PL",
  // 2026-05-24 추가 (2차, 8개)
  "ESTONIA_ML",
  "LITHUANIA_AL",
  "LEVAIN_CUP",
  "KAZAKHSTAN_PL",
  "GEORGIA_EL",
  "AZERBAIJAN_PL",
  "EREDIVISIE_2",
  "PRIMEIRA_LIGA_2",
  // NBA 제거 (2026-08-09) — TheSports basketball worker 단일 소스. af/ESPN 이중수집이
  // 팀 id 충돌로 이름 오매핑 3행을 만든 근본원인 (collectors.NBA 도 no-op 처리).
  "NHL",
  "MLB",
  "KBO",
  "NPB",
  "LOL",
  "LCK_CL", // LCK 2군
  "LPL", "LEC", "LCS", // 해외 (표시만) — collect 가 fetchLolAll 1회 캐시 공유
];
