// MLB 선수 영문 → 한국어 사전.
// 자동 생성: scripts/build-player-names-from-wiki.ts
// Source: 위키피디아 ko langlinks (en.wikipedia.org/w/api.php?prop=langlinks&lllang=ko)

export const MLB_PLAYER_NAMES_KO: Record<string, string> = {
  "Aaron Judge": "에런 저지",
  "Aaron Nola": "에런 놀라",
  "Adley Rutschman": "애들리 러치맨",
  "AJ Blubaugh": "AJ 블루바",
  "Alex Bregman": "알렉스 브레그먼",
  "Andrew Benintendi": "앤드루 베닌텐디",
  "Andrew McCutchen": "앤드루 매커친",
  "Aroldis Chapman": "어롤디스 채프먼",
  "Austin Riley": "오스틴 라일리",
  "Blake Treinen": "블레이크 트라이넨",
  "Bo Bichette": "보 비솃",
  "Brooks Raley": "브룩스 레일리",
  "Bryce Harper": "브라이스 하퍼",
  "Bryce Johnson": "브라이스 존슨",
  "Burch Smith": "버치 스미스",
  "Carlos Rodon": "카를로스 로돈",
  "Carson Kelly": "카슨 켈리",
  "Chris Sale": "크리스 세일",
  "Christian Yelich": "크리스천 옐리치",
  "CJ Abrams": "CJ 에이브럼스",
  "Cody Bellinger": "코디 벨린저",
  "Craig Kimbrel": "크레이그 킴브렐",
  "Danny Jansen": "대니 잰슨",
  "Dansby Swanson": "댄즈비 스완슨",
  "Devin Williams": "데빈 윌리엄스",
  "DL Hall": "DL 홀",
  "Enmanuel De Jesus": "엔마누엘 데 헤수스",
  "Fernando Tatis Jr.": "페르난도 타티스 주니어",
  "Freddie Freeman": "프레디 프리먼",
  "Garrett Whitlock": "개럿 휘틀록",
  "George Springer": "조지 스프링어",
  "Grant Taylor": "그랜트 테일러",
  "Ha-Seong Kim": "김하성",
  "Henry Davis": "헨리 데이비스",
  "Hyeseong Kim": "김혜성 (야구 선수)",
  "Isaac Paredes": "아이작 파레데스",
  "J.C. Escarra": "J. C. 에스카라",
  "J.P. Crawford": "J. P. 크로포드",
  "J.T. Realmuto": "J. T. 리얼무토",
  "Jacob Young": "제이컵 영",
  "Jason Alexander": "제이슨 알렉산더",
  "Jeff McNeil": "제프 맥닐",
  "Jeremy Pena": "제레미 페냐",
  "Jesus Luzardo": "헤수스 루자르도",
  "JJ Bleday": "JJ 블러데이",
  "JJ Wetherholt": "J. J. 웨더홀트",
  "Joc Pederson": "작 피더슨",
  "Jonathan Loaisiga": "조너선 로아이시가",
  "Jorge Soler": "호르헤 솔레르",
  "Jose Fernandez": "호세 페르난데스",
  "Jose Ferrer": "호세 페레르",
  "Juan Soto": "후안 소토",
  "Kazuma Okamoto": "오카모토 가즈마",
  "Kenley Jansen": "켄리 잰슨",
  "Ketel Marte": "케텔 마르테",
  "Kyle Higashioka": "카일 히가시오카",
  "Kyle Tucker": "카일 터커",
  "Lourdes Gurriel Jr.": "루어데스 구리엘 주니어",
  "Luis Severino": "루이스 세베리노",
  "Manny Machado": "매니 마차도",
  "Marcell Ozuna": "마르셀 오즈나",
  "Marcus Semien": "마커스 세미엔",
  "Masataka Yoshida": "요시다 마사타카",
  "Matt Chapman": "맷 채프먼",
  "Matt Olson": "맷 올슨",
  "Max Muncy": "맥스 먼시",
  "Merrill Kelly": "메릴 켈리",
  "Michael Conforto": "마이클 콘포토",
  "Michael Wacha": "마이클 와카",
  "Miguel Andujar": "미겔 안두하르",
  "Mike Trout": "마이크 트라우트",
  "MJ Melendez": "MJ 멜렌데즈",
  "Mookie Betts": "무키 베츠",
  "Munetaka Murakami": "무라카미 무네타카",
  "Nick Castellanos": "니콜라스 카스테야노스",
  "Nick Kurtz": "닉 커츠",
  "Nolan Arenado": "놀런 아레나도",
  "P.J. Higgins": "P. J. 히긴스",
  "Patrick Wisdom": "패트릭 위즈덤",
  "Paul Goldschmidt": "폴 골드슈미트",
  "Pete Alonso": "피트 알론소",
  "Pierce Johnson": "피어스 존슨",
  "Rafael Devers": "라파엘 데베르스",
  "Ramon Laureano": "라몬 로리아노",
  "Randal Grichuk": "랜달 그리척",
  "Rhys Hoskins": "리스 호스킨스",
  "Rob Refsnyder": "롭 레프스나이더",
  "Ronald Acuna Jr.": "로날드 아쿠냐 주니어",
  "Ryan Johnson": "라이언 존슨",
  "Salvador Perez": "살바도르 페레스",
  "Sandy Alcantara": "샌디 알칸타라",
  "Sandy Leon": "샌디 레온",
  "Seiya Suzuki": "스즈키 세이야",
  "Shane Baz": "셰인 바즈",
  "Shohei Ohtani": "오타니 쇼헤이",
  "Starling Marte": "스탈링 마르테",
  "Sung-Mun Song": "송성문 (야구 선수)",
  "Teoscar Hernandez": "테오스카 에르난데스",
  "Vladimir Guerrero Jr.": "블라디미르 게레로 주니어",
  "Will Smith": "윌 스미스",
  "Willson Contreras": "윌손 콘트레라스",
  "Yandy Diaz": "얀디 디아즈",
  "Yordan Alvarez": "요르단 알바레스",
  "Yuki Matsui": "마쓰이 유키",
};
