// MLB 선수 영문 → 한국어 사전.
// 자동 생성: scripts/build-player-names-from-wiki.ts
// Source: 위키피디아 ko langlinks (en.wikipedia.org/w/api.php?prop=langlinks&lllang=ko)

export const MLB_PLAYER_NAMES_KO: Record<string, string> = {
  "A.J. Minter": "A. J. 민터",
  "Aaron Brooks": "에런 브룩스",
  "Aaron Judge": "에런 저지",
  "Aaron Nola": "에런 놀라",
  "Adley Rutschman": "애들리 러치맨",
  "AJ Blubaugh": "AJ 블루바",
  "Albert Suarez": "앨버트 수아레즈",
  "Alec Gamboa": "알렉 감보아",
  "Alex Bregman": "알렉스 브레그먼",
  "Andrew Benintendi": "앤드루 베닌텐디",
  "Andrew McCutchen": "앤드루 매커친",
  "Aroldis Chapman": "어롤디스 채프먼",
  "Austin Riley": "오스틴 라일리",
  "Blake Snell": "블레이크 스넬",
  "Blake Treinen": "블레이크 트라이넨",
  "Bo Bichette": "보 비솃",
  "Brooks Raley": "브룩스 레일리",
  "Bryce Harper": "브라이스 하퍼",
  "Bryce Johnson": "브라이스 존슨",
  "Burch Smith": "버치 스미스",
  "Carlos Carrasco": "카를로스 카라스코",
  "Carlos Rodon": "카를로스 로돈",
  "Carson Kelly": "카슨 켈리",
  "Chris Bassitt": "크리스 배싯",
  "Chris Martin": "크리스 마틴",
  "Chris Sale": "크리스 세일",
  "Christian Yelich": "크리스천 옐리치",
  "CJ Abrams": "CJ 에이브럼스",
  "Cody Bellinger": "코디 벨린저",
  "Connor Seabold": "코너 시볼드",
  "Corey Seager": "코리 시거",
  "Craig Kimbrel": "크레이그 킴브렐",
  "Danny Jansen": "대니 잰슨",
  "Dansby Swanson": "댄즈비 스완슨",
  "Devin Williams": "데빈 윌리엄스",
  "Dietrich Enns": "디트릭 엔스",
  "DL Hall": "DL 홀",
  "Enmanuel De Jesus": "엔마누엘 데 헤수스",
  "Eric Lauer": "에릭 라우어",
  "Erick Fedde": "에릭 페디",
  "Eugenio Suarez": "에우헤니오 수아레스",
  "Fernando Tatis Jr.": "페르난도 타티스 주니어",
  "Freddie Freeman": "프레디 프리먼",
  "Gabriel Arias": "가브리엘 아리아스",
  "Garrett Cleavinger": "개럿 클레빈저",
  "Garrett Stubbs": "개럿 스텁스",
  "Garrett Whitlock": "개럿 휘틀록",
  "Gary Sanchez": "가리 산체스",
  "George Springer": "조지 스프링어",
  "Gerrit Cole": "게릿 콜",
  "Gleyber Torres": "글레이버 토레스",
  "Grant Taylor": "그랜트 테일러",
  "Ha-Seong Kim": "김하성",
  "Henry Davis": "헨리 데이비스",
  "Hyeseong Kim": "김혜성 (야구 선수)",
  "Isaac Paredes": "아이작 파레데스",
  "J.C. Escarra": "J. C. 에스카라",
  "J.P. Crawford": "J. P. 크로포드",
  "J.T. Ginn": "J. T. 긴",
  "J.T. Realmuto": "J. T. 리얼무토",
  "Jack Flaherty": "잭 플래어티",
  "Jacob deGrom": "제이컵 디그롬",
  "Jacob Young": "제이컵 영",
  "Jameson Taillon": "제이미슨 타이온",
  "Jared Young": "제러드 영",
  "Jason Alexander": "제이슨 알렉산더",
  "Jeff McNeil": "제프 맥닐",
  "Jeremy Pena": "제레미 페냐",
  "Jesus Luzardo": "헤수스 루자르도",
  "JJ Bleday": "JJ 블러데이",
  "JJ Wetherholt": "J. J. 웨더홀트",
  "Joc Pederson": "작 피더슨",
  "Jonathan Loaisiga": "조너선 로아이시가",
  "Jorge Soler": "호르헤 솔레르",
  "Jose Altuve": "호세 알투베",
  "Jose Fernandez": "호세 페르난데스",
  "Jose Ferrer": "호세 페레르",
  "Jose Quintana": "호세 퀸타나",
  "Josh Smith": "조시 스미스",
  "JT Brubaker": "JT 브루베이커",
  "Juan Soto": "후안 소토",
  "Jung Hoo Lee": "이정후",
  "Kazuma Okamoto": "오카모토 가즈마",
  "Kenley Jansen": "켄리 잰슨",
  "Ketel Marte": "케텔 마르테",
  "Kevin Gausman": "케빈 고즈먼",
  "Kodai Senga": "센가 고다이",
  "Kyle Hart": "카일 하트",
  "Kyle Higashioka": "카일 히가시오카",
  "Kyle Schwarber": "카일 슈워버",
  "Kyle Tucker": "카일 터커",
  "Logan Henderson": "로건 헨더슨",
  "Lou Trivino": "루 트리비노",
  "Lourdes Gurriel Jr.": "루어데스 구리엘 주니어",
  "Lucas Giolito": "루커스 지올리토",
  "Luis Garcia": "루이스 가르시아",
  "Luis Severino": "루이스 세베리노",
  "Manny Machado": "매니 마차도",
  "Marcell Ozuna": "마르셀 오즈나",
  "Marcus Semien": "마커스 세미엔",
  "Masataka Yoshida": "요시다 마사타카",
  "Matt Chapman": "맷 채프먼",
  "Matt Olson": "맷 올슨",
  "Max Fried": "맥스 프리드",
  "Max Muncy": "맥스 먼시",
  "Max Scherzer": "맥스 슈어저",
  "Merrill Kelly": "메릴 켈리",
  "Michael Conforto": "마이클 콘포토",
  "Michael Kelly": "마이크 켈리",
  "Michael Wacha": "마이클 와카",
  "Miguel Andujar": "미겔 안두하르",
  "Mike Trout": "마이크 트라우트",
  "Miles Mikolas": "마일스 마이컬러스",
  "MJ Melendez": "MJ 멜렌데즈",
  "Mookie Betts": "무키 베츠",
  "Munetaka Murakami": "무라카미 무네타카",
  "Nathan Eovaldi": "네이선 이발디",
  "Nick Castellanos": "니콜라스 카스테야노스",
  "Nick Kurtz": "닉 커츠",
  "Nolan Arenado": "놀런 아레나도",
  "P.J. Higgins": "P. J. 히긴스",
  "Patrick Corbin": "패트릭 코빈",
  "Patrick Wisdom": "패트릭 위즈덤",
  "Paul Goldschmidt": "폴 골드슈미트",
  "Pete Alonso": "피트 알론소",
  "Pierce Johnson": "피어스 존슨",
  "PJ Poulin": "PJ 풀린",
  "Rafael Devers": "라파엘 데베르스",
  "Ramon Laureano": "라몬 로리아노",
  "Randal Grichuk": "랜달 그리척",
  "Rhys Hoskins": "리스 호스킨스",
  "Rob Refsnyder": "롭 레프스나이더",
  "Robbie Ray": "로비 레이",
  "Roki Sasaki": "사사키 로키",
  "Ronald Acuna Jr.": "로날드 아쿠냐 주니어",
  "Rowdy Tellez": "라우디 텔레즈",
  "Ryan Johnson": "라이언 존슨",
  "Salvador Perez": "살바도르 페레스",
  "Sandy Alcantara": "샌디 알칸타라",
  "Sandy Leon": "샌디 레온",
  "Sean Manaea": "숀 머나이아",
  "Seiya Suzuki": "스즈키 세이야",
  "Shane Baz": "셰인 바즈",
  "Shohei Ohtani": "오타니 쇼헤이",
  "Shota Imanaga": "이마나가 쇼타",
  "Sonny Gray": "소니 그레이",
  "Starling Marte": "스탈링 마르테",
  "Sung-Mun Song": "송성문 (야구 선수)",
  "Tatsuya Imai": "이마이 다쓰야",
  "Teoscar Hernandez": "테오스카 에르난데스",
  "TJ Friedl": "TJ 프리들",
  "Tommy Edman": "토미 에드먼",
  "Tommy Kahnle": "토미 케인리",
  "Tomoyuki Sugano": "스가노 도모유키",
  "Trevor Story": "트레버 스토리",
  "Trey Mancini": "트레이 맨시니",
  "Vladimir Guerrero Jr.": "블라디미르 게레로 주니어",
  "Walker Buehler": "워커 뷸러",
  "Will Smith": "윌 스미스",
  "Willson Contreras": "윌손 콘트레라스",
  "Yandy Diaz": "얀디 디아즈",
  "Yoan Moncada": "요안 몽카다",
  "Yordan Alvarez": "요르단 알바레스",
  "Yoshinobu Yamamoto": "야마모토 요시노부",
  "Yuki Matsui": "마쓰이 유키",
  "Zack Wheeler": "잭 휠러",
};
