// NBA 선수 영문 → 한글 매핑 (시즌 리더보드용).
// player-names.ts 의 RAW 는 슈퍼스타 위주라 매년 바뀌는 leaders 명단 누락 多.
// 신규 leader 등장 시 추가.

export const NBA_PLAYER_NAMES_KO: Record<string, string> = {
  "Ausar Thompson": "아우사 톰슨",
  "Cade Cunningham": "케이드 커닝햄",
  "Cason Wallace": "케이슨 월리스",
  "Chet Holmgren": "쳇 홈그렌",
  "Donovan Clingan": "도노반 클링건",
  "Dyson Daniels": "다이슨 대니얼스",
  "Evan Mobley": "에반 모블리",
  "Isaiah Collier": "아이제이아 콜리어",
  "Isaiah Stewart": "아이제이아 스튜어트",
  "Jalen Brunson": "제일런 브런슨",
  "Jalen Duren": "제일런 듀렌",
  "Jalen Johnson": "제일런 존슨",
  "Jamal Murray": "자말 머레이",
  "Jay Huff": "제이 허프",
  "Kawhi Leonard": "카와이 레너드",
  "Kel'el Ware": "켈렐 웨어",
  "Kris Dunn": "크리스 던",
  "LaMelo Ball": "라멜로 볼",
  "Matas Buzelis": "마타스 부젤리스",
  "Myles Turner": "마일스 터너",
  "OG Anunoby": "OG 아누노비",
  "Rudy Gobert": "루디 고베어",
  "Scottie Barnes": "스카티 반스",
  "Stephon Castle": "스테펀 캐슬",
  "Trey Murphy III": "트레이 머피 III",
  "Tyrese Maxey": "타이리스 맥시",
  // ── 슈퍼스타 / 올스타 (자주 leader) ──
  "LeBron James": "르브론 제임스",
  "Stephen Curry": "스테판 커리",
  "Kevin Durant": "케빈 듀란트",
  "Giannis Antetokounmpo": "야니스 아데토쿤보",
  "Nikola Jokic": "니콜라 요키치",
  "Nikola Jokić": "니콜라 요키치",
  "Luka Doncic": "루카 돈치치",
  "Luka Dončić": "루카 돈치치",
  "Joel Embiid": "조엘 엠비드",
  "Jayson Tatum": "제이슨 테이텀",
  "Anthony Davis": "앤서니 데이비스",
  "Damian Lillard": "데이미언 릴라드",
  "Devin Booker": "데빈 부커",
  "Anthony Edwards": "앤서니 에드워즈",
  "Shai Gilgeous-Alexander": "셰이 길저스알렉산더",
  "Victor Wembanyama": "빅터 웸반야마",
  "Ja Morant": "자 모란트",
  "Trae Young": "트레이 영",
  "Zion Williamson": "자이언 윌리엄슨",
  "De'Aaron Fox": "디애런 폭스",
  "Donovan Mitchell": "도노반 미첼",
  "Paul George": "폴 조지",
  "Jimmy Butler": "지미 버틀러",
  "Kyrie Irving": "카이리 어빙",
  "James Harden": "제임스 하든",
  "Russell Westbrook": "러셀 웨스트브룩",
  "Klay Thompson": "클레이 톰슨",
  "Draymond Green": "드레이먼드 그린",
  "Jrue Holiday": "즈루 할리데이",
  "Bam Adebayo": "뱀 아데바요",
  "Pascal Siakam": "패스칼 시아캄",
  "Brandon Ingram": "브랜든 잉그램",
  "Zach LaVine": "잭 라빈",
  "DeMar DeRozan": "디마 드로잔",
  "Domantas Sabonis": "도만타스 사보니스",
  "Tyrese Haliburton": "타이리스 핼리버튼",
  "Paolo Banchero": "파올로 반케로",
  "Franz Wagner": "프란츠 바그너",
  "Jaylen Brown": "제일런 브라운",
  "Derrick White": "데릭 화이트",
  "Kristaps Porzingis": "크리스타프스 포르징기스",
  "Kristaps Porziņģis": "크리스타프스 포르징기스",
  "Karl-Anthony Towns": "칼앤서니 타운스",
  "Julius Randle": "줄리어스 랜들",
  "Mikal Bridges": "마이클 브리지스",
  "Devin Vassell": "데빈 바셀",
  "Aaron Gordon": "애런 고든",
  "Michael Porter Jr.": "마이클 포터 주니어",
  "Jalen Williams": "제일런 윌리엄스",
  "Alperen Sengun": "알페렌 셴군",
  "Alperen Şengün": "알페렌 셴군",
  "Fred VanVleet": "프레드 밴블릿",
  "Lauri Markkanen": "라우리 마르카넨",
  "Desmond Bane": "데즈먼드 베인",
  "Jaren Jackson Jr.": "자렌 잭슨 주니어",
  "CJ McCollum": "시제이 맥칼럼",
  "Brook Lopez": "브룩 로페즈",
  "Khris Middleton": "크리스 미들턴",
  "Bradley Beal": "브래들리 빌",
  "Jordan Poole": "조던 풀",
  "RJ Barrett": "알제이 배럿",
  "Cam Thomas": "캠 토머스",
  "Coby White": "코비 화이트",
  "Nikola Vucevic": "니콜라 부체비치",
  "Nikola Vučević": "니콜라 부체비치",
  "Austin Reaves": "오스틴 리브스",
  "Norman Powell": "노먼 파월",
  "Ivica Zubac": "이비차 주바츠",
  "Jalen Green": "제일런 그린",
  "Amen Thompson": "에이먼 톰슨",
  "Deni Avdija": "데니 아브디야",
  "Jabari Smith Jr.": "자바리 스미스 주니어",
  "Walker Kessler": "워커 케슬러",
  "Cooper Flagg": "쿠퍼 플래그",
};
