// NBA 선수 영문 → 한국어 사전.
// 자동 생성: scripts/build-player-names-from-wiki.ts
// Source: 위키피디아 ko langlinks (en.wikipedia.org/w/api.php?prop=langlinks&lllang=ko)

export const NBA_PLAYER_NAMES_WIKI_KO: Record<string, string> = {
  "Aaron Gordon": "애런 고든",
  "AJ Green": "A. J. 그린",
  "AJ Johnson": "A. J. 존슨",
  "Alperen Sengun": "알페렌 솅귄",
  "Andrew Wiggins": "앤드루 위긴스",
  "Anthony Davis": "앤서니 데이비스 (농구 선수)",
  "Anthony Edwards": "앤서니 에드워즈",
  "Bam Adebayo": "뱀 아데바요",
  "Baylor Scheierman": "베일러 샤이어만",
  "Bilal Coulibaly": "빌랄 쿨리발리",
  "Bogdan Bogdanovic": "보그단 보그다노비치",
  "Brandon Ingram": "브랜던 잉그램",
  "Bronny James": "브로니 제임스",
  "Brook Lopez": "브룩 로페즈",
  "CJ McCollum": "CJ 매콜럼",
  "Cody Williams": "코디 윌리엄스",
  "Cooper Flagg": "쿠퍼 플래그",
  "D'Angelo Russell": "디안젤로 러셀",
  "Dalton Knecht": "달튼 크넥트",
  "Damian Lillard": "데이미언 릴러드",
  "Daniel Gafford": "대니얼 개퍼드",
  "Dariq Whitehead": "다리크 화이트헤드",
  "Darius Garland": "다리우스 갈랜드",
  "DaRon Holmes II": "다론 홈즈 2세",
  "David Roddy": "데이비드 로디",
  "De'Aaron Fox": "디애런 팍스",
  "De'Andre Hunter": "디안드레 헌터",
  "De'Anthony Melton": "디앤서니 멜튼",
  "Dean Wade": "딘 웨이드",
  "DeAndre Jordan": "디앤드리 조던",
  "Dejounte Murray": "드존테 머레이",
  "DeMar DeRozan": "더마 더로전",
  "Dennis Schroder": "데니스 슈뢰더",
  "Dereck Lively II": "데릭 라이블리 2세",
  "Derrick Jones Jr.": "데릭 존스 주니어",
  "Derrick White": "데릭 화이트 (농구 선수)",
  "Desmond Bane": "데스몬드 베인",
  "Devin Booker": "데빈 부커",
  "Dillon Brooks": "딜런 브룩스",
  "Domantas Sabonis": "도만타스 사보니스",
  "Donte DiVincenzo": "단테 디빈첸조",
  "Doug McDermott": "덕 맥더맷",
  "Draymond Green": "드레이먼드 그린",
  "Duncan Robinson": "던컨 로빈슨",
  "Dwight Powell": "드와이트 파월",
  "E.J. Liddell": "E. J. 리델",
  "Franz Wagner": "프란츠 바그너 (농구 선수)",
  "Gabe Vincent": "게이브 빈센트",
  "Garrett Temple": "개릿 템플",
  "Gary Harris": "게리 해리스",
  "Gary Payton II": "게리 페이턴 2세",
  "Gary Trent Jr.": "게리 트렌트 주니어",
  "GG Jackson": "GG 잭슨",
  "Giannis Antetokounmpo": "야니스 아데토쿤보",
  "Gradey Dick": "그래디 딕",
  "Grayson Allen": "그레이슨 앨런",
  "Guerschon Yabusele": "게르숀 야부셀레",
  "Harrison Barnes": "해리슨 반스",
  "Hugo Gonzalez": "우고 곤살레스",
  "Ja Morant": "자 머랜트",
  "Ja'Kobe Walter": "자코비 월터",
  "Jalen Brunson": "제일런 브런슨",
  "Jalen Green": "제일런 그린",
  "James Harden": "제임스 하든",
  "Jaren Jackson Jr.": "재런 잭슨 주니어",
  "Jayson Tatum": "제이슨 테이텀",
  "JD Davison": "JD 데이비슨",
  "Jerami Grant": "제러미 그랜트",
  "Jimmy Butler III": "지미 버틀러",
  "Joel Embiid": "조엘 엠비드",
  "John Collins": "존 콜린스",
  "Jonas Valanciunas": "요나스 발란추나스",
  "Jonathan Kuminga": "조나탕 쿠밍가",
  "Jrue Holiday": "즈루 홀리데이",
  "Jusuf Nurkic": "유수프 누르키치",
  "Karl-Anthony Towns": "칼앤서니 타운스",
  "Kawhi Leonard": "카와이 레너드",
  "Keldon Johnson": "켈든 존슨",
  "Kelly Olynyk": "켈리 올리닉",
  "Kevin Durant": "케빈 듀랜트",
  "Kevin Love": "케빈 러브",
  "Kevin Porter Jr.": "케빈 포터 주니어",
  "Khris Middleton": "크리스 미들턴",
  "KJ Simpson": "KJ 심슨",
  "Klay Thompson": "클레이 톰프슨",
  "Kristaps Porzingis": "크리스탑스 포르진지스",
  "Kyle Anderson": "카일 앤더슨",
  "Kyle Lowry": "카일 라우리",
  "Kyrie Irving": "카이리 어빙",
  "LaMelo Ball": "라멜로 볼",
  "Lauri Markkanen": "라우리 마르카넨",
  "LeBron James": "르브론 제임스",
  "Luguentz Dort": "루겐츠 도트",
  "Luka Doncic": "루카 돈치치",
  "Mark Williams": "마크 윌리엄스",
  "Max Christie": "맥스 크리스티",
  "Mikal Bridges": "미캘 브리지스",
  "Miles Bridges": "마일스 브리지스",
  "Moritz Wagner": "모리츠 바그너",
  "Naji Marshall": "나지 마셜",
  "Naz Reid": "나즈 리드",
  "Nic Claxton": "닉 클랙스턴",
  "Nick Smith Jr.": "닉 스미스 주니어",
  "Nickeil Alexander-Walker": "니킬 알렉산더워커",
  "Nicolas Batum": "니콜라 바튐",
  "Nikola Jokic": "니콜라 요키치",
  "Nikola Jovic": "니콜라 요비치",
  "Noah Clowney": "노아 클라우니",
  "Norman Powell": "노먼 파웰",
  "P.J. Washington": "P. J. 워싱턴",
  "Paul George": "폴 조지",
  "Ron Harper Jr.": "론 하퍼 주니어",
  "Rudy Gobert": "뤼디 고베르",
  "Rui Hachimura": "하치무라 루이",
  "Russell Westbrook": "러셀 웨스트브룩",
  "Ryan Dunn": "라이언 던",
  "Ryan Rollins": "라이언 롤린스",
  "Seth Curry": "세스 커리",
  "Shai Gilgeous-Alexander": "셰이 길저스알렉산더",
  "Stephen Curry": "스테픈 커리",
  "T.J. McConnell": "T. J. 맥코넬",
  "Terrence Shannon Jr.": "테런스 섀넌 주니어",
  "Tyrese Haliburton": "타이리스 핼리버턴",
  "Victor Wembanyama": "빅토르 웸바냐마",
  "Yuki Kawamura": "가와무라 유키",
  "Zaccharie Risacher": "자카리 리자셰",
  "Zach LaVine": "잭 러빈",
  "Zion Williamson": "자이언 윌리엄슨",
};
