// NHL 선수 영문 → 한글 매핑 (ESPN summary 리더 displayName 풀네임 기준).
// player-names.ts 의 RAW 는 축구 위주라 NHL 리더 누락 多 → 주요 선수 별도 누적.
// 신규 leader 등장 시 추가.

export const NHL_PLAYER_NAMES_KO: Record<string, string> = {
  "Connor McDavid": "코너 맥데이비드",
  "Leon Draisaitl": "리언 드라이자이틀",
  "Nathan MacKinnon": "네이선 매키넌",
  "Sidney Crosby": "시드니 크로스비",
  "Auston Matthews": "오스턴 매슈스",
  "Nikita Kucherov": "니키타 쿠체로프",
  "Cale Makar": "케일 매카",
  "Connor Hellebuyck": "코너 헬레부이크",
  "David Pastrnak": "다비드 파스트르나크",
  "Mitch Marner": "미치 마너",
  "Artemi Panarin": "아르테미 파나린",
  "Jack Hughes": "잭 휴스",
  "Quinn Hughes": "퀸 휴스",
  "Matthew Tkachuk": "매슈 트카척",
  "Brady Tkachuk": "브레이디 트카척",
  "Mikko Rantanen": "미코 란타넨",
  "Kirill Kaprizov": "키릴 카프리조프",
  "Aleksander Barkov": "알렉산데르 바르코프",
  "Igor Shesterkin": "이고리 셰스테르킨",
  "Roman Josi": "로만 요시",
  "Victor Hedman": "빅토르 헤드만",
  "Steven Stamkos": "스티븐 스탬코스",
  "Brad Marchand": "브래드 마찬드",
  "Sam Reinhart": "샘 라인하트",
  "Jason Robertson": "제이슨 로버트슨",
  "Tage Thompson": "테이지 톰슨",
  "Elias Pettersson": "엘리아스 페테르손",
  "Adam Fox": "애덤 폭스",
  "Sebastian Aho": "세바스티안 아호",
  "Sergei Bobrovsky": "세르게이 보브롭스키",
  "Carter Verhaeghe": "카터 베라이게",
  "William Nylander": "윌리엄 닐란데르",
  "John Tavares": "존 타바레스",
  "Jack Eichel": "잭 아이클",
  "Mark Stone": "마크 스톤",
  "Tim Stützle": "팀 슈튀츨레",
  "Tim Stutzle": "팀 슈튀츨레",
  "Filip Forsberg": "필립 포르스베리",
  "Clayton Keller": "클레이턴 켈러",
  "Kyle Connor": "카일 코너",
  "Mark Scheifele": "마크 샤이펠레",
  "Robert Thomas": "로버트 토머스",
  "Jordan Kyrou": "조던 키루",
  "Devon Toews": "데번 튜스",
  "Andrei Svechnikov": "안드레이 스베치니코프",
  "Nick Suzuki": "닉 스즈키",
  "Cole Caufield": "콜 코필드",
  "Juraj Slafkovsky": "유라이 슬라프콥스키",
  "Juraj Slafkovský": "유라이 슬라프콥스키",
  "Lane Hutson": "레인 허트슨",
  "Jesper Bratt": "예스페르 브라트",
  "Nico Hischier": "니코 히스키어",
  "Matt Boldy": "맷 볼디",
  "Wyatt Johnston": "와이엇 존스턴",
  "Dylan Larkin": "딜런 라킨",
  "Jake Guentzel": "제이크 권첼",
  "Bo Horvat": "보 호바트",
  "Mathew Barzal": "매슈 바질",
  "Elias Lindholm": "엘리아스 린드홀름",
};
