// 종목(sport) ↔ 리그(league) 매핑 + 한글 라벨.
// /scores 페이지 종목 탭에서 사용.

export type SportCode = "all" | "soccer" | "baseball" | "basketball" | "hockey" | "esports";

interface SportMeta {
  code: SportCode;
  label: string;
  emoji: string;
  leagues: string[]; // 우리 League 코드 (대문자)
}

// 모든 리그 묶음 — `all` 처리용 (URL 호환성, sportTab 노출 X)
export const ALL_LEAGUES = [
  "EPL", "LALIGA", "BUNDESLIGA", "SERIE_A", "LIGUE_1", "MLS", "UCL", "WORLD_CUP",
  "K_LEAGUE_1", "K_LEAGUE_2", "J1_LEAGUE", "J2_LEAGUE", "AFC_CL", "AFC_CL_TWO", "AFC_U23", "SAUDI_PL",
  "UEL", "UECL",
  "CHAMPIONSHIP", "LALIGA_2", "BUNDESLIGA_2", "SERIE_B", "LIGUE_2",
  "EREDIVISIE", "PRIMEIRA_LIGA", "SUPER_LIG", "JUPILER_PL", "SPL", "GREEK_SL",
  "EKSTRAKLASA", "POLAND_1L", "BULGARIA_PL", "LIGA_I", "SWISS_SL", "CHALLENGE_LEAGUE", "ARMENIA_PL",
  "AUSTRIA_BL", "CZECH_L", "HNL", "UKRAINE_PL", "HUNGARY_NB1",
  "SERBIA_SL", "SLOVAKIA_SL", "SLOVENIA_SNL", "CYPRUS_1D", "DENMARK_SL",
  "IRELAND_PD", "BOSNIA_PL", "ALBANIA_SL", "MOLDOVA_SL",
  "ELITESERIEN", "NORWAY_1L", "ALLSVENSKAN", "SUPERETTAN",
  "VEIKKAUSLIIGA", "YKKONEN", "URVALSDEILD", "ICELAND_1L",
  "LIGA_MX", "BRASILEIRAO", "COPA_LIB", "COPA_SUD",
  "CHILE_PD", "CHILE_PB", "ECUADOR_LP", "COLOMBIA_PA", "PERU_PD", "VENEZUELA_PD",
  "EGYPT_PL", "ISRAEL_PL", "INDIA_ISL", "VIETNAM_VL1", "INDONESIA_L1", "SINGAPORE_PL",
  "UAE_PL", "QATAR_SL", "MOROCCO_BP", "SOUTHAFRICA_PSL",
  "USA_USL_CH", "CANADA_PL",
  "CSL", "A_LEAGUE",
  "CLUB_WORLD_CUP",
  "FA_CUP", "EFL_CUP", "COPA_DEL_REY", "COPPA_ITALIA", "DFB_POKAL",
  "COUPE_DE_FRANCE", "KFA_CUP", "EMPEROR_CUP", "CONCACAF_CCUP", "AFC_CUP",
  "KBO", "NPB", "MLB",
  "NBA", "NHL", "LOL",
];

export const SPORTS: SportMeta[] = [
  {
    code: "soccer",
    label: "축구",
    emoji: "⚽",
    leagues: [
      "K_LEAGUE_1", "K_LEAGUE_2", "AFC_CL", "AFC_CL_TWO", "AFC_U23",
      "J1_LEAGUE", "J2_LEAGUE",
      "UCL", "UEL", "UECL",
      "EPL", "CHAMPIONSHIP",
      "LALIGA", "LALIGA_2",
      "BUNDESLIGA", "BUNDESLIGA_2",
      "SERIE_A", "SERIE_B",
      "LIGUE_1", "LIGUE_2",
      "EREDIVISIE", "PRIMEIRA_LIGA", "SUPER_LIG", "JUPILER_PL", "SPL", "GREEK_SL",
      "EKSTRAKLASA", "POLAND_1L", "BULGARIA_PL", "LIGA_I", "SWISS_SL", "CHALLENGE_LEAGUE", "ARMENIA_PL",
      "AUSTRIA_BL", "CZECH_L", "HNL", "UKRAINE_PL", "HUNGARY_NB1",
      "SERBIA_SL", "SLOVAKIA_SL", "SLOVENIA_SNL", "CYPRUS_1D", "DENMARK_SL",
      "IRELAND_PD", "BOSNIA_PL", "ALBANIA_SL", "MOLDOVA_SL",
      "ELITESERIEN", "NORWAY_1L", "ALLSVENSKAN", "SUPERETTAN",
      "VEIKKAUSLIIGA", "YKKONEN", "URVALSDEILD", "ICELAND_1L",
      "MLS", "LIGA_MX", "BRASILEIRAO", "COPA_LIB", "COPA_SUD",
      "CHILE_PD", "CHILE_PB", "ECUADOR_LP", "COLOMBIA_PA", "PERU_PD", "VENEZUELA_PD",
      "EGYPT_PL", "ISRAEL_PL", "INDIA_ISL", "VIETNAM_VL1", "INDONESIA_L1", "SINGAPORE_PL",
      "UAE_PL", "QATAR_SL", "MOROCCO_BP", "SOUTHAFRICA_PSL",
      "USA_USL_CH", "CANADA_PL",
      "CSL", "A_LEAGUE", "SAUDI_PL",
      "CLUB_WORLD_CUP", "WORLD_CUP",
      // 컵 대회 — 메이저 5 + 한국·일본·CONCACAF·AFC
      "FA_CUP", "EFL_CUP", "COPA_DEL_REY", "COPPA_ITALIA", "DFB_POKAL",
      "COUPE_DE_FRANCE", "KFA_CUP", "EMPEROR_CUP", "CONCACAF_CCUP", "AFC_CUP",
    ],
  },
  {
    code: "baseball",
    label: "야구",
    emoji: "⚾",
    leagues: ["KBO", "NPB", "MLB"],
  },
  {
    code: "basketball",
    label: "농구",
    emoji: "🏀",
    leagues: ["NBA", "WNBA"],
  },
  {
    code: "hockey",
    label: "하키",
    emoji: "🏒",
    leagues: ["NHL"],
  },
  {
    code: "esports",
    label: "e스포츠",
    emoji: "🎮",
    leagues: ["LOL"],
  },
];

export function leaguesForSport(code: SportCode): string[] {
  if (code === "all") return ALL_LEAGUES;
  return SPORTS.find((s) => s.code === code)?.leagues ?? ALL_LEAGUES;
}

export const LEAGUE_DISPLAY: Record<string, string> = {
  EPL: "프리미어리그",
  LALIGA: "라리가",
  BUNDESLIGA: "분데스리가",
  SERIE_A: "세리에 A",
  LIGUE_1: "리그 1",
  MLS: "MLS",
  UCL: "챔피언스리그",
  WORLD_CUP: "FIFA 월드컵 2026",
  K_LEAGUE_1: "K리그 1",
  K_LEAGUE_2: "K리그 2",
  J1_LEAGUE: "J1 리그",
  J2_LEAGUE: "J2 리그",
  AFC_CL: "AFC 챔피언스리그",
  SAUDI_PL: "사우디 프로 리그",
  UEL: "유로파 리그",
  UECL: "유로파 컨퍼런스",
  CHAMPIONSHIP: "잉글랜드 챔피언십",
  LALIGA_2: "라리가 2",
  BUNDESLIGA_2: "분데스리가 2",
  SERIE_B: "세리에 B",
  LIGUE_2: "리그 2",
  CLUB_WORLD_CUP: "FIFA 클럽 월드컵",
  AFC_CL_TWO: "AFC 챔피언스리그 2",
  AFC_U23: "AFC U23 아시안컵",
  CSL: "중국 슈퍼리그",
  A_LEAGUE: "A-리그",
  EREDIVISIE: "에레디비시",
  PRIMEIRA_LIGA: "프리메이라 리가",
  SUPER_LIG: "쉬페르 리그",
  JUPILER_PL: "주피러 프로 리그",
  SPL: "스코틀랜드 프리미어십",
  GREEK_SL: "그리스 슈퍼리그",
  EKSTRAKLASA: "에크스트라클라사",
  POLAND_1L: "폴란드 I 리가",
  BULGARIA_PL: "불가리아 퍼스트 리그",
  LIGA_I: "루마니아 리가 I",
  SWISS_SL: "스위스 슈퍼리그",
  CHALLENGE_LEAGUE: "스위스 챌린지 리그",
  ARMENIA_PL: "아르메니아 프리미어 리그",
  AUSTRIA_BL: "오스트리아 분데스리가",
  CZECH_L: "체코 1부",
  HNL: "크로아티아 HNL",
  UKRAINE_PL: "우크라이나 프리미어 리그",
  HUNGARY_NB1: "헝가리 NB I",
  SERBIA_SL: "세르비아 슈퍼리가",
  SLOVAKIA_SL: "슬로바키아 슈퍼리가",
  SLOVENIA_SNL: "슬로베니아 1. SNL",
  CYPRUS_1D: "키프로스 1부",
  DENMARK_SL: "덴마크 슈페르리가",
  IRELAND_PD: "아일랜드 프리미어",
  BOSNIA_PL: "보스니아 프리미어",
  ALBANIA_SL: "알바니아 슈페르리가",
  MOLDOVA_SL: "몰도바 슈페르리가",
  ELITESERIEN: "노르웨이 엘리테세리엔",
  NORWAY_1L: "노르웨이 1부 디비전",
  ALLSVENSKAN: "스웨덴 알스벤스칸",
  SUPERETTAN: "스웨덴 수페레탄",
  VEIKKAUSLIIGA: "핀란드 베이카우슬리가",
  YKKONEN: "핀란드 위쾨넨",
  URVALSDEILD: "아이슬란드 우르발스데일드",
  ICELAND_1L: "아이슬란드 1부 데일드",
  CHILE_PD: "칠레 프리메라 디비시온",
  CHILE_PB: "칠레 프리메라 B",
  ECUADOR_LP: "에콰도르 리가 프로",
  COLOMBIA_PA: "콜롬비아 프리메라 A",
  PERU_PD: "페루 프리메라 디비시온",
  VENEZUELA_PD: "베네수엘라 프리메라 디비시온",
  EGYPT_PL: "이집트 프리미어 리그",
  ISRAEL_PL: "이스라엘 리가트 하알",
  INDIA_ISL: "인도 슈퍼 리그",
  VIETNAM_VL1: "베트남 V-리그 1",
  INDONESIA_L1: "인도네시아 리가 1",
  SINGAPORE_PL: "싱가포르 프리미어 리그",
  UAE_PL: "UAE 프로 리그",
  QATAR_SL: "카타르 스타스 리그",
  MOROCCO_BP: "모로코 보톨라 프로",
  SOUTHAFRICA_PSL: "남아공 PSL",
  USA_USL_CH: "USL 챔피언십",
  CANADA_PL: "캐나다 프리미어 리그",
  BRASILEIRAO: "브라질 세리에 A",
  LIGA_MX: "리가 MX",
  COPA_LIB: "코파 리베르타도레스",
  COPA_SUD: "코파 수다메리카나",
  FA_CUP: "FA컵",
  EFL_CUP: "카라바오 컵",
  COPA_DEL_REY: "코파 델 레이",
  COPPA_ITALIA: "코파 이탈리아",
  DFB_POKAL: "DFB-포칼",
  COUPE_DE_FRANCE: "쿠프 드 프랑스",
  KFA_CUP: "KFA컵",
  EMPEROR_CUP: "천황배",
  CONCACAF_CCUP: "CONCACAF 챔피언스컵",
  AFC_CUP: "AFC컵",
  KBO: "KBO 리그",
  NPB: "NPB 일본프로야구",
  MLB: "메이저리그",
  NBA: "NBA",
  WNBA: "WNBA",
  NHL: "NHL",
  LOL: "LCK",
};

/** 정렬 우선순위 (낮을수록 위) — KBO/NPB 한국 시청자 우선 */
export const LEAGUE_ORDER: Record<string, number> = {
  KBO: 0,
  NPB: 1,
  MLB: 2,
  K_LEAGUE_1: 5,
  K_LEAGUE_2: 6,
  AFC_CL: 7,
  AFC_CL_TWO: 7.5,
  AFC_U23: 7.7,
  J1_LEAGUE: 8,
  J2_LEAGUE: 9,
  EPL: 10,
  CHAMPIONSHIP: 10.5,
  UCL: 11,
  UEL: 11.5,
  UECL: 11.7,
  LALIGA: 12,
  LALIGA_2: 12.5,
  BUNDESLIGA: 13,
  BUNDESLIGA_2: 13.5,
  SERIE_A: 14,
  SERIE_B: 14.5,
  LIGUE_1: 15,
  LIGUE_2: 15.5,
  EREDIVISIE: 15.6,
  PRIMEIRA_LIGA: 15.65,
  SUPER_LIG: 15.7,
  JUPILER_PL: 15.75,
  SPL: 15.8,
  GREEK_SL: 15.85,
  SWISS_SL: 15.86,
  AUSTRIA_BL: 15.861,
  EKSTRAKLASA: 15.87,
  DENMARK_SL: 15.872,
  CZECH_L: 15.873,
  HNL: 15.874,
  UKRAINE_PL: 15.875,
  LIGA_I: 15.88,
  BULGARIA_PL: 15.89,
  ARMENIA_PL: 15.9,
  HUNGARY_NB1: 15.901,
  SERBIA_SL: 15.902,
  SLOVAKIA_SL: 15.903,
  SLOVENIA_SNL: 15.904,
  CYPRUS_1D: 15.905,
  BOSNIA_PL: 15.906,
  ALBANIA_SL: 15.907,
  MOLDOVA_SL: 15.908,
  IRELAND_PD: 15.909,
  CHALLENGE_LEAGUE: 15.91,
  POLAND_1L: 15.92,
  ELITESERIEN: 15.93,
  ALLSVENSKAN: 15.931,
  VEIKKAUSLIIGA: 15.932,
  URVALSDEILD: 15.933,
  NORWAY_1L: 15.934,
  SUPERETTAN: 15.935,
  YKKONEN: 15.936,
  ICELAND_1L: 15.937,
  COLOMBIA_PA: 16.21,
  CHILE_PD: 16.22,
  ECUADOR_LP: 16.23,
  PERU_PD: 16.24,
  VENEZUELA_PD: 16.25,
  CHILE_PB: 16.26,
  USA_USL_CH: 16.51,
  CANADA_PL: 16.52,
  EGYPT_PL: 16.6,
  MOROCCO_BP: 16.61,
  SOUTHAFRICA_PSL: 16.62,
  UAE_PL: 16.63,
  QATAR_SL: 16.64,
  ISRAEL_PL: 16.65,
  INDIA_ISL: 16.7,
  VIETNAM_VL1: 16.71,
  INDONESIA_L1: 16.72,
  SINGAPORE_PL: 16.73,
  MLS: 16,
  LIGA_MX: 16.1,
  BRASILEIRAO: 16.2,
  COPA_LIB: 16.3,
  COPA_SUD: 16.35,
  CSL: 16.4,
  A_LEAGUE: 16.45,
  SAUDI_PL: 16.5,
  CLUB_WORLD_CUP: 17,
  WORLD_CUP: 18,
  // 컵 대회 — 각 자국 리그 그룹 바로 뒤 (소수점 .6~.7 대 활용)
  KFA_CUP: 5.5, // K리그 바로 다음
  EMPEROR_CUP: 8.5, // J리그 다음
  AFC_CUP: 7.8, // AFC_CL_TWO 다음
  FA_CUP: 10.1, // EPL 다음 — 컵 노출 우선
  EFL_CUP: 10.2,
  COPA_DEL_REY: 12.1, // LALIGA 다음
  DFB_POKAL: 13.1, // BUNDESLIGA 다음
  COPPA_ITALIA: 14.1, // SERIE_A 다음
  COUPE_DE_FRANCE: 15.1, // LIGUE_1 다음
  CONCACAF_CCUP: 16.05, // MLS 다음
  NBA: 20,
  NHL: 21,
  LOL: 30,
};

/** 축구 사이드바 — 인기 리그 (상단 고정 노출) */
export const POPULAR_SOCCER_LEAGUES: string[] = [
  "UCL",
  "UEL",
  "UECL",
  "EPL",
  "LALIGA",
  "BUNDESLIGA",
  "SERIE_A",
  "LIGUE_1",
  "K_LEAGUE_1",
];

/** 축구 리그 → 국가명 (사이드바 그룹화). 대륙 대회는 "국제". */
export const COUNTRY_BY_LEAGUE: Record<string, string> = {
  // 대한민국
  K_LEAGUE_1: "대한민국",
  K_LEAGUE_2: "대한민국",
  // 일본
  J1_LEAGUE: "일본",
  J2_LEAGUE: "일본",
  // 잉글랜드
  EPL: "잉글랜드",
  CHAMPIONSHIP: "잉글랜드",
  // 스페인
  LALIGA: "스페인",
  LALIGA_2: "스페인",
  // 독일
  BUNDESLIGA: "독일",
  BUNDESLIGA_2: "독일",
  // 이탈리아
  SERIE_A: "이탈리아",
  SERIE_B: "이탈리아",
  // 프랑스
  LIGUE_1: "프랑스",
  LIGUE_2: "프랑스",
  // 그 외 유럽
  EREDIVISIE: "네덜란드",
  PRIMEIRA_LIGA: "포르투갈",
  SUPER_LIG: "튀르키예",
  JUPILER_PL: "벨기에",
  SPL: "스코틀랜드",
  GREEK_SL: "그리스",
  EKSTRAKLASA: "폴란드",
  POLAND_1L: "폴란드",
  BULGARIA_PL: "불가리아",
  LIGA_I: "루마니아",
  SWISS_SL: "스위스",
  CHALLENGE_LEAGUE: "스위스",
  ARMENIA_PL: "아르메니아",
  AUSTRIA_BL: "오스트리아",
  CZECH_L: "체코",
  HNL: "크로아티아",
  UKRAINE_PL: "우크라이나",
  HUNGARY_NB1: "헝가리",
  SERBIA_SL: "세르비아",
  SLOVAKIA_SL: "슬로바키아",
  SLOVENIA_SNL: "슬로베니아",
  CYPRUS_1D: "키프로스",
  DENMARK_SL: "덴마크",
  IRELAND_PD: "아일랜드",
  BOSNIA_PL: "보스니아",
  ALBANIA_SL: "알바니아",
  MOLDOVA_SL: "몰도바",
  ELITESERIEN: "노르웨이",
  NORWAY_1L: "노르웨이",
  ALLSVENSKAN: "스웨덴",
  SUPERETTAN: "스웨덴",
  VEIKKAUSLIIGA: "핀란드",
  YKKONEN: "핀란드",
  URVALSDEILD: "아이슬란드",
  ICELAND_1L: "아이슬란드",
  // 북·중미
  MLS: "미국",
  USA_USL_CH: "미국",
  CANADA_PL: "캐나다",
  LIGA_MX: "멕시코",
  // 남미
  BRASILEIRAO: "브라질",
  CHILE_PD: "칠레",
  CHILE_PB: "칠레",
  ECUADOR_LP: "에콰도르",
  COLOMBIA_PA: "콜롬비아",
  PERU_PD: "페루",
  VENEZUELA_PD: "베네수엘라",
  // 아프리카·중동·아시아
  EGYPT_PL: "이집트",
  MOROCCO_BP: "모로코",
  SOUTHAFRICA_PSL: "남아프리카",
  UAE_PL: "UAE",
  QATAR_SL: "카타르",
  ISRAEL_PL: "이스라엘",
  SAUDI_PL: "사우디아라비아",
  INDIA_ISL: "인도",
  VIETNAM_VL1: "베트남",
  INDONESIA_L1: "인도네시아",
  SINGAPORE_PL: "싱가포르",
  CSL: "중국",
  A_LEAGUE: "호주",
  // 국제 / 대륙 대회
  UCL: "국제",
  UEL: "국제",
  UECL: "국제",
  AFC_CL: "국제",
  AFC_CL_TWO: "국제",
  AFC_U23: "국제",
  COPA_LIB: "국제",
  COPA_SUD: "국제",
  CLUB_WORLD_CUP: "국제",
  WORLD_CUP: "국제",
};

/** 국가명 → 국기 유니코드 이모지. "국제"는 지구본. */
export const COUNTRY_FLAG: Record<string, string> = {
  국제: "🌍",
  대한민국: "🇰🇷",
  일본: "🇯🇵",
  잉글랜드: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  스페인: "🇪🇸",
  독일: "🇩🇪",
  이탈리아: "🇮🇹",
  프랑스: "🇫🇷",
  네덜란드: "🇳🇱",
  포르투갈: "🇵🇹",
  튀르키예: "🇹🇷",
  벨기에: "🇧🇪",
  스코틀랜드: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  그리스: "🇬🇷",
  폴란드: "🇵🇱",
  불가리아: "🇧🇬",
  루마니아: "🇷🇴",
  스위스: "🇨🇭",
  아르메니아: "🇦🇲",
  오스트리아: "🇦🇹",
  체코: "🇨🇿",
  크로아티아: "🇭🇷",
  우크라이나: "🇺🇦",
  헝가리: "🇭🇺",
  세르비아: "🇷🇸",
  슬로바키아: "🇸🇰",
  슬로베니아: "🇸🇮",
  키프로스: "🇨🇾",
  덴마크: "🇩🇰",
  아일랜드: "🇮🇪",
  보스니아: "🇧🇦",
  알바니아: "🇦🇱",
  몰도바: "🇲🇩",
  노르웨이: "🇳🇴",
  스웨덴: "🇸🇪",
  핀란드: "🇫🇮",
  아이슬란드: "🇮🇸",
  미국: "🇺🇸",
  캐나다: "🇨🇦",
  멕시코: "🇲🇽",
  브라질: "🇧🇷",
  칠레: "🇨🇱",
  에콰도르: "🇪🇨",
  콜롬비아: "🇨🇴",
  페루: "🇵🇪",
  베네수엘라: "🇻🇪",
  이집트: "🇪🇬",
  모로코: "🇲🇦",
  남아프리카: "🇿🇦",
  UAE: "🇦🇪",
  카타르: "🇶🇦",
  이스라엘: "🇮🇱",
  사우디아라비아: "🇸🇦",
  인도: "🇮🇳",
  베트남: "🇻🇳",
  인도네시아: "🇮🇩",
  싱가포르: "🇸🇬",
  중국: "🇨🇳",
  호주: "🇦🇺",
};

/** 국가 정렬 순서 — 국제·대한민국·일본 우선, 나머지 A–Z (한국어 가나다순). */
export const COUNTRY_ORDER: string[] = [
  "국제",
  "대한민국",
  "일본",
  "잉글랜드",
  "스페인",
  "독일",
  "이탈리아",
  "프랑스",
  "네덜란드",
  "포르투갈",
  "튀르키예",
  "벨기에",
  "스코틀랜드",
  "그리스",
  "폴란드",
  "불가리아",
  "루마니아",
  "스위스",
  "아르메니아",
  "오스트리아",
  "체코",
  "크로아티아",
  "우크라이나",
  "헝가리",
  "세르비아",
  "슬로바키아",
  "슬로베니아",
  "키프로스",
  "덴마크",
  "아일랜드",
  "보스니아",
  "알바니아",
  "몰도바",
  "노르웨이",
  "스웨덴",
  "핀란드",
  "아이슬란드",
  "미국",
  "캐나다",
  "멕시코",
  "브라질",
  "칠레",
  "에콰도르",
  "콜롬비아",
  "페루",
  "베네수엘라",
  "이집트",
  "모로코",
  "남아프리카",
  "UAE",
  "카타르",
  "이스라엘",
  "사우디아라비아",
  "인도",
  "베트남",
  "인도네시아",
  "싱가포르",
  "중국",
  "호주",
];
