// WNBA 선수 영문 → 한글 매핑.
// api-sports basketball player.name (풀네임) 기준 — route WNBA 분기에서 toKoreanPlayerName 으로 변환.
// 신규 leader 등장 시 추가.

export const WNBA_PLAYER_NAMES_KO: Record<string, string> = {
  "A'ja Wilson": "아자 윌슨",
  "Breanna Stewart": "브리아나 스튜어트",
  "Caitlin Clark": "케이틀린 클라크",
  "Sabrina Ionescu": "사브리나 이오네스쿠",
  "Napheesa Collier": "나피사 콜리어",
  "Alyssa Thomas": "얼리사 토머스",
  "Jonquel Jones": "종켈 존스",
  "Kelsey Plum": "켈시 플럼",
  "Jewell Loyd": "주얼 로이드",
  "Arike Ogunbowale": "아리케 오건보왈레",
  "Chelsea Gray": "첼시 그레이",
  "Nneka Ogwumike": "느네카 오궈마이케",
  "Jackie Young": "재키 영",
  "Brittney Griner": "브리트니 그라이너",
  "Kahleah Copper": "칼리아 코퍼",
  "Aliyah Boston": "얼라이아 보스턴",
  "Angel Reese": "에인절 리스",
  "Diana Taurasi": "다이애나 터라시",
  "Satou Sabally": "사토우 사발리",
  "Rhyne Howard": "라인 하워드",
  "Dearica Hamby": "디어리카 햄비",
  "DeWanna Bonner": "디원나 보너",
  "Courtney Vandersloot": "코트니 밴더슬루트",
  "Skylar Diggins": "스카일러 디긴스",
  "Skylar Diggins-Smith": "스카일러 디긴스",
  "Kelsey Mitchell": "켈시 미첼",
  "Allisha Gray": "얼리샤 그레이",
  "Ezi Magbegor": "에지 마그베고르",
  "Gabby Williams": "개비 윌리엄스",
  "Paige Bueckers": "페이지 베커스",
  "Kamilla Cardoso": "카밀라 카르도주",
  "Nalyssa Smith": "날리사 스미스",
  "Marina Mabrey": "머리나 메이브리",
  "Brionna Jones": "브리오나 존스",
  "Dana Evans": "데이나 에번스",
  "Tina Charles": "티나 찰스",
  "Sophie Cunningham": "소피 커닝햄",
  "Jacy Sheldon": "제이시 셸던",
  "Veronica Burton": "베로니카 버턴",
  "Kayla McBride": "케일라 맥브라이드",
};
